### ISSUE TITLE
Link to download 20.04 beta ISO not present

### ISSUE THREAD

**Issue by richerve** [pop-os/beta#1]
I don't know if this is expected as the 20.04 ISO is not ready yet, but I've noticed that in the README there's a section stating to download the ISO from "here", but no link is present.

**Comment by tocsinde** [comment]
I found these two links, but I can't tell how old these images are (the "3" might indicate a 3rd beta?), so use with caution.

Intel: https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/3/pop-os_20.04_amd64_intel_3.iso

NVIDIA: https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/nvidia/3/pop-os_20.04_amd64_nvidia_3.iso

**Comment by tocsinde** [comment]
Source: https://www.reddit.com/r/pop_os/comments/ethiyf/my_computer_says_that_popos_2004_is_available/

**Comment by jackpot51** [comment]
Those are not official links @tocsinde. They are not beta, they are alpha. We will be releasing a 20.04 beta ISO when it is ready

**Comment by mikemadden42** [comment]
@richerve The 20.04 beta is officially out now. 🥳 
https://github.com/pop-os/beta

**Comment by richerve** [comment]
Thank you
