### ISSUE TITLE
[20.04] Bios  contains WGDS but not WRDS

### ISSUE THREAD

**Issue by amithiel** [pop-os/beta#101]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Fresh
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

on startup before getting to login screen, flashes several times this error message: 
[ 5.955404] iwlwifi 0000:00:14.3: BIOS contains WGDS but not WRDS,
On pop!_os 19.19 didn't happened, neither does on ubuntu 20.04.
here's more info:

journalctl -k| grep iwlwifi
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: enabling device (0000 -> 0002)
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: Found debug destination: EXTERNAL_DRAM
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: Found debug configuration: 0
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: loaded firmware version 46.6bf1df06.0 op_mode iwlmvm
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: Detected Intel(R) Dual Band Wireless AC 9560, REV=0x318
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: Applying debug destination EXTERNAL_DRAM
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: Allocated 0x00400000 bytes for firmware monitor.
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3: base HW address: 18:56:80:cd:bf:77
Apr 27 16:35:45 zamorak kernel: iwlwifi 0000:00:14.3 wlo1: renamed from wlan0
Apr 27 16:35:47 zamorak kernel: iwlwifi 0000:00:14.3: Applying debug destination EXTERNAL_DRAM
Apr 27 16:35:47 zamorak kernel: iwlwifi 0000:00:14.3: Applying debug destination EXTERNAL_DRAM
Apr 27 16:35:47 zamorak kernel: iwlwifi 0000:00:14.3: FW already configured (0) - re-configuring
Apr 27 16:35:47 zamorak kernel: iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS

**Steps to reproduce (if you know):**

Reboot/startup the machine. Also you can see it flashing when resuming from suspend (although its not so much annoying because it flahes only once).

**Expected behavior:**

**Other Notes:**

My wifi works just fine, its just annoying seeing that error many times (as it's a bootscreen itself).

**Comment by Radhesh-Sarma** [comment]
I am also getting the same message , any fixes yet?

**Comment by amithiel** [comment]
> I am also getting the same message , any fixes yet?

Nope. Its the only error i get when booting up. but its there every damn time =/

**Comment by SleepySlippers** [comment]
Any fix suggestion? Why close? Having same message now.
