### ISSUE TITLE
SSL certificate problem for download url:

### ISSUE THREAD

**Issue by rvanlaar** [pop-os/beta#102]
**Issue/Bug Description:**

Firefox issues a warning when downloading the images.

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for pop-iso.sfo2.cdn.digitaloceanspaces.com. The certificate is only valid for the following names: *.ssl.hwcdn.net, ssl.hwcdn.net
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
**Steps to reproduce (if you know):**

Open the following URL in Firefox:
https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/4/pop-os_20.04_amd64_intel_4.iso

**Expected behavior:**
It to work with a valid certificate

**Other Notes:**
It would a great if there was a shasum file as well to verify the download.

**Comment by jackpot51** [comment]
SHASUM file is at https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/4/SHA256SUMS with GPG signature at https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/4/SHA256SUMS.gpg

**Comment by brs17** [comment]
Pop!_OS 20.04 has been released and the shasums are updated and posted with the iso links at pop.system76.com
