### ISSUE TITLE
When is LTS coming out?

### ISSUE THREAD

**Issue by mdhishaamakhtar** [pop-os/beta#103]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
 From 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not a specific Package

**Issue/Bug Description:**
No issues

**Steps to reproduce (if you know):**
No issue

**Expected behavior:**
No issue

**Other Notes:**
I just wanted to ask when is the LTS version expected to release?

**Comment by WatchMkr** [comment]
April 30th
