### ISSUE TITLE
Launcher Issue

### ISSUE THREAD

**Issue by lunarark** [pop-os/beta#104]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Launcher (SUPER + /)
arrow function sometimes doesnt work

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by brs17** [comment]
@lunarark are you still having issues running the latest version of pop-shell? Can you describe the issues you're having with a little bit more detail? A screenrecording with detail of what keys you are pressing would probably be the most helpful.

**Comment by brs17** [comment]
The launcher and the shell additions in 20.04 received a big update yesterday that resolved a number of issues. Hopefully your issue has been resolved. If it has not feel free to create an issue here: https://github.com/pop-os/shell/issues
