### ISSUE TITLE
Firefox Title window

### ISSUE THREAD

**Issue by thenitai** [pop-os/beta#105]
Upgraded from 19.10 to 20.04. Been running the beta for some weeks now (since the initial release) and have not encountered any issues. Except for this visual glitch with the Firefox Title bar.

![image](https://user-images.githubusercontent.com/372121/80422650-8e37de80-88ac-11ea-8d82-1ec79e816b10.png)

Now, before anyone yells at me to go to "Customize", this does not work anymore. Furthermore, the setting takes no effect.

Just wondering if this is a Firefox issue (most likely as Firefox is the only one with this issue) or something else.

**Comment by leviport** [comment]
Thanks for the report! We're tracking the Firefox titlebar bug here: https://github.com/pop-os/beta/issues/2
