### ISSUE TITLE
Will LTS version need an upgrade from Beta?

### ISSUE THREAD

**Issue by mdhishaamakhtar** [pop-os/beta#106]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
19.10

**Other Notes:**
When the LTS version is released on 30th April, will the beta version which we downloaded now need another full upgrade?

**Comment by brs17** [comment]
No it will not. Running normal updates through Pop!_Shop or the terminal will be sufficient to stay up to date until the next release (20.10)
