### ISSUE TITLE
Numerous Packages with dependency errors

### ISSUE THREAD

**Issue by zaphod80013** [pop-os/beta#107]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Fresh install on Galpro3-c
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

forensics-all/focal 3.18
orensics-all-gui/focal 3.18 
forensics-extra/focal,focal 2.14
forensics-extra-gui/focal,focal 2.14
vlc/focal 3.0.8-4
mpv/focal 0.32.0-1ubuntu1
digikam/focal 4:6.4.0+dfsg-3build1 
geeqie/focal 1:1.5.1-8build1
azebo9/focal 9.12.0+dfsg-1build2
gnuradio/focal 3.8.1.0~rc1-2build2
openjdk-8-jre/focal 8u252-b07-1
openjdk-13-jre/focal 13.0.2+8-2

**Issue/Bug Description:**

Above Packages all reporting dependency issues 

Mostly HTTP 404
Some Depends: xxxxx  but it is not going to be installed

libzmq5 seemed to be a common thread in some of these packages.

**Steps to reproduce (if you know):**

attempt to apt install said packages

**Expected behavior:**

Package dependencies to be correct, Package install to be tested before release

**Other Notes:**

**Comment by brs17** [comment]
I was just able to install vlc and gnuradio just fine. Is this still an issue you are encountering?

**Comment by bflanagin** [comment]
Thank you for submitting this issue. We are now working toward the 21.04 release and will be closing old issues to make room for newer ones. If this problem still persists please reopen and respond to this issue.
