### ISSUE TITLE
Pop!_Shop lists 2 null drivers under "Installed" tab

### ISSUE THREAD

**Issue by bobzhu418** [pop-os/beta#108]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Shop

**Issue/Bug Description:**

Under "Installed" tab, 2 null drivers are listed at the top, with "Install" button which will give error if clicked.

**Steps to reproduce (if you know):**

**Expected behavior:**

No null drivers

**Other Notes:**

This seems to appear after I applied the latest flatpak-nvidia update.

**Comment by lunarark** [comment]
i have got some issues with new update nvidia driver via pop_OS shop
![Screenshot from 2020-04-28 11-59-50](https://user-images.githubusercontent.com/63534831/80448903-ec65cf80-8947-11ea-9a0a-2cd8839ffe60.png)

**Comment by deyvisonrocha** [comment]
Some problem here.

**Comment by Rysher** [comment]
I can confirm that as @lunarark attached screen shot, I get this problem as well, exactly the same, only I have an AMD CPU and an AMD GPU, no nVidia.
(Ryzen 3 3900X + Sapphire Radeon RX5700).
This issue did not occure on Pop 19.10 or previous releases

**Comment by bwat47** [comment]
I see the same on a darter pro (in my case it just shows 1 null driver)

I don't have any flatpak packages installed afaik

**Comment by dcominottim** [comment]
Not fixed yet for me, even with the latest updates (have just double-checked) and rebooting multiple times. `ubuntu-drivers` list gives the output

`backport-iwlwifi-dkms, (kernel modules provided by backport-iwlwifi-dkms)`

**Comment by jackpot51** [comment]
Can you run `apt-cache policy pop-shop` ?

**Comment by dcominottim** [comment]
Sure. Here it is.

`pop-shop:
  Installed: 3.1.1pop0~1588203946~20.04~f106def
  Candidate: 3.1.1pop0~1588203946~20.04~f106def
  Version table:
 *** 3.1.1pop0~1588203946~20.04~f106def 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status`

**Comment by dcominottim** [comment]
Oh, I've just opened Pop!_Shop again the the entry was gone. Haven't updated anything today, just installed a couple new packages in the afternoon (I rebooted several times before installing them and it didn't solve the issue, but maybe it did after installing them?). Anyway, thanks a lot for the great support!

**Comment by jackpot51** [comment]
Glad that it's working now
