### ISSUE TITLE
Pop! OS Logo disappear from System Settings

### ISSUE THREAD

**Issue by SwisSlow** [pop-os/beta#111]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
User Themes (last version)

**Issue/Bug Description:**
After Enable User Themes Extensions and apply via Gnome-Tweaks, the logo of Pop! OS disappear from the information in System Settings, and showing Debian Logo.

**Steps to reproduce (if you know):**
I've try to format and install User Themes with and without any update, i loose the logo everytime
![Schermata da 2020-04-28 18-58-28](https://user-images.githubusercontent.com/64490436/80515492-58fdc000-8982-11ea-80e4-00d2863de94a.png)

**Comment by cassidyjames** [comment]
The OS icon is provided by the icon theme. If you change the icon theme, it changes the icon used for the OS.

**Comment by SwisSlow** [comment]
> The OS icon is provided by the icon theme. If you change the icon theme, it changes the icon used for the OS.

You're right...sorry!! Any way to change the icon theme and keep Pop logo?

**Comment by brs17** [comment]
> > The OS icon is provided by the icon theme. If you change the icon theme, it changes the icon used for the OS.
> 
> You're right...sorry!! Any way to change the icon theme and keep Pop logo?

You could see if the icon theme you are using will carry the Pop!_OS logo! You can find the Pop!_OS logo and other icons here: https://github.com/pop-os/icon-theme
