### ISSUE TITLE
Raise first window

### ISSUE THREAD

**Issue by thenitai** [pop-os/beta#112]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Raise first window setting doesn't work anymore.

In 19.10 one could set to NOT raise the first window only. This has either changed (I hope not) or is a bug.

**Steps to reproduce (if you know):**

In Tweaks set "Raise first window"

**Other Notes:**

I hope this is only a bug as I do have multiple windows open of the same application and since 20.04 beta switching between app makes me also switch between windows now.

**Comment by bflanagin** [comment]
Thank you for submitting this issue. We are now working toward the 21.04 release and will be closing old issues to make room for newer ones. If this problem still persists please reopen and respond to this issue.
