### ISSUE TITLE
[20.04] Chrome doesn't quit and windows remain in dock right click menu

### ISSUE THREAD

**Issue by nlander** [pop-os/beta#114]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Upgraded from 19.10
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Issue/Bug Description:**
Chrome windows cannot be fully closed. They still show up in the menu when right clicking the chrome icon in the dock. Once the window has been closed, however, the window cannot be reopened from the dock menu either.

**Steps to reproduce (if you know):**
- make sure Chrome is in the dock
- open Chrome from the dock
- close the window by clicking the x with the mouse
- press super to open dock, then right click the Chrome icon. Notice the window you just closed is in the menu.
- Try clicking the menu item for the closed window. Notice that the window doesn't open.

**Expected behavior:**
Clicking the x to close the last Chrome window should quit Chrome.
Clicking the x on a Chrome window should at least remove it from the dock icon right-click menu if there are any other Chrome windows open.

**Other Notes:**

**Comment by leviport** [comment]
Thank you for the report. We are tracking this here: https://github.com/pop-os/shell/issues/220
