### ISSUE TITLE
Error in Upgrade

### ISSUE THREAD

**Issue by mdhishaamakhtar** [pop-os/beta#116]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
19.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
```bash
release upgrade aborted: fetch of package 'tpm-udev_0.4_all.deb' at http://us.archive.ubuntu.com/ubuntu/pool/main/t/tpm-udev/tpm-udev_0.4_all.deb failed: async fetch for "/var/cache/apt/archives/partial/tpm-udev_0.4_all.deb" failed: http://us.archive.ubuntu.com/ubuntu/pool/main/t/tpm-udev/tpm-udev_0.4_all.deb: connection closed before message completed
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed
```

**Steps to reproduce (if you know):**
Just ran the command to upgrade

**Expected behavior:**
It should have fetched

**Other Notes:**
How to fix?

**Comment by seekjimmyg** [comment]
Try again after sudo systemctl restart pop-upgrade.service
