### ISSUE TITLE
[20.04]

### ISSUE THREAD

**Issue by Rysher** [pop-os/beta#119]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
fresh install

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

multiple built-in pop-shop applications: BRLTTY, character map, Comic Books, Document Scanner, Eye Of Gnome, Gnome Fonts, Gnome Help, Gnome Power Statistics, Gnome Screenshot, PPTP VPN Client, Printers.

**Issue/Bug Description:**
Unable to remove these un-needed applications that serve no purpose as a message appears saying that they are required by pop-desktop and/or yelp (WTF does a linux DE have to do with yelp?!?). As I understand this means that for example BRLTTY (which is meant for blind people, judging from the package description) is a dependency of the pop-desktop, which will break the graphical environment. This is of course absord to have a graphical environment dependant of an accessibilty feature meant for blind people. I also have no scanners or printers so document scanner and printers are also un-needed and serve no meaningful purpose on my machines, I also was able to remove them without any problems on 19.10 and previous releases.

**Steps to reproduce (if you know):**
Enter pop-shop and try to uninstall any of the above mentioned packages, or try to remove them by 'sudo apt remove' via the terminal.

**Expected behavior:**
These packages should not be listed as a pop-desktop dependency, and a package like "yelp" should not be pre-installed (specially without user consent during system installation, this was one of the gripes many people had with Canonical for adding the Amazon application in the ISO), they serve no other packages but themselves. people that don't use VPNs, don't have printers or scanners and prefer Flameshot over gnome-screenshot should be allowed to remove these un-needed packages to clean their system and set it up like they need it to be.

**Other Notes:**
yelp?! really?!

**Comment by adamhassel** [comment]
Yelp has nothing to do with the website. It's Ubuntu's standard documentation browser.
```
$ apropos yelp
yelp (1)             - browse system documentation
```

**Comment by Rysher** [comment]
@adamhassel my bad than! lol
but still, the presence of this app even I wasn't wrong about it is besides the point.
why would removing Gnome's (admittedly under-acheiving) screen capture app would break a system-documentation browser, or even the graphical environment itself? it's not like deleting DLL files from the System32 directory on windows...

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.

**Comment by david-gherghita** [comment]
After upgrading to 22.04 and the kernel 5.16.19-76051619-generic brltty messes up the cp210x device driver used in Arduino. The only fix for this issue is uninstalling brltty, which on pop-os can't be done, as it's a dependency for pop-desktop. This should be addressed.

**Comment by essagl** [comment]
I agree
