### ISSUE TITLE
20.04 Application directory bug

### ISSUE THREAD

**Issue by akashpal-21** [pop-os/beta#120]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**: Upgrade

 From 19.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:** When there are a lot of programs inside a single directory, in the activities menu, >= 4 rows, the last row is not completely visible, and cannot be scrolled past that, resulting in the last row programs only showing icons and incomplete text.

**Steps to reproduce (if you know):**
Create a directory of applications >= 13 applications, scroll to the end.

**Expected behavior:**
The last row's application names are not visible

**Other Notes:**

![Screenshot from 2020-04-30 02-25-31](https://user-images.githubusercontent.com/46517170/80646604-ae24f900-8a8a-11ea-92b9-6b2e05d51038.png)

**Comment by Rysher** [comment]
I can confirm this on a clean install of the official release as well
