### ISSUE TITLE
[20.04] super-key functional inconsistancy across input-sources

### ISSUE THREAD

**Issue by Rysher** [pop-os/beta#121]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 clean install

**Issue/Bug Description:**
I have two input sources - english (US) and hebrew installed, when ever i'm not on the english input source the super key does not open Gnome's overview, only when I return to english input source it works as usual. even funnier - when I'm on hebrew and the super key by itself does not open the overview, the rest of the keyboard shortcuts that involve the super key DO work.
(I have the Corsair K95 keyboard with the ckb-next driver installed from a ppa), though I do not believe it should matter which keyboard you are using

**Steps to reproduce (if you know):**
switch to hebrew input source and press super key

**Expected behavior:**
the super key should respond in the same manner no matter which input source is active

**Other Notes:**
none

**Comment by brs17** [comment]
Thank you for your issue report, we are currently tracking this https://github.com/pop-os/beta/issues/98
