### ISSUE TITLE
Super key not showing overview in some languages

### ISSUE THREAD

**Issue by mrbesher** [pop-os/beta#123]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-shell

**Issue/Bug Description:**
Super key not showing the "overview" and launcher shortcut not working in some languages (This is the case for Arabic and Turkish languages)

**Steps to reproduce (if you know):**
1- Change the keyboard layout to Arabic or Turkish.
2- Press the super key and try the default launcher shortcut (super + /)

**Expected behavior:**
super key should show the overview.
super + / should start the launcher (if the shortcut has not been changed)

**Other Notes:**

**Comment by leviport** [comment]
Thank you for the report! We're tracking this bug here: https://github.com/pop-os/beta/issues/98

It looks like the fix was merged upstream, so hopefully we see it soon.
https://gitlab.gnome.org/GNOME/mutter/-/issues/1144
