### ISSUE TITLE
Youtube video playback on full screen broken when "fractional scale" is active (Firefox and X11).

### ISSUE THREAD

**Issue by willbernascimento** [pop-os/beta#125]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

firefox:
  Instalado: 75.0+build3-0ubuntu1
  Candidato: 75.0+build3-0ubuntu1
  Tabela de versão:
 *** 75.0+build3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Youtube video playback is broken when playing the video in full screen (Firefox) when I have "fractional scale" active.

**Steps to reproduce (if you know):**
1. Activate the fractional scale with: $ ``gsettings set org.gnome.mutter experimental-features "['x11-randr-fractional-scaling']"``
2. In the settings application, increase the screen scale to 125%.
3. Play any YouTube video with the Firefox browser in full screen mode.

**Expected behavior:**

The expected behavior is that the video will play normally in full screen mode. The current behavior is of video paused on a still image and reproduction on a smaller part of the screen (The printscreen shows exactly what happens).
![Captura de tela de 2020-05-02 08-37-55](https://user-images.githubusercontent.com/7853382/80864900-2b539800-8c5c-11ea-8748-b6ecff02d06f.png)

**Other Notes:**
This bad behavior occurs both with Intel graphics only and with the active hybrid mode (intel / Nvidia 940MX) on Dell Inspiron 7460 laptop. The HiDPI Deamon has not affect this behaviour. In the Chromium browser the video is slow and has a lot of lag but does not break (crash). When the screen scale is at 100% everything works fine.

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
