### ISSUE TITLE
[20.04] Terminal jumping around when using tiling on double monitors

### ISSUE THREAD

**Issue by MeurillonGuillaume** [pop-os/beta#126]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Upgraded from 19.04.
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
System76 window tiling

**Issue/Bug Description:**
The terminal jumps around on different screens in a multi-screen setup when creating a new terminal (`ctrl+shift+T`)

**Steps to reproduce (if you know):**
Open a terminal on secondary monitor, does not matter if it is tiled or not. Press `CTRL+shift+T` or click new terminal button. The terminal will now jump back to the primary display.

**Expected behavior:**
The terminal windows stays where it was originally placed, since no new windows were created.

**Other Notes:**
Happens when the terminal is the only application that is opened on the secondary display, as well as when it is aside other applications using tiling.

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
