### ISSUE TITLE
Calandar no longer working with Nextcloud online accounts

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#13]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome-calendar 3.36.0

**Issue/Bug Description:**

No longer works after upgrade

![Screenshot from 2020-04-10 12-42-12](https://user-images.githubusercontent.com/40340217/78988500-00789700-7b29-11ea-97be-67a27b4fdba7.png)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**
Tried removing and re-adding account
Server back-end has made no changes.

**Comment by rocinante333** [comment]
I can confirm this is happening as well.  I have pop-os 19.10 connected to a 17.0.5 Snap of Nextcloud working fine.  

On a second machine running 19.10 (wasn't connected to Nextcloud at all yet) I updated to 20.04 and tried to sync Nextcloud for the first time to this system to test this.  Calendar does not sync.

NOTE: I also had some initial problems getting files to sync, but while trying to test and find anything in the log files I ended up changing the IP of my new 20.04 machine and files started syncing.  Calendar still doesn't sync.

**Comment by rocinante333** [comment]
> I can confirm this is happening as well. I have pop-os 19.10 connected to a 17.0.5 Snap of Nextcloud working fine.
> 
> On a second machine running 19.10 (wasn't connected to Nextcloud at all yet) I updated to 20.04 and tried to sync Nextcloud for the first time to this system to test this. Calendar does not sync.
> 
> NOTE: I also had some initial problems getting files to sync, but while trying to test and find anything in the log files I ended up changing the IP of my new 20.04 machine and files started syncing. Calendar still doesn't sync.

May not be specific to 20.04?  Just installed 19.10 on a new laptop and Nextcloud isn't syncing to this either.  Nextcloud is still syncing to previously set up devices, a 19.10 computer and Android phones

**Comment by brs17** [comment]
It looks like there was at least one issue with GNOME 3.36 and nextcloud, as of the recent 3.36.2 release it looks like it should have been resolved: https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/204
