### ISSUE TITLE
After update I lost Nvidia Drivers and I have only one display enabled

### ISSUE THREAD

**Issue by Kublick** [pop-os/beta#134]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Upgrade
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

system76-driver-nvidia

**Issue/Bug Description:**
I lost Nvida drivers and I have display on one monitor, rest are blank.

**Steps to reproduce (if you know):**
upgraded via console
downloaded all the files, updated after the installer completed
then tried to upgrade some packages and I had conflicts with dpkg
resolved with  dpkg --configure -a 
Then did 
apt-get update
apt-get upgrade
requested to restart some services

at the end I got an error like this 

Loading new nvidia-465.24.02 DKMS files...
Building for 5.11.17-051117-generic
Building for architecture x86_64
Building initial module for 5.11.17-051117-generic
ERROR (dkms apport): kernel package linux-headers-5.11.17-051117-generic is not supported
Error! Application of patch disable_fstack-clash-protection_fcf-protection.patch failed.
Check /var/lib/dkms/nvidia/465.24.02/build/ for more information.
dpkg: error processing package nvidia-dkms-465 (--configure):
 installed nvidia-dkms-465 package post-installation script subprocess returned error exit status 6
dpkg: dependency problems prevent configuration of nvidia-dkms-455:
 nvidia-dkms-455 depends on nvidia-dkms-465; however:
  Package nvidia-dkms-465 is not configured yet.

dpkg: error processing package nvidia-dkms-455 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of nvidia-dkms-450:
 nvidia-dkms-450 depends on nvidia-dkms-465; however:
  Package nvidia-dkms-465 is not configured yet.

dpkg: error processing package nvidia-dkms-450 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of nvidia-dkms-460:
 nvidia-dkms-460 depends on nvidia-dkms-465; however:
  Package nvidia-dkms-465 is not configured yet.

dpkg: error processing package nvidia-dkms-460 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.139ubuntu3) ...
update-initramfs: Generating /boot/initrd.img-5.11.17-051117-generic
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 21.04
    Root partition:....../dev/sda4
    Root FS UUID:........5be64f28-60bc-4622-805a-507f86e7689f
    ESP Path:............/boot/efi
    ESP Partition:......./dev/sda3
    ESP Partition #:.....3
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-5.11.17-051117-generic
    Initrd Image Path:.../boot/initrd.img-5.11.17-051117-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     Making entry file for Pop!_OS
Errors were encountered while processing:
 nvidia-dkms-465
 nvidia-dkms-455
 nvidia-dkms-450
 nvidia-dkms-460

**Expected behavior:**
I should have both displays working

**Other Notes:**

**Comment by bflanagin** [comment]
Thanks for the report @Kublick, I wasn't able to replicate the issue. Looking at the error log, you're using a non-stock kernel which is the root of your issue. I would verify all the 5.11.17 kernel packages are installed properly and then try to purge and reinstall the nvidia driver. 

```
sudo apt purge *nvidia*
sudo apt install system76-driver-nvidia

```

**Comment by Kublick** [comment]
reinstalled to current live pop os ; I will retry another day, indeed my kernel was ahead but on my install i didnt had any issues
