### ISSUE TITLE
[21.04] Error when updating OS in Pop!_Shop immediately after fresh install

### ISSUE THREAD

**Issue by nathanbibb** [pop-os/beta#136]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Fresh Install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When installing OS updates in Pop!_Shop immediately after the install, I got the following error:
```
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 system76-driver all 20.04.33~1621030200~21.04~a62678c is not (yet) available (Cannot initiate the connection to ppa.launchpad.net:80 (2001:67c:1560:8008::19). - connect (101: Network is unreachable) Could not connect to ppa.launchpad.net:80 (91.189.95.85), connection timed out [IP: 91.189.95.85 80])
```
This occurred after a restart as well.

However, these commands worked fine:
```
sudo apt update
sudo apt upgrade
```

After that, there was nothing to update in Pop!_Shop

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by bflanagin** [comment]
That is curious, reading the error message it looks like there was some sort of connectivity issue between your machine and our server. Let us know if it becomes a consistent issue or if any other networking issues appear on your end.

**Comment by nathanbibb** [comment]
Not sure if it was due to the 230+ updates needed on the OS (is there a timeout on the Pop!_Shop?), but after resorting to the command line once, updates afterward in Pop!_Shop have been fine.  I don't think there was a connection issue on my end since it apt upgrade worked just fine.  Perhaps just an anomaly.

**Comment by OldmanHades** [comment]
Had a similar issue immediately after install when I tried to do a sudo update it said that there were no servers.  I went to the Pop Shop and after trying to update twice it finally applied all the updates.  Once that was done sudo update worked fine.
