### ISSUE TITLE
NVIDIA kernel problems after fresh install + upgrade

### ISSUE THREAD

**Issue by trevorjamesmartin** [pop-os/beta#137]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 
fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Nvidia ISO

**Issue/Bug Description:**

after a fresh install, upgrading the OS causes NVRM: API mismatch

**Steps to reproduce (if you know):**

install NVIDIA ISO
apt upgrade OS (pop OS store)
before rebooting, check dmesg

**Expected behavior:**
               NVRM: API mismatch: the client has the version 465.24.02, but
               NVRM: this kernel module has the version 460.67.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.

**Other Notes:**
this may render the machine un-bootable,
I re-installed the system using USB image
(nice re-install option btw)

**Comment by bflanagin** [comment]
Thanks for the report @trevorjamesmartin, I can confirm the message, but didn't have any issues rebooting after all the updates were installed. Did you system fail to boot?

**Comment by trevorjamesmartin** [comment]
normally on POST, it will show a string of characters in the top left corner of the monitor
*then my GPU will take over the job of rendering things on the screen. 

*this is where it freezes

GUID partitioning, 
CPU: Intel i7-7700 (8) @ 4.200GHz
GPU: NVIDIA GeForce GTX 1660 Ti

**Comment by trevorjamesmartin** [comment]
tried again (same result); however, instead of re-installing I
- [booted the recovery partition](https://support.system76.com/articles/pop-recovery/)
- took a ^^^ Chroot to my installation
- installed _nvidia-driver-460-server_ with apt
- **rebooted to a working system!**
