### ISSUE TITLE
[21.04] Upgrade fails on system with many non-default repos/packages

### ISSUE THREAD

**Issue by cybik** [pop-os/beta#139]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
From: 20.10
Using: `pop-upgrade release upgrade -f`

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
None specifically

**Issue/Bug Description:**
```jun 01 15:24:41 chibe pop-upgrade[1100]: [INFO ] pop_upgrade src/daemon.rs:301: event processed
jun 01 15:24:42 chibe pop-upgrade[1100]: [INFO ] pop_upgrade src/daemon.rs:507: release upgrade: fetching updated packages for the current release
jun 01 15:24:48 chibe pop-upgrade[1100]: [ERROR] pop_upgrade src/daemon/dbus_helper.rs:29: release upgrade cannot be finalized, because a release upgrade was not performed
```

**Steps to reproduce (if you know):**
  * Have a number of additional apt source repositories
  * Install a few system override packages via `dpkg -i`
    * pipewire from Debian Upstream Unstable
    * nVidia latest drivers (using 18.04 packages)
  * Try upgrading
  * Can't upgrade

**Expected behavior:**
Upgrade to beta.

**Other Notes:**
Admittedly my system has a bit of spice to it. It would be nice to know if this is fixable.

**Comment by jacobgkau** [comment]
> Have a number of additional apt source repositories

Thank you for trying the beta. Can you please specify the exact third-party repositories you've added (and, if possible, the packages you installed from them)? This would really help us recreate the issue so we can make the upgrader handle the situation you're encountering.

The output of these commands in a text file would be helpful as well:
```
cat /etc/apt/sources.list
ls -alh /etc/apt/sources.list.d/
cat /etc/apt/sources.list.d/*
sudo apt update
apt list --installed
```

**Comment by cybik** [comment]
Here's the gist of it: https://gist.github.com/cybik/ab8404a5330001378919c906a5bb2635

It's a NUMBER of things here, up to and including one package yall have been very rude in trying to override upstream (vscode - you're clashing with MS' naming and repo).

**Comment by jacobgkau** [comment]
Thank you! I'll try to replicate this setup.

> one package yall have been very rude in trying to override upstream (vscode - you're clashing with MS' naming and repo).

I want to make sure I'm understanding the concern here correctly. I see this line in your output:

```
code/stable,now 1.56.2-1620838498 amd64 [installé, pouvant être mis à jour vers : 1.56.2-1620838498-pop1~1621122459~20.10~94c1af4]
```

This looks like you have VS Code installed from Microsoft's repo, but apt thinks it's upgradable to the version in our repo. I assume you've held it with `apt-mark hold` or something similar? Is there a reason you haven't pinned Microsoft's repo to tell apt to prefer it? You could do that by creating a file here:

```
sudo nano /etc/apt/preferences.d/code
```

And adding this contents:

```
Package: *
Pin: origin packages.microsoft.com
Pin-Priority: 1005
```

This would be the more correct way to prefer Microsoft's package over ours, as it doesn't keep showing updates available for versions from our repository.

(I'm also curious why you're using Microsoft's package instead of ours, since we're really just pulling in their package and hosting it in a default repository for your convenience, but that's a secondary question.)

In any case, I'm not sure this particular package is the issue-- on my test machine, `pop-upgrade` proceeded despite `code` being held with `apt-mark hold` and `sudo apt update` showing an update available.

**Comment by cybik** [comment]
I wasn't aware of apt-mark hold - and to my point, "upstream" is Microsoft's package and thus your repack should never interfere, technically.

As well:

> (I'm also curious why you're using Microsoft's package instead of ours, since we're really just pulling in their package and hosting it in a default repository for your convenience, but that's a secondary question.)

Literally: you install it in a different location (from what I remember) and the path to the binary changes between your repack and MS's original package - last I checked, anyway. Point being, I prefer getting most tools from the origin rather than a repack (also true for Steam; on advice from VALVe staff, I used their deb and repo instead of the default one and it fixed my VR setup).

I'll try with a hold. Though, to be fair, this issue MIGHT also stem from the last upgrade to 20.10 that didn't "finalize" properly - I had to repair the system myself w.r.t. nVidia packages.

**Comment by jacobgkau** [comment]
I would not recommend trying with a hold if you haven't already done that. If you're not using a hold, how have you been installing updates? Do you reinstall Microsoft's version manually after every `sudo apt upgrade` or Pop!_Shop update?

**Comment by cybik** [comment]
> I would not recommend trying with a hold if you haven't already done that. If you're not using a hold, how have you been installing updates? Do you reinstall Microsoft's version manually after every `sudo apt upgrade` or Pop!_Shop update?

I've just been ignoring your updates manually XD

**Comment by jacobgkau** [comment]
> I've just been ignoring your updates manually

I'm not sure I understand, does this mean you haven't been installing any updates at all? Or do you manually install updates through the Pop!_Shop GUI and make sure not to click `Update` on VS Code specifically?

**Comment by cybik** [comment]
> I'm not sure I understand, does this mean you haven't been installing any updates at all? Or do you manually install updates through the Pop!_Shop GUI and make sure not to click Update on VS Code specifically?

I've been installing updates via synaptic manually :3

Also, even with a hold:

```[ERROR] pop_upgrade src/daemon/dbus_helper.rs:29: release upgrade cannot be finalized, because a release upgrade was not performed```

**Comment by jacobgkau** [comment]
To reiterate, two packages providing the same application having the same name (and not being co-installable) is correct behavior, and the correct way to get the version you prefer on your system would be the pin process that I described. This is true for any system using Debian-style package management.

I will dig further into your package list to try and recreate the failure, although it sounds like a lot of manual configuration has been performed. If you were able to provide step-by-step instructions for causing this from a fresh installation of Pop, that would be what we need (and what I'm looking for on my test machines.)

**Comment by cybik** [comment]
The most boiled-down alterations are:

* `dpkg -i`-ing the latest nVidia-465 packages from 18.04 into 20.10
  * this was done when the 465.24 upgrade broke 20.10. Instead of regressing to 460 I force-installed the 18.04 packages to keep the updated drivers.
* forcing a pipewire setup mostly via https://cybik.github.io/dumbthings/PipeWire202010.html
  * yes I wrote a readme on this!
  * I should update it, been a bit and there's a few little deviations but otherwise mostly that

Anything else isn't an actual deviation, just additional stuff. Though I did make a point of disabling / uninstalling as much of flatpak and snap as possible. Maybe this is why the process is failing?

Also of note: there's no way to flip on additional verbosity in the pop-upgrade daemon, from the looks of it at least. Maybe additional logging could show where this is exploding sideways.

**Comment by jacobgkau** [comment]
> Also of note: there's no way to flip on additional verbosity in the pop-upgrade daemon, from the looks of it at least. Maybe additional logging could show where this is exploding sideways.

If you watch the logs with `sudo journalctl -u pop-upgrade -f` while running the command, is any further information shown? You could also stop the background daemon and run it in the foreground with `sudo systemctl stop pop-upgrade; sudo pop-upgrade daemon`, the output should be the same.

**Comment by cybik** [comment]
> If you watch the logs with `sudo journalctl -u pop-upgrade -f` while running the command, is any further information shown? You could also stop the background daemon and run it in the foreground with `sudo systemctl stop pop-upgrade; sudo pop-upgrade daemon`, the output should be the same.

I did the latter and the logging doesn't say anything of worth. just goes
```
[INFO ] pop_upgrade src/daemon.rs:507: release upgrade: fetching updated packages for the current release
Canceled hold on pop-upgrade.
[INFO ] pop_upgrade src/daemon.rs:301: event processed
[ERROR] pop_upgrade src/daemon/dbus_helper.rs:29: release upgrade cannot be finalized, because a release upgrade was not performed```

**Comment by jacobgkau** [comment]
Could you provide the output of `sudo apt update` like I requested earlier, then `sudo apt upgrade` followed by `sudo apt full-upgrade`? This may undo some of your "manual" installations performed in Synaptic, but that's what `pop-upgrade` is trying to do (a full upgrade), so seeing whether `apt` gets hung up on anything might point us in the right direction. (The only downside is that your system will no longer be in the current state where it's failing, but a timely fix is unlikely until we know the cause.)

**Comment by cybik** [comment]
apt update:
```
326 ko réceptionnés en 5s (59,7 ko/s)                       
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Tous les paquets sont à jour.```

apt upgrade:
```
Lecture des listes de paquets... Fait                                                                         
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Calcul de la mise à jour... Fait
Il semble que l'outil de suppression automatique (« AutoRemover ») ait
supprimé quelque chose, ce qui est inattendu. Veuillez envoyer un
rapport de bogue pour le paquet « apt ».

L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 libnvidia-decode-465 : Dépend: libnvidia-decode-460 mais ne sera pas installé
 libnvidia-encode-465 : Dépend: libnvidia-encode-460 mais ne sera pas installé
 libnvidia-fbc1-465 : Dépend: libnvidia-fbc1-460 mais ne sera pas installé
 libnvidia-gl-465 : Dépend: libnvidia-gl-460 mais ne sera pas installé
 libnvidia-ifr1-465 : Dépend: libnvidia-ifr1-460 mais ne sera pas installé
 nvidia-compute-utils-465 : Dépend: nvidia-compute-utils-460 mais ne sera pas installé
 nvidia-dkms-465 : Dépend: nvidia-dkms-460
 nvidia-driver-465 : Dépend: nvidia-driver-460 mais ne sera pas installé
 nvidia-kernel-common-465 : Dépend: nvidia-kernel-common-460 mais ne sera pas installé
 nvidia-kernel-source-465 : Dépend: nvidia-kernel-source-460 mais ne sera pas installé
 nvidia-utils-465 : Dépend: nvidia-utils-460 mais ne sera pas installé
 xserver-xorg-video-nvidia-465 : Dépend: xserver-xorg-video-nvidia-460 mais ne sera pas installé
E: Erreur interne, l'outil de suppression automatique a cassé quelque chose.
```

Oooooooooh.

Any tip on blocking that driver rollback?

**Comment by cybik** [comment]
Okay so now with a bunch of pins, `apt --dry-run upgrade` gives out a nice 
```
Veuillez utiliser « apt autoremove » pour les supprimer.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 8 non mis à jour.
```

However, full-upgrade is being mean:

```
Les paquets suivants seront ENLEVÉS :
  libnvidia-compute-465:i386 libnvidia-decode-465 libnvidia-decode-465:i386 libnvidia-encode-465 libnvidia-encode-465:i386 libnvidia-extra-465 libnvidia-fbc1-465 libnvidia-gl-465 libnvidia-ifr1-465 nvidia-driver-465
Les NOUVEAUX paquets suivants seront installés :
  libnvidia-common-460 libnvidia-extra-460:i386 libnvidia-fbc1-460:i386 libnvidia-gl-460:i386 libnvidia-ifr1-460:i386
Les paquets suivants seront mis à une VERSION INFÉRIEURE :
  libnvidia-extra-465:i386 libnvidia-fbc1-465:i386 libnvidia-gl-465:i386 libnvidia-ifr1-465:i386
0 mis à jour, 5 nouvellement installés, 4 remis à une version inférieure, 10 à enlever et 1 non mis à jour.
Remv libnvidia-encode-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-decode-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-compute-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv nvidia-driver-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-encode-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-decode-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-extra-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-fbc1-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-ifr1-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Remv libnvidia-gl-465 [465.24.02-1pop0~1620080500~18.04~350b91c]
Inst libnvidia-common-460 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [all])
Inst libnvidia-extra-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c] (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386]) []
Inst libnvidia-extra-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Inst libnvidia-fbc1-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c] (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386]) []
Inst libnvidia-fbc1-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Inst libnvidia-gl-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c] (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386]) []
Inst libnvidia-gl-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Inst libnvidia-ifr1-465:i386 [465.24.02-1pop0~1620080500~18.04~350b91c] (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386]) []
Inst libnvidia-ifr1-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-common-460 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [all])
Conf libnvidia-extra-465:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-extra-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-fbc1-465:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-fbc1-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-gl-465:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-gl-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-ifr1-465:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
Conf libnvidia-ifr1-460:i386 (460.73.01-1pop0~1620243205~20.10~9a91ef9 Pop!_OS PPA:20.10/groovy [i386])
```

There's a reason I'm pinning these drivers, I don't want to yank them argh. Any way to override this behaviour?

**Comment by cybik** [comment]
(Closed this issue because this is becoming a "@cybik broke his stuff" issue)

**Comment by jacobgkau** [comment]
> Any way to override this behaviour?

I'm afraid we can't tell `pop-upgrade` to not upgrade things, its job is to upgrade things. You might be able to create a local repository and pin that to keep the current drivers from being upgraded during the "upgrading current release" phase, but `pop-upgrade` will disable any non-default sources upon upgrading to the new release, so you'd still end up with the released version of the driver and having to reinstall your old version manually. (For what it's worth, 21.04 is using the same driver branch as 18.04 currently is, so it will still be 465.)

Regarding `pop-upgrade` not handling this case automatically, this might need some discussion to determine what a safe and desirable outcome would be (just removing any packages having an issue seems a little dangerous.) I installed the 18.04 465 packages on a test machine, and `apt upgrade` is not giving me the same complaints, which probably has to do with the "non-aligned" packages you mentioned finding on your system.

(Side note, apt pinning should be respected by `full-upgrade` the same as `upgrade`. Since your `upgrade` output shows packages `not upgraded` and your `full-upgrade` is still trying to update them, it sounds like you held them, not pinned them. That is an important difference to understand for e.g. the VS Code issue from earlier.)

**Comment by cybik** [comment]
> (Side note, apt pinning should be respected by full-upgrade the same as upgrade. Since your upgrade output shows packages not upgraded and your full-upgrade is still trying to update them, it sounds like you held them, not pinned them. That is an important difference to understand for e.g. the VS Code issue from earlier.)

That's fair. Pinning/holding is something I literally learned to do today so I'm running on little experience here :P

**Comment by mmstick** [comment]
I'd advise just purging the NVIDIA drivers and getting back to a normal state. Do the upgrade, and 21.04 has 465 so there's no need to manually install packages from another release.

```
sudo apt-get purge '*nvidia*'
```

**Comment by cybik** [comment]
Circling back to say I relented and purged the better driver for a downgrade - and it let the whole upgrade through.

Then I did need to do minor housekeeping such as reinstalling Discord manually, but other than that and recovering rEFInd as my bootloader (because somehow the new pop loader wasn't hitting desktop), I was up and running on 21.04 within 20 minutes of the upgrade finishing (shenanigans needing sorting).
