### ISSUE TITLE
Gnome-keystore not working

### ISSUE THREAD

**Issue by rc-ontruck** [pop-os/beta#14]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade from 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-keyring

**Issue/Bug Description:**

gnome keyring not working do not allow to create default key store. 

**Steps to reproduce (if you know):**

Try to create a default keystore in seahorse

**Expected behavior:**

Been able to create it 

**Other Notes:**

**Comment by brs17** [comment]
Have you tried again recently? There were gnome-keyring issues resolved right before Pop!_OS 20.04 launch that should have resolved this issue as well as many additional improvements with the release of gnome 3.36.2.
