### ISSUE TITLE
[21.04] Dock appears when Terminal is active window during tiling mode

### ISSUE THREAD

**Issue by zamostny** [pop-os/beta#141]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Upgrade, 20.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Terminal (built in Pop terminal)

**Issue/Bug Description:**
When Tiling mode enabled and dock set to auto-hide, the dock appears when Terminal becomes the active window. Dock hides again when any other application is the active window.

**Steps to reproduce (if you know):**
Enable tiling mode
Enable dock auto hide
Open Terminal and another application
Switch between both apps

**Expected behavior:**
Dock would remain hidden unless mouse is near dock

**Other Notes:**

**Comment by jacobgkau** [comment]
Thank you for trying the beta. I'm not quite seeing this happen:

![Screenshot from 2021-06-03 07-18-20](https://user-images.githubusercontent.com/7199422/120651523-1e474080-c43c-11eb-800e-4c0e449f147c.png)
![Screenshot from 2021-06-03 07-18-30](https://user-images.githubusercontent.com/7199422/120651528-1f786d80-c43c-11eb-85a9-226dc1936376.png)

However, I saw the opposite happen-- if a terminal window is active, the dock is hidden, even if the active terminal window isn't near the dock:
![Screenshot from 2021-06-03 07-19-35](https://user-images.githubusercontent.com/7199422/120651536-21423100-c43c-11eb-95ad-d0c1e5789da6.png)
![Screenshot from 2021-06-03 07-19-30](https://user-images.githubusercontent.com/7199422/120651533-20110400-c43c-11eb-9ac1-95ed09814348.png)

It seems the dock treats all terminal windows as one, so _if_ any of the terminal windows are covering the dock, then any of the terminal windows being active hides the dock. If none are covering the dock, then terminal doesn't interfere with the dock:
![Screenshot from 2021-06-03 07-21-29](https://user-images.githubusercontent.com/7199422/120651928-86962200-c43c-11eb-9e5e-92c5e218060d.png)
