### ISSUE TITLE
[21.04] Dock app rearrangement behaves inconsistently

### ISSUE THREAD

**Issue by nourkagha** [pop-os/beta#146]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 
Fresh install.

**Issue/Bug Description:**

Dragging and rearranging apps on the dock does not work correctly. There are certain spots that cannot be dragged into, behaving as 'blocks' of (three?) apps. Demonstration:

![Peek 2021-06-03 20-50](https://user-images.githubusercontent.com/50773468/120690346-c3e6c800-c4ad-11eb-9513-4e4d54d99889.gif)

**Steps to reproduce (if you know):**

N/A

**Expected behavior:**

It must be possible to drag an app in between any other two apps.

**Other Notes:**

N/A

**Comment by bflanagin** [comment]
I see something similar on my machine but only when moving the icon over non-favorited applications (which is the desired result.) Could you verify the version of pop-cosmic you're running and check for updates. you can use `apt policy pop-cosmic` to find out which revision you have installed.

For reference I'm on `0.1.0~1622730049~21.04~7b17096`

**Comment by nourkagha** [comment]
I was on an older version. Fixed after updating to `0.1.0~1622730049~21.04~7b17096` and restarting.

Thanks!

**Comment by jacobgkau** [comment]
https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/issues/9 seems related to this.
