### ISSUE TITLE
[21.04] [Feature] Dock is using intelligent hiding rather than autohiding, setting mislabeled

### ISSUE THREAD

**Issue by RedBearAK** [pop-os/beta#148]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Fresh install 21.04 beta 

**Issue/Bug Description:**

Dock hiding preference is labeled "Automatically Hide Dock", but it is using what most desktops call "Intelligent" hiding, which is hiding only when the focused application overlaps the dock. Autohiding is when the dock automatically hides itself at all times, unless you touch the edge of the screen with the mouse to reveal it. 

Both of these options should exist. Many of us really dislike the "Intelligent" hiding mode and want the dock to just always get out of the way whenever it isn't needed. If I have another unfocused window on the screen where the dock pops up, the dock ends up obscuring part of that background window just because the window that has focus isn't overlapping the dock. The only way to make the dock get out of the way is to give the focus to the window that happens to be overlapping the dock area. This is not always practical. A true autohiding mode, where the dock always hides unless it is being actively revealed by the mouse cursor, is a far superior mode for my desktop usage. 

This is also exactly how the Dock behaves in macOS when you set it to hide itself. It just gets out of the user's way. It doesn't try to keep itself visible just because no window is overlapping itself. 

Every other desktop environment that I've experienced that has the ability to automatically hide a panel (Xfce, Cinnamon, MATE, Plasma, Plank) has always had both "Autohide" and "Intelligently Hide" sorts of options. The shell extensions to hide the GNOME Dash or the Top Bar have options for hiding "always" or "only when the active window is overlapping" (paraphrasing, but you get the idea). 

These choices are extremely important to make the COSMIC desktop truly useful to a wide variety of users.

**Comment by jacobgkau** [comment]
Related: https://github.com/pop-os/beta/issues/140

**Comment by RedBearAK** [comment]
Crossposting a quote from my own comment on issue #140: 

To make this kind of hiding feature work for all users, it needs to have three distinct modes: 

**Automatic** = dock always hides itself unless actively being revealed by mouse

**Intelligent hiding, active window only** = This is the only current hiding mode. Dock hides only when active window overlaps the dock area. 

**Intelligent hiding, all windows** = Dock should hide itself whenever ANY window starts to overlap the dock area, regardless of focus. This is most similar to the actual "automatic" mode, but still leaves the dock visible whenever there isn't a window close enough to the dock area to force it to hide.

**Comment by RedBearAK** [comment]
This was pretty much cleared up in the final release. Closing.
