### ISSUE TITLE
Failed to connect to an apt repository

### ISSUE THREAD

**Issue by Impendeo** [pop-os/beta#15]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

19.10 upgrade

**Issue/Bug Description:**
Failed to connect to an apt repository. You may not be connected to the Internet.
    Try again? y/N

**Steps to reproduce (if you know):**

sudo pop-upgrade release upgrade systemd -f

**Expected behavior:**

To proceed with upgrade

**Other Notes:**

sudo pop-upgrade release update works, can update system normally with apt update/upgrade.

I have 3 network cards in theory
1 is wifi disabled in bios never used
lshw -class network 
2 are ethernet 
I211 Gigabit Network Connection (active, in use)
RTL8125 2.5GbE Controller (not in use, unplugged)
I did try the command with RTL8125 plugged in with same result

**Comment by isms** [comment]
@Impendeo What do the logs say in `journalctl -u pop-upgrade`?

(See [comment](https://github.com/pop-os/beta/issues/54#issuecomment-619424418) for more info on debugging.)

**Comment by Impendeo** [comment]
https://github.com/pop-os/upgrade/issues/98

I believe this is/was the issue.
