### ISSUE TITLE
[21.04] Application menu animation glitches

### ISSUE THREAD

**Issue by smth-0** [pop-os/beta#151]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Update from 20.10 which was updated from 20.04.
 
**Issue/Bug Description:**
When opening applications menu animation is late or missing and results in unpleasant flicker.

**Steps to reproduce (if you know):**
To get late animation, press "show applications" on dash-to-dock dock.
Example:

https://user-images.githubusercontent.com/35414314/120789988-de5a8900-c521-11eb-99c7-7b5287aa16b1.mp4

To get missing animation, press "Applications" button in COSMIC top bar.
Example:

https://user-images.githubusercontent.com/35414314/120790012-e9151e00-c521-11eb-84ca-4c6e91675496.mp4

**Expected behavior:**
Pleasant gnome animation of icons flying out of applications button with no stutters or flickering.

**Other Notes:**
Not transparent background of Applications menu does not look good and would look significantly better with wallpaper background instead of plain grey.

**Comment by jacobgkau** [comment]
Potentially related: https://github.com/pop-os/cosmic/issues/47

**Comment by bflanagin** [comment]
@smth-0 are you using a custom dock to achieve this issue? It doesn't look or behave like the dock that comes with cosmic.

**Comment by smth-0** [comment]
> @smth-0 are you using a custom dock to achieve this issue? It doesn't look or behave like the dock that comes with cosmic.

I use Dash To Dock as described in the OP.  Cosmic built-in dock does not show a "show applications" button for me when I enable it.

**Comment by bflanagin** [comment]
Ah, sorry missed that the first time through. Looks like a duplicate of this issue https://github.com/pop-os/pop/issues/1684

**Comment by smth-0** [comment]
> Ah, sorry missed that the first time through. Looks like a duplicate of this issue [pop-os/pop#1684](https://github.com/pop-os/pop/issues/1684)

Agreed. Though not exactly complete clone. Should I close the issue?

**Comment by bflanagin** [comment]
Yes, lets close this issue to keep the beta list clean. It will still be here if we need to reference it later.

**Comment by smth-0** [comment]
> Yes, lets close this issue to keep the beta list clean. It will still be here if we need to reference it later.

Okay, cool!
