### ISSUE TITLE
Dock briefly reappears after unlock

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/beta#156]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Upgraded from 20.10.

**Issue/Bug Description:**

With the dock disabled, the dock briefly reappears after unlocking. So suspend -> wakeup -> unlock -> dock is there and then hides itself.

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic/issues/41
