### ISSUE TITLE
[21.04] Mediatek 7961 wifi adapter not found with kernel 5.12

### ISSUE THREAD

**Issue by CebulMaciej** [pop-os/beta#159]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I had problem with new laptop with Mediatek 7961 wifii adapter. I have installed popOs and i have changed Kernel to 5.12.x and IT works, but after reboot wifii does not work. My solutions is turn off and turn on the laptop, but i want to have wireless adapter after reboot too :) bug exists in ubuntu 21.04 

**Steps to reproduce (if you know):**
Reboot - wifii does not work. After turn off and then turn on, everything works as expected

**Expected behavior:**
Working wifii after reboot

**Other Notes:**

**Comment by jacobgkau** [comment]
Thank you for trying the beta. Kernel 5.12 is not what we're currently shipping by default. Is the issue present on the default 5.11 kernel?

If this issue is also present in Ubuntu, then this would need to be fixed upstream. No System76 products currently use Mediatek WiFi adapters, so we don't have one for testing/development.

**Comment by CebulMaciej** [comment]
At kernel 5.11 wifii does not work whole time

**Comment by tylergale** [comment]
Did the wifi work on initial install, but only then become problematic once you manually installed a newer non-Pop! OS kernel, or has it always been broken?

**Comment by CebulMaciej** [comment]
On initial install wifi does not work. Only change Kernel to 5.12 makes wifii working, but after reboot wifii does not work. When i rerun device - works as expected

**Comment by YubinToysmyth** [comment]
I'm having the same issue on my laptop ACER NITRO5 (AN515-45).

It seems that Mediatek 7961 [14c3:7961] is actually MT7921K and it is wifi6+BT combo module,
however the weirdest thing is that BT works whether wifi doesn't.
So I think it is an issue of wifi device driver init function, not of frontend one (like device-tree).

It would be nice if there is some driver path offer because I still wanted to use 20.04 version.

Thanks.

**Comment by develm** [comment]
I can confirm that wifi card does not work on Kernel 5.11 but it does work on kernel 5.12.15. I have Acer Nitro 5 (AN517-41 weird east europe version) with Mediatek 7961

**Comment by CebulMaciej** [comment]
Bluetooth does not work for me too. 
But in wifi case... does it work after reboot @develm ?

**Comment by develm** [comment]
> Bluetooth does not work for me too.
> But in wifi case... does it work after reboot @develm ?

I've updated to 5.13.1 and wifi works after reboot I didn't check if it worked before, bluetooth still doesn't work.

**Comment by vigneshgr8** [comment]
I'm running 5.13.8 and WiFi works but bluetooth does not. I guess it is an incompatibility issue with MT7921 and MT7961.
All I can do is wait for the firmware of 7961 to come to the Linux Kernel.

**Comment by kasunbdn** [comment]
I had the same problem when running 5.11 and then I updated to 5.14.1
both WiFi and Bluetooth are working fine now

**Comment by YoungGarbage** [comment]
@CebulMaciej , hi! I'm new to Pop OS and got the same problem as you, can you guide me or give me a link to update to the 5.12 kernel? Thank you in advance

**Comment by CebulMaciej** [comment]
Just start application with mamę "mainline" and choose version which you want. Few hours ago i installed 5.14.1 version and everything works

**Comment by YoungGarbage** [comment]
@CebulMaciej , Thanks for the help man, been having this problem for 2 months now, bless you bro

**Comment by pkumarg** [comment]
Situations same for Kernel Version 5.13. Just now installed Ubuntu 21.10 which is offering 5.13 latest, by usual updates. And wifi not working.
Didn't try Bluetooth.

**Comment by SleepyPepperHead** [comment]
https://www.reddit.com/r/Amd/comments/n90uv3/comment/hme51wh/?utm_source=share&utm_medium=web2x&context=3

Just for the record, Linux kernel's driver module `mt7921e` does work with this card. I'm on `5.15.2`.

But, for now it seems that this module currently doesn't include a match for this card's id until this patch hit: https://patchwork.kernel.org/project/linux-wireless/patch/84ab45bf42f57fd0301c156ffc11d0fe330ff1f8.1636857817.git.deren.wu@mediatek.com/

So, currently I used a `modprobe` rule and a `udev` rule to automatically load the module and use it for the card.

```
cat /etc/modprobe.d/rz608.conf
alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e

cat /etc/udev/rules.d/99-rz608.rules
SUBSYSTEM=="drivers", DEVPATH=="/bus/pci/drivers/mt7921e", ATTR{new_id}="14c3 0608"
```
