### ISSUE TITLE
[21.04] Doubled/phanthom desktop icons

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/beta#164]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Upgrade from Pop!OS 20.10

**Issue/Bug Description:**

![image](https://user-images.githubusercontent.com/63356574/121206157-86e94f80-c878-11eb-9298-11552b6ec398.png)

![image](https://user-images.githubusercontent.com/63356574/121206241-98caf280-c878-11eb-8255-631fd166ee18.png)
Desktop icons leave a phantom icon behind them that cannot be clicked. The phantom icon disappears after the file is deleted.  ALT+F2 and "r" doesn't solve the problem. When it happened cosmic wasn't on.

**Steps to reproduce (if you know):**

None, it happened right after the upgrade.

**Expected behavior:**

That shouldn't happen.

**Other Notes:**
Extensions
![image](https://user-images.githubusercontent.com/63356574/121207578-b0ef4180-c879-11eb-8dfe-c8f82a799e1a.png)

**Comment by jacobgkau** [comment]
Thank you for trying the beta. Your screenshot shows that you have both the `Desktop icons` and `Desktop icons ng (ding)` extensions installed. DING is the extension that we currently ship by default; you should disable one of the two.

Related: https://github.com/pop-os/upgrade/issues/166

**Comment by Kartonrealista** [comment]
Thank you.
