### ISSUE TITLE
[21.04] Lutris icon does not show in applications overview

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [pop-os/beta#170]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

Fresh install 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Lutris
```
lutris:
  Installed: 0.5.8.3-1
  Candidate: 0.5.8.3-1
  Version table:
 *** 0.5.8.3-1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/multiverse amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu hirsute/multiverse i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Three things happen...
1) The icon does not appear in the applications overview
2) In the Pop store, there is no open button.
3) It is not searchable in the launcher.

**Steps to reproduce (if you know):**
Install lutris (cli or store)

**Expected behavior:**
See an icon in the applications overview and the ability to run it via the launcher.

**Comment by bflanagin** [comment]
Curious, I did an upgrade from 20.10 to 21.04 and the only issue I see from the list of issues is the Pop_Shop not having an open button. Will do a fresh install and report back.

**Comment by fcwoknhenuxdfiyv** [comment]
Yes, very strange...

The .desktop file is in ```/u/s/applications``` and I can ```gtk-launch net.lutris.Lutris```

**Comment by fcwoknhenuxdfiyv** [comment]
I just looked at the application overview, and it's there now!
