### ISSUE TITLE
Can't login to profile

### ISSUE THREAD

**Issue by ouroboroscoding** [pop-os/beta#171]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 
Insalled 20.10 fresh on Saturday. Then ran the following Monday in order to get 21.04 without even realising it was beta/alpha/whatever

sudo apt update && sudo apt dist-upgrade
sudo pop-upgrade release upgrade -f

Basically I just realised I couldn't install MySQL Workbench as it only had repos for 20.04 or 21.04, no 20.10 so I looked up how to upgrade PopOS and it worked.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Not sure what package is causing the issue.

**Issue/Bug Description:**

Twice now, in the span of two days, I have tried to log into the PopOS and just get the "Oh No!' screen with nothing but the option to log out.

The first time the system appeared to be working, but my devices (keyboard/mouse) wouldn't respond so I had to hard shutdown, when it booted back up, I had the message and couldn't get back into my account. I had to log in using the terminal, delete ".config" and then I was able to get in again.

The second time, no crash, I simply logged out of my profile, and when I logged back in, same problem, no access. Only this time rather than delete ".config", I went folder by folder and tried to figure out what exactly was the issue. Turns out it was ".config/dconf/user". Deleting or renaming the file allows me back into my profile.

**Steps to reproduce (if you know):**

Not sure I can reproduce the problem. So far I am unsure why it's happened. The only thing I do remember is the first time I was trying to access a virtual box instance that was running when it locked up, or appeared to lock up. And the second time, when I logged out, I had forgotten to shut down the VB instance and so it was trying to suspend when it logged out. Don't know if it's a coincidence or not, but it's the only thing I can connect both issues to.

**Expected behavior:**

See above

**Other Notes:**
[user.txt](https://github.com/pop-os/beta/files/6627476/user.txt)

please note, I renamed the file from "user" to "user.txt" only because it wouldn't let me attach as just "user"

**Comment by jmbuhr** [comment]
Did you by any chance also change the Multi-Monitors Add-On settings? See https://github.com/pop-os/beta/issues/172

**Comment by duplexsystem** [comment]
I had the same issue before the beta(force installed 21.04) when I disabled dock2dash

**Comment by Kartonrealista** [comment]
#173
