### ISSUE TITLE
constant "new" Printer notification

### ISSUE THREAD

**Issue by Impendeo** [pop-os/beta#18]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

19.10 >  Upgrade

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

GUI (gnome) keeps notifying user of local printer which is installed.

**Steps to reproduce (if you know):**

**Expected behavior:**

Notify once upon first detection only.

**Other Notes:**

**Comment by mikemadden42** [comment]
@Impendeo I have this same issue on the pop-os 20.04 beta and ubuntu 20.04 beta.  I have not found a fix for it yet.

**Comment by mikemadden42** [comment]
I wonder if this is the same issue?
https://github.com/pop-os/iso/issues/178

**Comment by WatchMkr** [comment]
Thanks for the report. We're tracking this one here https://github.com/pop-os/pop/issues/891. The behavior changed in GNOME 3.36.
