### ISSUE TITLE
Unable to Upgrade From Pop!_OS 20.1

### ISSUE THREAD

**Issue by BelArvardan** [pop-os/beta#184]
**Issue/Bug Description:**

Running command to upgrade returns error 

![pic1](https://user-images.githubusercontent.com/19807636/122658694-f2170980-d135-11eb-9618-3c6f5b3dd175.png)

![pic3](https://user-images.githubusercontent.com/19807636/122658725-373b3b80-d136-11eb-8b85-5c9605bf172b.png)

**Steps to reproduce (if you know):**

Run `sudo pop-upgrade release upgrade -f` in terminal or run update recovery from settings.

**Expected behavior:**

Upgrade system or upgrade recovery

**Other Notes:**

Could be caused by any of the following:
- Custom kernel (Liquorix or XanMod)
- I use Refind Bootloader
- BTRFS File System
- Pipewire

![pic2](https://user-images.githubusercontent.com/19807636/122658709-1672e600-d136-11eb-866a-442978d6b062.png)

**Comment by bflanagin** [comment]
Given all the modifications it could be a number of things. Could you provide us with your /var/log/upgrade.log file and make sure that you can run `sudo apt update && sudo apt upgrade` without fail.

**Comment by BelArvardan** [comment]
I ran `sudo apt update && sudo apt upgrade`. No issues there. 

I do not have a /var/log/upgrade.log file. 


Look I am not a developer I am a layman so take this with a grain of salt. I read a [post on Reddit](https://www.reddit.com/r/pop_os/comments/jgqsb0/failed_to_apply_system_repair_before_upgrade/) about others have similar issues while upgrading previous versions of Pop!_OS. They were able to correct the issue by commenting out entries in /etc/fstab. In one case it was the recovery partition in another case it was custom entries. This tip didn't fix my problem. However it is interesting that I am also unable to upgrade my recovery partition and get the same error message in the gui.

My concern is that the issue is related to /etc/fstab and btrfs entries.

Another thing I noticed after running `sudo journalctl -u pop-upgrade` was the line 

"pop_upgrade src/release_api.rs:55: checking for build 20.10 in channel nvidia"

I do not use any nvidia drivers on my device. So I'm not sure why it's using "channel nvidia"

Attached below is a txt file with the full output of `sudo journalctl -u pop-upgrade`.
[journalctl_u_pop-upgrade.txt](https://github.com/pop-os/beta/files/6688400/journalctl_u_pop-upgrade.txt)

Hopefully I have given you something you can use. Please let me know if there are any other logs I can pass along or any other way I can help.

Thanks for your help.

**Comment by jacobgkau** [comment]
I just completed an upgrade on a btrfs install, so btrfs itself does not cause any problems. @BelArvardan Can you please provide the output of the following commands:
```
cat /etc/fstab
cat /etc/crypttab
lsblk
mount
```

**Comment by BelArvardan** [comment]
That's good news about the successful BTRFS upgrade.

The text files below contain the command outputs you requested:

- [fstab.txt](https://github.com/pop-os/beta/files/6696593/fstab.txt)
- [crypttab.txt](https://github.com/pop-os/beta/files/6696600/crypttab.txt)
- [lsblk.txt](https://github.com/pop-os/beta/files/6696602/lsblk.txt)
- [mount.txt](https://github.com/pop-os/beta/files/6696603/mount.txt)

**Comment by jacobgkau** [comment]
You have a single partition (encrypted volume) configured to mount at three different mountpoints in your fstab.

```
UUID=82122405-9268-4b3f-a70b-35ccb8dd97e1 / btrfs defaults,subvol=@,ssd,noatime,space_cache,commit=120,compress=zstd,subvol=@,ssd,noatime,space_cache,commit=120,compress=zstd:1 0 0
UUID=82122405-9268-4b3f-a70b-35ccb8dd97e1 /home btrfs defaults,subvol=@,ssd,noatime,space_cache,commit=120,compress=zstd:1,subvol=@home,ssd,noatime,space_cache,commit=120,compress=zstd 0 0
UUID=82122405-9268-4b3f-a70b-35ccb8dd97e1 /swap btrfs defaults,subvol=@,ssd,noatime,space_cache,commit=120,compress=zstd,subvol=@swap,compress=no 0 0
```

It's actually mounted at four different mountpoints, the three that it's configured for plus an additional Timeshift directory.

```
/dev/mapper/data-root on / type btrfs (rw,noatime,compress=zstd:1,ssd,space_cache,commit=120,subvolid=1868,subvol=/@)
/dev/mapper/data-root on /home type btrfs (rw,noatime,compress=zstd:1,ssd,space_cache,commit=120,subvolid=264,subvol=/@home)
/dev/mapper/data-root on /swap type btrfs (rw,noatime,compress=zstd:1,ssd,space_cache,commit=120,subvolid=540,subvol=/@swap)
/dev/mapper/data-root on /run/timeshift/backup type btrfs (rw,relatime,compress=zstd:1,ssd,space_cache,commit=120,subvolid=5,subvol=/)
```

Going back to just the fstab configuration, I understand that you're using multiple btrfs subvolumes, but you've defined `subvol=@` for all three before the actual `subvol=@home`/`@swap` later in the line. In fact, it looks like most of the options on those three lines are duplicated. Is there a reason for this? (If not, I'd recommend removing the duplicate options so each option appears once per line, then rebooting and trying the upgrade again.)

**Comment by BelArvardan** [comment]
Thanks I will try and fix that. I am pretty new to using btrfs.

**Comment by BelArvardan** [comment]
Alright correcting those entries in fstab fix my problem. I was able to upgrade without any issues. 

I will close the issue.

Thanks for all your help!
