### ISSUE TITLE
Active Hint frame "ghosting" with activated Window Tiling

### ISSUE THREAD

**Issue by zbeeble49** [pop-os/beta#185]
Using a fresh install of 21.04 on
Lenox Thinkpad X1 6th gen (HiDPI display, of course)

With windows tiling switched on and "Show Active hint" enabled, I get ghosting of the active hint colored frame after closing the last open app window on any virtual desktop. I have tried with enabled and disabled both HiDPI daemon settings and had this ghosting effect with any setting.

The active hint frame is not persistent and disappears when I switch virtual desktops. Opening another app or multiple apps shows correct "Active Hint" behavior. So rather a visual glitch / minor annoyance. 
 
Have not recognized this behavior in previous versions of Pop!_OS 20.10 and also not previous iterations of the beta.

![2021-06-22_11-08](https://user-images.githubusercontent.com/36364835/122899603-409df100-d34c-11eb-8f30-0c12e546c2a3.png)

![2021-06-21_14-51_1](https://user-images.githubusercontent.com/36364835/122899576-3976e300-d34c-11eb-9d60-f5772f9da530.png)

**Comment by jacobgkau** [comment]
This may be solved by https://github.com/pop-os/shell/pull/1014, if it's the same issue as https://github.com/pop-os/shell/issues/1013.

**Comment by zbeeble49** [comment]
Thanks. 
Indeed same issue as described in [pop-os/shell#1013](https://github.com/pop-os/shell/issues/1013).
However no have a dual monitor setup, just using my notebook screen.

Have tried and disabled 'multi monitor add-on' to see if that has any impact on the issue, but as expected did not.
