### ISSUE TITLE
[21.04] Graphical glitch while switching from Applications to Workspaces

### ISSUE THREAD

**Issue by Giovix92** [pop-os/beta#188]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Upgrade from 20.10 freshly installed

**Issue/Bug Description:**
Graphical glitch while switching from Applications tab to Workspaces.

**Steps to reproduce (if you know):**
- Open applications tab
- Click "Workspaces" in the top-left border. The graphical glitch will appear, if you have one or more window opened in background.

**Expected behavior:**
No glitches.

**Other Notes:**
Sadly the stock screenshot tool doesn't show the "glitch", since it deletes all the under-area. Example shown in photo. Had to take the screenshot using another tool.

"Empty" screenshot:
![Schermata da 2021-06-24 01-51-37](https://user-images.githubusercontent.com/19226770/123182503-e443ea00-d48f-11eb-8a6a-5c479d8d0a7c.png)

Actual glitch:
![2021-06-24_01-59](https://user-images.githubusercontent.com/19226770/123182568-09385d00-d490-11eb-8264-cab2353eb710.png)

**Comment by Kartonrealista** [comment]
It's a bug with COSMIC
https://github.com/pop-os/cosmic/issues/86

**Comment by Giovix92** [comment]
> It's a bug with COSMIC
> [pop-os/cosmic#86](https://github.com/pop-os/cosmic/issues/86)

Uh okay, nice to see you already reported it! Closing this issue then.
