### ISSUE TITLE
Do Not Disturb is not persistent across boots

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/beta#19]
Regression

**Comment by crawfxrd** [comment]
Do Not Disturb is an integrated feature in GNOME 3.36. In previous releases this functionality is made available through [our extension](https://github.com/pop-os/gnome-shell-extension-do-not-disturb). The extension was not installed on a machine I upgraded to 20.04, and does not work on GNOME 3.36.

**Comment by brs17** [comment]
@crawfxrd this might be an issue then with Do Not Disturb that is integrated in GNOME. If that is the case, we should see if we can fix it, or if there it has already been fixed upstream.

**Comment by crawfxrd** [comment]
- [gnome-control-center#961](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/961)
- https://launchpad.net/bugs/1873692

**Comment by crawfxrd** [comment]
Fixed upstream: [GNOME/gnome-shell!1264](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1264)
