### ISSUE TITLE
Tap To Click Nonfunctional During First-Boot Setup Session

### ISSUE THREAD

**Issue by Schykle** [pop-os/beta#191]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
Fresh install.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
First-run setup session.

**Issue/Bug Description:**
After install, the first boot which sets up the device/user lacks tap-to-click, while this is functional in the live system as well as the installed user's session afterwards.

**Steps to reproduce (if you know):**
Boot live USB, test tap-to-click, install.
Boot installed system, test tap-to-click, it should fail.
Log into new user session, tap-to-click works.

**Expected behavior:**
Tap-to-click functionality present and consistent across all sessions by default.

**Other Notes:**
Pop!_OS 21.04 looks AMAZING, and runs very well on my Surface Laptop Go! You guys rock <3

**Comment by leviport** [comment]
Can you confirm the version of iso you're installing from? This has been known behavior in all releases prior to 21.04, but now 21.04 runs GIS after the user logs in, and tap-to-click should be working after login.

**Comment by Schykle** [comment]
Tap to click does work after logging in, but it doesn't seem to work in the stage before login, where the initial user setup happens. It also seems to be nonfunctional in GDM after further testing. Seems to be 21.04 Intel/AMD ISO. I downloaded it a few days ago via the link provided at the top of the Pop!_OS Mattermost chat.

**Comment by leviport** [comment]
Ah I see. That iso is a bit stale and doesn't have the changes I mentioned. Newer isos won't have that before-login stage, meaning that tap-to-click will work in Gnome Initial Setup as expected.

**Comment by Schykle** [comment]
Thanks for the reply, and sorry for the delay in mine! I've done some fiddling with the official release ISO and I can't seem to replicate the issue! Apologies for reporting against such an old image!

**Comment by leviport** [comment]
No worries, thanks for helping report bugs!
