### ISSUE TITLE
Unable to upgrade "pop-session" package in Pop_Shop! or using apt

### ISSUE THREAD

**Issue by nathanbibb** [pop-os/beta#194]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Pop_Shop! indicates updates are needed, but when trying to install updates, the following message is displayed:
```
Failed to update “Operating System Updates
This may have been caused by external or manually compiled software.
The following packages have unmet dependencies:
  gnome-shell-extension-cosmic-dock: Breaks: gnome-shell-extension-ubuntu-dock but 69ubuntu1pop0~1624393749~21.04~00aed10 is to be installed
```

When running `sudo apt upgrade`, the following message is displayed:
```
The following packages have been kept back:
  pop-session
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Steps to reproduce (if you know):**

**Expected behavior:**
All packages should be upgraded, using either method.

**Other Notes:**

**Comment by leviport** [comment]
This happened because we renamed the dock extension. You can fix it with `sudo apt full-upgrade`.

**Comment by nathanbibb** [comment]
Thanks for the quick response!  Confirmed, issue is gone after `sudo apt full-upgrade`.  This can be closed.
