### ISSUE TITLE
Guake Window doesn't stay on top, but is pulled into tiled layout

### ISSUE THREAD

**Issue by TS-CUBED** [pop-os/beta#195]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 
Upgrade from 20.10.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Guake Terminal

**Issue/Bug Description:**

Since yesterdays update, Guake is no longer behaving as it is supposed to. The drop down terminal is pulled into the tiled layout, rather than rolling down from the top as an overlay window over the tiled ones.

**Steps to reproduce (if you know):**

Start Gnome with Pop-Shell tiling enabled

Start Guake

Open Guake using Hotkey (F12)

**Expected behavior:**

Guake terminal window should stay "attached" to the top bar and lay on top of the tiled windows on the desktop

**Other Notes:**

**Comment by TS-CUBED** [comment]
The drop-down windows behave properly when added to the float exception list.

Need to do that manually since the Guake or DDTerm windows won't show on the windows overview when using the Floating Window Exception GUI.

**Comment by leviport** [comment]
Let's track this issue in https://github.com/pop-os/shell/issues/1034 since it is related to pop-shell
