### ISSUE TITLE
Redshift is sending me a continued  error on Pop!_OS version 21.04 

### ISSUE THREAD

**Issue by rodrigofigueroa** [pop-os/beta#199]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

20.10 to  21.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Redshift

**Issue/Bug Description:**

Pop up an error

**Steps to reproduce (if you know):**

Open it and then it shows the error

**Expected behavior:**

In 20.10 it works perfectly without errors on this application
![Screenshot from 2021-06-30 20-11-22](https://user-images.githubusercontent.com/8458860/124050234-c3bfe680-d9df-11eb-9fc5-ce44f3b0f41f.png)

**Other Notes:**

**Comment by bflanagin** [comment]
In 21.04 we switched the default for location services to off based on various security concerns. I imagine that this got toggled during the upgrade for one reason or another and needs to be re-enabled. If you go to Settings-->Privacy-->Location Service you should be able to see the feature's status and toggle it on. If it shows that its on let us know, but go ahead and turn it off and on again just to be on the safe side. 

After that you may need to reboot your computer or at least your gnome session to reinitialize redshift and geoclue.

**Comment by leviport** [comment]
Another alternative is to use Gnome's built in screen color shifter. You can find those settings in Settings -> Displays -> Night light (button at the top). Since that can be scheduled based on time alone, it doesn't have to rely on location services.

**Comment by rodrigofigueroa** [comment]
Thank you so much with your recommendations, it's better with your recommendations and I have been searching the night mode, but I haven't found until you told me I just found the redshift application but thank you so much from now on I will use the native display night light Thank you so much!!
