### ISSUE TITLE
Glitchy animations when closing animations panel

### ISSUE THREAD

**Issue by eniac314** [pop-os/beta#200]
I just upgraded to 21.04 from 20.10, everything seems to be working fine but I am seeing some flickering on the application icons and on the dock during the transition animations when I am closing the application panel, and when I am opening programs from the application panel.

I am also briefly seeing the desktop icons even though they should be hidden behind the opened apps. (although for some reason it does not seem to be visible in the screen-cast below)

https://user-images.githubusercontent.com/8986418/124100920-2a381980-da5f-11eb-923d-71071ad1810c.mp4

I am using a late 2012 mac mini with an Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz and integrated Intel® HD Graphics 4000 (IVB GT2).

 If I disable gnome animations with this command `gsettings set org.gnome.desktop.interface enable-animations false`, the flickering goes away.  

EDIT: I did not realize this was the beta repo, I pasted this issue to pop_os/cosmic repo.

**Comment by ids1024** [comment]
Closing in favor of https://github.com/pop-os/cosmic/issues/114.
