### ISSUE TITLE
Cosmic Dock not showing

### ISSUE THREAD

**Issue by Steve0929** [pop-os/beta#206]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Upgraded from 21.04 to 21.10 using `sudo pop-upgrade release upgrade -f`
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`Cosmic Dock V. 69`

**Issue/Bug Description:**
Cosmic Dock doesn't appear on screen when set on `Left`, `Bottom `or `Right`. When setting the position on `top` you can see a piece of the dock though.

![image](https://user-images.githubusercontent.com/26073885/137049605-9fd413e4-d7b7-4a22-9939-626d24d4a5de.png)

**Steps to reproduce (if you know):**
`sudo pop-upgrade release upgrade -f`

**Expected behavior:**
Cosmic Dock should be visible

**Comment by Steve0929** [comment]
> Did you have Dash to Dock or similar before? Try disabling some gnome extensions

I had Dash to Panel installed. However even after disabling all the extensions the issue persists.

**Comment by Stevendotcom** [comment]
Dash to dock is no compatible with gnome 41 (yet). You have to enable cosmic dock in settings or install other dock, like Floating Dock.

**Comment by Steve0929** [comment]
Fixed. Cosmic Dock was disabled on settings even though it was enabled on extensions.
