### ISSUE TITLE
Cannot create folders in Application Window

### ISSUE THREAD

**Issue by Serious-Table** [pop-os/beta#207]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Upgrade from 21.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome Application Launcher

**Issue/Bug Description:**
When attempting to group icons, I am unable to create folders by dragging icons on top of each other. 

**Steps to reproduce (if you know):**
1. Click the "Applications" option from the top-left window
2. Drag an application icon on top of another.
3. (Optional) Also attempt to drag an application icon on to an existing folder, such as Utilities

**Expected behavior:**
A new folder or grouping of Applications should form, or an application should be moved into an existing folder.

**Other Notes:**

**Comment by mmstick** [comment]
The App Library that will replace the Applications view is not yet in the beta.

**Comment by jacobgkau** [comment]
The Application Library is now being used in the beta, and it is not affected by this issue (I can create a new folder.)
