### ISSUE TITLE
Cannot select bottom workspace on workspace overview

### ISSUE THREAD

**Issue by twoprimehydroxyl** [pop-os/beta#213]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Upgrade from 21.04 via command line

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Cannot select the empty bottom workspace on the workspaces overview

**Steps to reproduce (if you know):**
Click Workspaces button to bring up overview

**Expected behavior:**
Ability to select empty workspace at the bottom to open a new workspace

**Other Notes:**

**Comment by twoprimehydroxyl** [comment]
I had 3 populated workspaces open. When I opened up an additional workspace, I could no longer click on or scroll through any workspaces, but I could still change workspaces with Ctrl+Super+Up/Down.

I rebooted and it seems to be working at the moment.

**Comment by leviport** [comment]
I think I'm seeing the bug on my install. In the Workspaces view, the only two workspaces I can switch to with a mouse click are the first two. I am, however, still able to scroll through all my workspaces by putting my mouse cursor over the workspace picker and scrolling with my mouse/touchpad.

**Comment by twoprimehydroxyl** [comment]
@leviport I was able to select all the workspaces before running apt-get upgrade about 2 hours ago.

Now I can select the top two workspaces with the mouse, but not the bottom 3 (I have 4 populated workspaces, as in the screenshot). I can scroll through the workspaces with the wheel on my mouse, which was something I wasn't able to do when I first opened the issue.

**Comment by n3m0-22** [comment]
These issues have been addressed and fixed. Please let us know if you are still seeing the problem and we can reopen.
