### ISSUE TITLE
desktop icons pop out of running apps when changing workspaces

### ISSUE THREAD

**Issue by ianhundere** [pop-os/beta#214]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 `sudo pop-upgrade release upgrade -f`
from 21.04

**Issue/Bug Description:**
when you change workspaces, if you have icons on your desktop they'll momentarily pop out until you've changed workspaces.

**Steps to reproduce (if you know):**
- have desktop icons
- change workspaces

**Expected behavior:**
deskstop icons shouldn't bleed through running apps

**Comment by WatchMkr** [comment]
Thank you for your report. Added to the release project to address.

**Comment by jackpot51** [comment]
Do you mean that they disappear while you change workspaces? I believe this is intentional.

**Comment by ianhundere** [comment]
they bleed through applications which, afaik, is not expected behavior. i went back to 21.04 tho, so i can't test this any longer.

**Comment by jackpot51** [comment]
Okay, I am not seeing this anymore after updating the desktop icons extension

**Comment by ianhundere** [comment]
hmm, i updated again since 21.10 was officially released. Desktop Icons NG (DING) is used by default now whereas on 21.04 it was installed manually by the user.

i tried removing the extension and then adding it manually and same behavior.

**Comment by ianhundere** [comment]
can this be reopen?
