### ISSUE TITLE
Iso download fails after 1gb

### ISSUE THREAD

**Issue by IdekTheMaster** [pop-os/beta#216]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**
When I download the iso it just fails after 1gb downloaded.

**Steps to reproduce (if you know):**

**Expected behavior:**

It downloads the full iso and doesn't fail

**Other Notes:**
I use Brave web browser

**Comment by jacobgkau** [comment]
We are not currently seeing iso downloads fail. I'm closing this issue because more information was requested and it has not been provided. If this is still an issue, please leave a comment and we can re-open.
