### ISSUE TITLE
App grid icon too small

### ISSUE THREAD

**Issue by jovanap17** [pop-os/beta#219]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
fresh install
 

**Issue/Bug Description:**
![image](https://user-images.githubusercontent.com/49643347/137182786-c2b33547-a58e-41f3-9111-31277f419577.png)

App grid icon too small

**Steps to reproduce (if you know):**
If turn on Gnome Extensions Vertical Overview. The icon will be small. But, if turn off the Gnome Extensions Vertical Overview, icon will be bigger. But, it will make interface to pure Gnome 40 and switch workspace shortcut didn't work (CTRL+SUPER+UP/DOWN) for change workspace, the shortcut is SUPER+UP/DOWN (default Gnome/Ubuntu)

**Expected behavior:**
Make icon to bigger.

**Other Notes:**
My resolution is 1366x768 (16:9)

**Comment by isantop** [comment]
I believe this is a feature in GNOME 40 that attempts to increase the number of available applications listed in the overview by using 32px versions instead of 48/64px versions.

**Comment by jacobgkau** [comment]
The Applications menu has been replaced with a new Applications Library, which is not affected by this issue.
