### ISSUE TITLE
Weird Resizing Of App Windows

### ISSUE THREAD

**Issue by ankushdas9** [pop-os/beta#22]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install

**Issue/Bug Description:**
The tiling works as expected - however, with Tiling turned off, I noticed a weird resizing issue.

**1st try:** When I want to simply have two different applications divided on two sides of the screen - it automatically shrinks one application window. Here's how it looks:

https://imgur.com/41sdt8Q

**2nd try**: While I had Firefox already active, I tried to launch another application. Usually, the second app (such as slack/File Manager) should just launch on top of that - but it shrinks Firefox and launches the second app on top of that as well.

Here's a screenshot of that: https://imgur.com/xCbe5wb

**Expected behavior:**

On **1st try**, it should just easily split both the app window with 50-50% occupied by each app without resizing one of them.

On **2nd try** the primary active windows (Firefox, in my case) should not be resized when I launch a new app.

**Other Notes:**
It's definitely annoying and needs to be addressed. Everything else seems to be working fine for me - will report if I find anything else.

**Comment by ankushdas9** [comment]
Also to add another case:

When trying to download something on Firefox (full-screen mode) - after the download window pops up, Firefox window automatically resizes like this: https://imgur.com/xAmPfCM

**Comment by KillYourFM** [comment]
I can confirm this exact same behavior but with an in-place upgrade from Pop 19.10 to 20.04.

**Comment by ankushdas9** [comment]
As of now, with the recent updates, I can confirm that I'm getting the expected behavior.

So, I'm gonna close this issue. I will keep an eye if this happens again!

**Comment by ankushdas9** [comment]
As of now, with the recent updates, I can confirm that I'm getting the expected behavior.

So, I'm gonna close this issue. I will keep an eye if this happens again!
