### ISSUE TITLE
Rename Vertical Overview to COSMIC Workspaces

### ISSUE THREAD

**Issue by aliceTheGrinseCatz** [pop-os/beta#220]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
 Refresh installation per Boot stick
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

After updating the Gnome shell extension "Vertical Overview" on the extension website, the customization of the extension for Cosmic are lost and the extension is reset to vanilla. This makes conflicts with Cosmic Dock and the overview isn't shown completely anymore. So, please don't update the extension and wait for the fixing. 

**Steps to reproduce (if you know):**

Go to extension.gnome.org, search "Vertical Overview" and click on the update icon. Just wait for the process is ending and look into the Overview. 

**Expected behavior:**
It's keep the design and the behavior it has before updating it.

**Other Notes:**
I like horizontal Overview. Could you work on an improved horizontal Overview as additional option for the version 22.04 or 22.10, sudo?

**Comment by Crylia** [comment]
I might wanna add that disabling this extension causes the top bar background to turn black and not follow any themes, might be gnome related idk
