### ISSUE TITLE
apt packages kept back

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/beta#221]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**

 Upgrade from 21.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When I run `sudo apt upgrade` after the update I get

```
The following packages have been kept back:
  libnss-systemd libpam-systemd libsystemd0 libudev1 netplan.io systemd
  systemd-sysv systemd-timesyncd udev
```

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jaylittle** [comment]
Not as of yet.  Until the missing i386 packages are added back to the impish repos, we are pretty much SOL here.

**Comment by EysseW** [comment]
> Is there a fix without removing lutris and or steam? I got quite some games i dont want to reinstall.

You could makea backup of the games then uninstall steam. After fixing, you can install steam and you are able to tell steam where the games are located.

**Comment by EysseW** [comment]
Is it possible to donwgrade back to beta version 20.04? I am using steam and lutris on a daily basis and I am fine with waiting for the dependencies coming out until starting to use 20.10

**Comment by jaylittle** [comment]
This fix appears to have resolved the issue on both of my Ryzen machines as well as on the test VM I setup.

Thank you!
