### ISSUE TITLE
Applications Menu blank

### ISSUE THREAD

**Issue by ghost** [pop-os/beta#224]
**How did you upgrade to 21.04? (Fresh install / Upgrade)**
 Upgrade 21.04 to 21.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

When I access the applications menu it's blank, I am able use Launcher and the Search in Applications to find my programs and launch them.

**Steps to reproduce (if you know):**

Super+A or click Applications form the dock.

**Expected behavior:**

To be able to see my applications.

**Other Notes:**

**Comment by GrumpyWookie67** [comment]
Not sure if it's related or not but I also have these packaged held back
The following packages have been kept back:
  libnss-mymachines libnss-systemd libpam-systemd libsystemd0 libsystemd0:i386 libudev1 libudev1:i386 netplan.io systemd systemd-container systemd-sysv
  systemd-timesyncd udev

I've tried the following to get them to install.

apt full-upgrade
apt dist-upgrade
apt install -f
