### ISSUE TITLE
The ISO links are not working

### ISSUE THREAD

**Issue by crbelaus** [pop-os/beta#23]
**Issue/Bug Description:**

When clicking the ISO links in the README file I get an XML error page like this:

```xml
<Error>
    <Code>NoSuchKey</Code>
    <BucketName>pop-iso</BucketName>
    <RequestId>tx00000000000007cf0be3d-005e9421f2-44315b-sfo2a</RequestId>
    <HostId>44315b-sfo2a-sfo</HostId>
</Error>
```

**Steps to reproduce (if you know):**

Simply try to download the ISO files linked in the README. The error happens both for the Intel/AMD and Nvidia files.

**Expected behavior:**

Clicking the ISO links should download the corresponding ISOs.

**Other Notes:**

**Comment by ankushdas9** [comment]
I can still download it now and I had no issues downloading it initially. I'm rocking the beta version right now. Maybe check your browser extensions or something that's conflicting.

**Comment by KillYourFM** [comment]
It looks like the Intel ISO link is broken at the moment.

**Comment by ankushdas9** [comment]
> It looks like the Intel ISO link is broken at the moment.

Weird. I'm able to download both of em just fine.

**Comment by caasi-dev** [comment]
Yes I can't get the ISO link either

```
<Error>
<Code>NoSuchKey</Code>
<BucketName>pop-iso</BucketName>
<RequestId>tx000000000000087f4e041-005e987ca1-443fd0-sfo2a</RequestId>
<HostId>443fd0-sfo2a-sfo</HostId>
</Error>
```

**Comment by LiamDawe** [comment]
NVIDIA iso is fine now, Intel/AMD still seems to not work.

**Comment by ankushdas9** [comment]
Even though the link works fine for me,I think this might help:

https://www.digitalocean.com/community/questions/why-do-i-get-a-a-nosuchkey-response-for-some-files-in-a-folder-on-spaces-sub-domain-url-but-it-works-on-the-origin-url

Try clearing cache/ a different browser / change DNS/ use a VPN.

If none of these solutions work, I guess there's something that needs to be done from the server-end to fix it.

**Comment by caasi-dev** [comment]
OK, it seems that there will be something to do with the cache, however, Private/Incognito tab did not work for me. I use Brave browser and **Private window with Tor** does work and it's downloading successfully.

**Comment by SuperMatt** [comment]
It's nothing to do with browser cache, because I tried to use wget from my digital ocean server based in London.

I am physically in the UK, and I have not been able to download the Intel ISO from any of my UK ISPs (I'm on a work VPN, and also at home).

My guess therefore is that the UK Point of Presence (POP) for the CDN has not received replicated versions of one or more of the ISOs.

I *am* able to download via the Tor browser, which would have me connected to a different POP.

**Comment by TAPCollins** [comment]
Tried downloading (from the UK), got the above error. Same in Incognito and other browsers and machines.

Connected through PIA VPN to US New York, worked fine downloading in Incognito.

**Comment by jeroen7s** [comment]
Same issue, but only for the AMD/Intel ISO, the NVIDIA ISO is working fine.

**Comment by bkdwt** [comment]
Same issue here. 
![Screenshot_20200417-160747_Samsung Internet](https://user-images.githubusercontent.com/51302074/79605099-b01fad00-80c5-11ea-9eaf-1fd94d826a84.jpg)

**Comment by jackpot51** [comment]
We tried clearing the CDN cache, please try again and let us know what country you are in if it does not work

**Comment by TAPCollins** [comment]
Working for me in the UK after clearing cache.

**Comment by caasi-dev** [comment]
works for me to in the UK. Cheers

**Comment by jeroen7s** [comment]
Working here as well now, without requiring the use of a VPN (Belgium)

**Comment by jackpot51** [comment]
Nice, closing for now
