### ISSUE TITLE
Default session/desktop environment changed after upgrade

### ISSUE THREAD

**Issue by SanderBlom** [pop-os/beta#236]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Upgraded from 21.04 with sudo pop-upgrade release upgrade -f

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`sander@t14-sander:~$ apt policy pop-cosmic
pop-cosmic:
  Installed: 0.1.0~1634308107~21.10~ea74293
  Candidate: 0.1.0~1634308107~21.10~ea74293
  Version table:
 *** 0.1.0~1634308107~21.10~ea74293 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
sander@t14-sander:~$ 
`

**Issue/Bug Description:**
After upgrading the desktop where pretty broken. Screenshot: https://imgur.com/a/9izFj3J 
Then I got this error: https://github.com/pop-os/beta/issues/209, and after this fix got merged and I updated, the error went away but the desktop is still broken. 

Both pop cosmic and vertical overview are in a error state in gnome extensions.

**Steps to reproduce (if you know):**
Just did the upgrade. The only modifications I had in 21.04 was Orchis-theme and papirus icon pack. 

**Expected behavior:**

**Comment by jacobgkau** [comment]
Are you using GNOME Flashback or another session intentionally? If not, do you have a gear icon on the login screen (after clicking your name, but before typing your password) that you can use to switch to the `Pop` session?
