### ISSUE TITLE
Command Line Upgrade not working

### ISSUE THREAD

**Issue by zunky44** [pop-os/beta#24]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 sudo pop-upgrade release upgrade systemd -f

**Issue/Bug Description:**

>  sudo pop-upgrade release upgrade systemd -f

 command is giving error 

> pop-upgrade: dbus client error: calling ReleaseCheck method failed

I am using 19.10.
![Screenshot from 2020-04-17 11-41-26](https://user-images.githubusercontent.com/11846539/79536925-e0088980-80a0-11ea-8196-863ca7f1601e.png)

**Other Notes:**

**Comment by Kartonrealista** [comment]
Sudo pop-upgrade daemon 
Run the other command in a second tab
