### ISSUE TITLE
Raspberry PI 4 - Cannot run "youtube-dl" in command line.

### ISSUE THREAD

**Issue by curyjorge98** [pop-os/beta#241]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh Install 21.10 Beta .img
Running from usb ssd.
 

**Issue/Bug Description:**
After installing youtube-dl:

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

sudo chmod a+rx /usr/local/bin/youtube-dl

cannot run youtube-dl - it says python is not installed.

$ youtube-dl 
/usr/bin/env: “python”: file or directory not found

If I try to install python, apt says that essential packages will be removed from system:

pop-default-settings python3-repolib and ubuntu-minimal

You are going to do some potentially catastrophic.

NOTE: I can run it on all releases of Ubuntu.

**Steps to reproduce (if you know):**

see above.

**Expected behavior:**

**Other Notes:**

**Comment by bflanagin** [comment]
I'm getting the same error on  21.04. It looks like python3 (installed by default on 21.04 and up) doesn't create a symlink that point /usr/bin/python to /usr/bin/python3

Workaround:
`sudo ln -s /usr/bin/python3 /usr/bin/python`

That gets youtube-dl to work on both the pi and standard pop_os.
