### ISSUE TITLE
[Feature Request] Let favourites remain in the Applications overview

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/beta#242]
**How did you upgrade to 21.10? (Upgrade)**
Upgraded from Pop!_OS 21.04
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Applications overview, cosmic dock.

**Issue/Bug Description:**
Right now applications set as favourites disappear from the applications overview. I think it's better if they remain or if that becomes a toggle-able setting.

**Comment by Crylia** [comment]
I agree, it was hella confusing for me at first, thought some programs were missing entirely

**Comment by Kartonrealista** [comment]
No longer relevant.
