### ISSUE TITLE
No "Upgrade" button when new device firmware is available, under Firmware in Settings

### ISSUE THREAD

**Issue by juanejot** [pop-os/beta#247]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Upgraded from 21.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Firmware in Settings (behavior just seen in GUI, so unsure of which package is causing it).

**Issue/Bug Description:**
It lists a new Device Firmware, but there is no green "Update" button as I've seen on System76 descriptions of the feature.

**Steps to reproduce (if you know):**
Just go to Firmware in Settings while there's an available device firmware upgrade

**Expected behavior:**
See, be able to click on green "Upgrade" button

**Other Notes:**
Let me know if the device for which the firmware is available, what version it is, is necessary info.

**Comment by 13r0ck** [comment]
Hey @jacobgkau!
The upgrade button should only show if there is an update available. Just to be sure would you mind attaching a screenshot showing the change log?

For example,
![Screenshot from 2021-10-19 08-43-41](https://user-images.githubusercontent.com/58987761/137934084-18950047-65a4-4bd0-9a91-fe8c9dae67a2.png)
)
