### ISSUE TITLE
The bottoms of windows on the workspace above being shown on the current workspace

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/beta#249]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh Install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```bash
gnome-shell-extension-cosmic-workspaces:
  Installed: (none)
  Candidate: 0.1.0~1634660887~21.10~39ed0f4
  Version table:
     0.1.0~1634660887~21.10~39ed0f4 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
```

**Issue/Bug Description:**
![Screenshot from 2021-10-19 12-38-35](https://user-images.githubusercontent.com/58987761/137972793-eef54d61-d5a1-4ec8-9ac6-9a52e08acebe.png)

**Steps to reproduce (if you know):**
Change dock position to bottom.

**Expected behavior:**
Windows from previous workspace shouldn't hang into the current workspace.

**Other Notes:**

**Comment by genebean** [comment]
I noticed this just now while using the live image too

**Comment by jackpot51** [comment]
Is this still an issue?

**Comment by leviport** [comment]
Haven't seen it in a while. Closing for now.
