### ISSUE TITLE
Colors appear under saturated, washed out in 22.04

### ISSUE THREAD

**Issue by ARoomWithAMoose** [pop-os/beta#253]
**How did you upgrade to 21.10? (Fresh install / Upgrade)** Both (multiple attempts to resolve issue). Upgrading from 21.04.

**Issue/Bug Description:**
Colors throughout the system appear under saturated, washed out. Extremely noticeable and distracting to the point of forcing me to reinstall 21.04.
Oddly enough, screenshots taken from 21.04 *also* appear washed out, but the actual display is not.
The only immediate difference I can se in the Nvidia X Server Settings is the "Server Vendor Version," which is 1.20.11 (12011000) on 21.04, and 1.20.13 (12013000) on 21.10.

**Other Notes:**

Nvidia GTX 960
Intel Core i5-3570K (not using integrated graphics)

**Comment by ExtremeCoolDude** [comment]
Same issue here. I'm using the same icc profile on my external monitor and the colors on 21.10 are very different. Reds are more "yellow" and almost looks orange, a blushed human face looks jaundiced.

For comparison the red fish and pacman like object on these pictures :

Previous : https://i.imgur.com/8IKl35N.png (disregard the arrow, picture from google)

Now : https://i.imgur.com/ae4jNS8.png

**Comment by ARoomWithAMoose** [comment]
It appears that this is an issue with Gnome 40:

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4071

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4206

**Comment by SUPERCILEX** [comment]
Wow, this has to be one of the weirdest bugs I've seen in a while. Can confirm that changing the refresh rate from 60 Hz to 29.93 Hz fixes the color issues.

Is there a fix? Or a way to downgrade gnome?

**Comment by spaghetticodez** [comment]
I have same issue after upgrade, whites are washed with red tint basically.

**Comment by jackpot51** [comment]
We may have tracked this down. It appears to be specific to monitors that provide ICC profiles. There is a change in gnome-settings-daemon that made these profiles automatically be used for the entire desktop environment. We are testing to see if reverting that change makes things work as expected.

**Comment by jackpot51** [comment]
Fixed by https://github.com/pop-os/gnome-settings-daemon/pull/12, which will be released soon

**Comment by spaghetticodez** [comment]
I can confirm for me this is fixed, thank you guys!

**Comment by jackpot51** [comment]
Fixed with latest gnome-settings-daemon, will release soon

**Comment by jackpot51** [comment]
Released with https://github.com/pop-os/repo-release/pull/69. When the update to gnome-settings-daemon arrives, please reboot and retest. Comment if it is not fixed after that and I will re-open

**Comment by carlosalves91** [comment]
I have same issue. POP OS 22.04, notebook samsung. Intel 10110U.

OS: Pop!_OS 22.04 LTS x86_64 
Host: 550XCJ/550XCR P12RFH 
Kernel: 5.17.5-76051705-generic 
Uptime: 9 hours, 53 mins 
Packages: 1928 (dpkg) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: GNOME 42.1 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i3-10110U (4) @ 4.100GHz 
GPU: Intel Comet Lake UHD Graphics 
Memory: 3245MiB / 15817MiB
