### ISSUE TITLE
Scaling of apps/font sizes does not work on high-res displays, multi-display setup when using tiling

### ISSUE THREAD

**Issue by TS-CUBED** [pop-os/beta#258]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Upgrade from 20.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

na

**Issue/Bug Description:**

I run a dual display setup:

1920x1080 (17" internal laptop display)
3840x2160 (32" Viewsonic, set as main screen)

After upgrade to 21.10, firefox and other apps scale badly on first launch: [Screenshot](https://www.dropbox.com/s/gwc8oodjrafqq1b/Screenshot%20from%202021-10-24%2022-56-28.png?dl=0)

**Steps to reproduce (if you know):**

- Lauch Pop-Os

- Log in

- Start Firefox

- firefox starts up and has weird scaling

- Problem only occurs when tiling (pop-shell) is active

- Scaling resets to correct scaling when switching to max. size (Super-M) and stays at correct scaling when switching back to tiled mode (Super-M a second time).

EDIT: this also occurs with some other apps and sporadically. Always fixed by scaling to fullscreen and back (Super-M twice).

**Expected behavior:**

firefox starts up with correct scaling

**Other Notes:**

I run the nouveau driver on Nvidia Quadro K4100M

xrandr output has the correct resolutions and display sizes:

``
DP-3 connected primary 3840x2160+1920+0 (normal left inverted right x axis y axis) 698mm x 393mm
   3840x2160     60.00*+  59.97    25.00    24.00    23.98    29.98
....

eDP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080     60.04*+  60.01    59.97    59.96    59.93    40.03 
....
``

EDIT: This also occurs on a fresh install of 21.10 using the NVIDIA drivers (nvidia-driver-418-server). So it seems to be unrelated to the driver.

**Comment by burnsco** [comment]
happens for me when using qbitorrent and elisa so far, also on a 4k monitor + 1080  multi setup.

**Comment by n3m0-22** [comment]
I think this issues has been fixed, but please let us know if you still have a problem and we can reopen.
