### ISSUE TITLE
Touchegg should be updated to the latest release

### ISSUE THREAD

**Issue by jawadalkassim** [pop-os/beta#263]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Upgrade

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
touchegg:
  Installed: 202110210919-stable-2.0.12~ubuntu21.10.1
  Candidate: 202110210919-stable-2.0.12~ubuntu21.10.1
  Version table:
 *** 202110210919-stable-2.0.12~ubuntu21.10.1 1500
        500 http://ppa.launchpad.net/touchegg/stable/ubuntu impish/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.9pop0~1619541270~21.10~2c84d77 1500
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
     1.1.1-0ubuntu4 1500
        500 http://us.archive.ubuntu.com/ubuntu impish/universe amd64 Packages
```

**Issue/Bug Description:**

When using Gnome Session X11 without any of Cosmic Extensions and trying to use default gnome 40 Touchegg gestures it's very slow and not smooth at all, 
the problem with touchegg that pop os shipping in their PPA.
Touchegg developer explained the issue here:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/14#issuecomment-945449574

it's a bug related to ```libinput```
**Steps to reproduce (if you know):**

Disable All Cosmic Extension and start Gnome Session 
and installing 
https://extensions.gnome.org/extension/4033/x11-gestures/
**Expected behavior:**
Smooth X11 gestures with touchegg

**Other Notes:**
the fix is enabling touchegg PPA and force installing it from the PPA than Pop os package.

**Comment by jackpot51** [comment]
This is done now
