### ISSUE TITLE
Cosmic Dock unminimizes instead of showing previews when clicking on a group

### ISSUE THREAD

**Issue by ghost** [pop-os/beta#264]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Upgrade

**Issue/Bug Description:**

Behaviour of Cosmic Dock is not the same as it was in 21.04. When I select the _Focus, minimize or show previews_ option, when clicked on a group of opened windows, dock will first maximize one of them and then it will show previews. 

**Steps to reproduce (if you know):**

Through the extensions set up the aformentioned behaviour. 

**Expected behavior:**

Show previews before maximizing.

**Other Notes:**

**Comment by jacobgkau** [comment]
The advanced extension settings are now redirecting to Settings correctly, but the other issues remain (the click action option is missing and only minimization is currently working.)

**Comment by jacobgkau** [comment]
I've got them showing up with the gsetting again in https://github.com/pop-os/cosmic-dock/pull/84, some styling is still off at the moment.

**Comment by jacobgkau** [comment]
This was partially fixed by https://github.com/pop-os/desktop-widget/pull/72 and the remaining portion will be fixed by https://github.com/pop-os/desktop-widget/pull/72.
