### ISSUE TITLE
Dependency issues are keeping back triggers for libglib2.0-0:i386

### ISSUE THREAD

**Issue by KitsuneAlex** [pop-os/beta#265]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 I upgraded from my existing 21.04 installation of Pop!
Also, excuse any weirdness with my CLI snippets, i translate them from german for y'all as good as i can, even if you probably know 99% of them pretty well.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
libglib2.0-0:
  Installed: 2.68.4-1ubuntu1
  Candidate: 2.68.4-1ubuntu1
  Version Table:
 *** 2.68.4-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
I tried running ```sudo apt update && sudo apt upgrade``` like usual, but i am not able to complete the latter because of some weird dependency issue with libglib2.0-0:i386.

I also tried using the recommended fix for kept-back apt-packages as described in #221 which results in exactly the same output.

It's telling me about libglib2.0-0 depending on libmount1 and the latter not being configured, hence the premature exit of the apt process when trying to perform the upgrade.

**Steps to reproduce (if you know):**
I don't know how to reproduce this sadly, since my system is packed full of software and libraries especially.

**Expected behavior:**
The expected behaviour would be the upgrade completing successfully, since i am currently unable to do anything with the package manager.

**Other Notes:**

**Comment by brandonblock** [comment]
Ran into this as well. For me, running `dpkg --configure -a` solved the dependency issues.

**Comment by KitsuneAlex** [comment]
Okay let's not tell anyone about thise, i am stoopid. Thanks for the help, appreciate it <3
