### ISSUE TITLE
pop-shop updates not showing

### ISSUE THREAD

**Issue by kp2401075** [pop-os/beta#269]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

Fresh Install 

I could not find an issue open regarding this, If there is an issue already open regarding this please disregard this and sorry for inconvenience. 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-shop:
  Installed: 3.4.2pop0~1634231591~21.10~ee0f962
  Candidate: 3.4.2pop0~1634231591~21.10~ee0f962
  Version table:
 *** 3.4.2pop0~1634231591~21.10~ee0f962 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Updates not showing up in pop-shop**

**Steps to reproduce (if you know):**
1. open pop-shop
2. wait for it to load 
3. switch to installed tab

**Expected behavior:**
upgrades of deb packages showing in installed tab of pop-shop

**Other Notes:**
Updates showing when doing `apt update` but not on pop-shop
![image](https://user-images.githubusercontent.com/20717654/139559294-f9022e67-2f00-4056-a207-c1db81c599c5.png)

**Comment by kp2401075** [comment]
This may be because of pop-session being kept back as well. Now I'm confused.

![image](https://user-images.githubusercontent.com/20717654/139559393-c2e5b425-d368-4403-98e0-c857fccf424b.png)

**Comment by x2ws** [comment]
I also have the same issue. Upgraded from 21.04 on a Dell XPS 15.

**Comment by jacobgkau** [comment]
> This may be because of pop-session being kept back as well. Now I'm confused. If somebody can confirm that this is due to pop-shop being kept back.

Does running `sudo apt update` and then `sudo apt full-upgrade` work to make `pop-session` no longer held back? Package names are sometimes changed during the beta period, and `full-upgrade` needs to be used to get past those.

**Comment by x2ws** [comment]
> > This may be because of pop-session being kept back as well. Now I'm confused. If somebody can confirm that this is due to pop-shop being kept back.
> 
> Does running `sudo apt update` and then `sudo apt full-upgrade` work to make `pop-session` no longer held back? Package names are sometimes changed during the beta period, and `full-upgrade` needs to be used to get past those.

I ran the `full-upgrade` command and it updated the pop-session package, however, I still don't see any updates in PopShop. I can only see updates when running the terminal command.
![Screenshot from 2021-11-01 15-41-27](https://user-images.githubusercontent.com/5016182/139731472-831d3729-cc66-4c22-b24b-72711537f572.png)
.

**Comment by kp2401075** [comment]
`sudo apt full-upgrade` work to upgrade `pop-session`, now will need to wait for more updates. to check whether updates show up in pop-shop or not.

**Comment by kp2401075** [comment]
still same issue.

updates are not showing in pop-shop


![image](https://user-images.githubusercontent.com/20717654/139970794-8646350f-0b14-4998-9109-c45755a96e74.png)

**Comment by goldyfruit** [comment]
I have the same behaviour.

**Comment by lhotari** [comment]
I also have the same issue.

**Comment by lhotari** [comment]
No updates for apt or flatpak show up for me either.

In `journalctl -o cat /usr/bin/io.elementary.appcenter` output I can see these log messages:
```
app_center_core_package_kit_backend_get_updates: assertion 'cancellable != NULL' failed
libostree pull from 'flathub' for appstream2/x86_64 complete
security: GPG: summary+commit 
security: SIGN: disabled http: TLS
non-delta: meta: 4 content: 1
transfer: secs: 0 size: 4,3 MB
user: Pulled appstream2/x86_64 from flathub
```

**Comment by lhotari** [comment]
I wonder if the log entry `app_center_core_package_kit_backend_get_updates: assertion 'cancellable != NULL' failed` can be related to the problem that updates don't show up?

**Comment by goldyfruit** [comment]
I got this in the logs:
```
failed to set proxy: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
PackageKitBackend.vala:187: Unable to set proxy for PackageKit to use: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
app_center_core_package_kit_backend_get_updates: assertion 'cancellable != NULL' failed
failed to set proxy: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
PackageKitBackend.vala:187: Unable to set proxy for PackageKit to use: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
app_center_core_package_kit_backend_get_updates: assertion 'cancellable != NULL' failed
```

**Comment by goldyfruit** [comment]
Updates are back \o/
