### ISSUE TITLE
Keyboardshortcuts can not be changed

### ISSUE THREAD

**Issue by felix-ulonska** [pop-os/beta#27]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

upgrade from 19.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Tilling Window Manager

**Issue/Bug Description:**
I can not change the keyboard shortcuts.
In an effort to fix the problem: I reseted the keyboard shortcuts in gsettings and then I wanted to rebuild the keyboard shortcuts but in the pop-os shell folder in extensions is not the rebuild.sh.

**Steps to reproduce (if you know):**

**Expected behavior:**
Keyboard shortcuts are in GSettings

**Other Notes:**

**Comment by Jabbbi** [comment]
I cloned the [Pop-OS-Sehll-repo](https://github.com/pop-os/shell#installation) and ran the rebuild.sh from that. It seems to have fixed the issue. Probally the rebuild.sh is not executed when upgrading from 19.10.

**Comment by defecador** [comment]
Yes, I also found it very annoying, specially when in EU keyboards, the / needs to be activated with shift + 7. that means that for activating the tiling, we would need to do super + shift + 7 and they are far away and very unpractical.
