### ISSUE TITLE
Razer Blade laptops not able to suspend/resume with kernel 5.15

### ISSUE THREAD

**Issue by Banjalucan** [pop-os/beta#274]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install from 21.10 ISO 

**Issue/Bug Description:**
After update to kernel 5.15 my machine is not able to wake up after suspend. The "sleep" LED is glowing like usual, but nothing happens after opening the lid and/or pressing some buttons.

**Steps to reproduce (if you know):**
Close the lid or manually put the computer to suspend.

**Expected behavior:**
Correct wake up like before the update to kernel 5.15.

**Other Notes:**
Laptop Type: Razer Blade Stealth 13 (Late 2020)
Kernel: 5.15.0-76051500-generic
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: NVIDIA GeForce GTX 1650 Ti Mobile

**Comment by michaeldauria** [comment]
I have the same issue with a Macbook Pro Retina 12,1. If you need help debugging, please let me know what steps to take and I will be happy to provide the data.

**Comment by michaeldauria** [comment]
I have been upgrading the kernel and I am happy to report this is no longer a problem for me

**Comment by jackpot51** [comment]
I believe 5.15.4 fixed a number of regressions. @Banjalucan do you see the same issue after upgrades?

**Comment by vakenbolt** [comment]
@michaeldauria  @jackpot51  Thanks for providing that feedback I had the same issue with wake from suspend. I noticed 5.15.5 is available for download from the Pop! Shop. I will perform the upgrade and report any findings here. Cheers!

**Comment by vakenbolt** [comment]
@michaeldauria @jackpot51 No dice :disappointed: Upgrading to `5.15.5` still has the broken behavior. When I try to suspend, only the monitor is able to do so but the rest of the machine stays awake at which point I am unable to continue using it unless I do a hard power cycle. 

My Specs:
```
Pop!_OS 21.04 x86_64

**Comment by Banjalucan** [comment]
> I believe 5.15.4 fixed a number of regressions. @Banjalucan do you see the same issue after upgrades?

Sorry for the late reply. On my machine everything is working as expected with the currently released version.

**Comment by vakenbolt** [comment]
@leviport @jackpot51   Upgraded to Kernel 5.15.15 with Pop!_OS 21.10 and suspend and resume works flawlessly!
