### ISSUE TITLE
5.15 kernel breaks network (ASUS XG-C100C)

### ISSUE THREAD

**Issue by pds2208** [pop-os/beta#275]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Beta to kernel 5.15
 
**Issue/Bug Description:**

Update to 5.15 has completely borked my system. No network and even dmesg is hanging.

**Comment by jacobgkau** [comment]
What network interface is in your computer?

**Comment by pds2208** [comment]
A few:

1 x Aquantia Corp. AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] (rev 02)
2 x Intel Corporation I211 Gigabit Network Connection (rev 03)
1 x Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller
2 x Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)

Of those only the Aquantia 10G and one of the RTL8111/8168/8411  adapters are plugged in. All working perfectly on the previous beta.

**Comment by Lautauro** [comment]
same issue

**Comment by pds2208** [comment]
Guessing it's the Aquantia 10G driver:

https://bugs.launchpad.net/ubuntu/+source/linux-hwe-edge/+bug/1768904

Apparently fixed in kernel release 4.15.0-51-generic. Would be great if PopOS can be updated

**Comment by pds2208** [comment]
Can confirm it's the 10G card, which is an ASUS XG-C100C. I remove it and the system comes up as normal. I install it and the network does not come up and the system essentially hangs.

**Comment by jackpot51** [comment]
This bug was reported upstream at https://bugzilla.kernel.org/show_bug.cgi?id=214619, and I contacted the kernel driver maintainer about it.

**Comment by leviport** [comment]
@pds2208 It seems 5.15.4 has fixed this issue on the machine I was seeing it happen on. Would you be able to verify on your hardware?

**Comment by pds2208** [comment]
@leviport Thanks. I can confirm it's working on my machine

**Comment by leviport** [comment]
Excellent, thanks for verifying!
