### ISSUE TITLE
Issues with Cosmic Dock (application shuffling)

### ISSUE THREAD

**Issue by SanderBlom** [pop-os/beta#284]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

Upgrade form 21.04.
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`
sander@t14-sander:~$ apt policy $PACKAGE gnome-shell-extension-cosmic-dock
gnome-shell-extension-cosmic-dock:
  Installed: 70~ubuntu1pop0~1635889396~21.10~acb33c1
  Candidate: 70~ubuntu1pop0~1635889396~21.10~acb33c1
  Version table:
 *** 70~ubuntu1pop0~1635889396~21.10~acb33c1 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
sander@t14-sander:~$ 

`

**Issue/Bug Description:**

Before upgrading, when pressing an icon on the dock it would shuffle the windows if it was multiple instances of the same application. 
Now it only open and closes the same window. 

**Steps to reproduce (if you know):**

So if I have two instances of chromium, one with YouTube and the other with GitHub. If I press the chromium icon on the dock, it would automatically switch back and forth between YouTube and GitHub for each click before upgrading. After the upgrade the behavior changed.

Video: https://youtu.be/Nn7cHMpniCQ

**Expected behavior:**

I expect the windows to shuffle instead of opening and closing only one of the windows. 

**Other Notes:**
If this has been changed on purpose, is there any way to change it trough settings or editing a config file?

**Comment by jabbermacy** [comment]
good catch, same behavior here, on wayland if it matters

**Comment by jacobgkau** [comment]
Thank you for the report. I'm seeing this as well. This seems like it's probably the same issue as https://github.com/pop-os/beta/issues/264.

**Comment by jacobgkau** [comment]
This was solved by https://github.com/pop-os/cosmic-dock/pull/84 and https://github.com/pop-os/desktop-widget/pull/72.
