### ISSUE TITLE
On wake from suspend: Lemur Pro lemp9 fans are at maximum and not slowing down

### ISSUE THREAD

**Issue by mcnamarabryan** [pop-os/beta#291]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Fresh install.

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

None.

**Issue/Bug Description:**
Fans are running at full speed. System use is minimal, no process is showing as using CPU. CPU temps are normal (pasted below).

`coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +32.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +31.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +32.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +30.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +32.0°C  (high = +100.0°C, crit = +100.0°C)

nvme-pci-0200
Adapter: PCI adapter
Composite:    +24.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

system76_acpi-acpi-0
Adapter: ACPI interface
CPU fan:     7309 RPM
CPU temp:    +100.0°C  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +28.0°C  

pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +31.0°C  

nvme-pci-0300
Adapter: PCI adapter
Composite:    +23.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:           8.20 V  
curr1:       672.00 mA 
`

**Steps to reproduce (if you know):**
Allow computer to suspend from screen blank followed by auto-suspend.

**Expected behavior:**
Fans run at a speed according to temperatures.

**Other Notes:**

**Comment by leviport** [comment]
Is this a lemp9 or a lemp10? Does toggling the fan speed with `Fn`+`1` make any difference? 

Also, it seems hard to believe 21.10 would be responsible for something like this. Any chance you were previously running an older version of Pop, and did it happen on that version?

**Comment by mcnamarabryan** [comment]
lemp9. I'll keep the shortcut in mind to try if the issue persists.

One note that rebooting did not resolve it. At login I used the power button to enter and exit suspend, the fans running the whole time, and upon resuming the fans followed a curve to a nominal speed.

On 20.04 there were times when the laptop would be suspended and plugged in, and I would notice that the fans were running full bore for some reason. I'm not certain if they are the same issue, and whether 21.10 is responsible, but I wanted to log the problem since I'm running 21.10.

**Comment by leviport** [comment]
Very strange. Thanks for the info though. I'll make a note to investigate with one of our lemp9's when I get a chance.

**Comment by mcnamarabryan** [comment]
Closing to archive, no specific 21.10 issue identified.
