### ISSUE TITLE
Error installing flatpaks on fresh install 21.10

### ISSUE THREAD

**Issue by andirsun** [pop-os/beta#292]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Fresh install last iso V2
 https://github.com/pop-os/shop/issues/299

**Issue/Bug Description:**
![Screenshot from 2021-11-11 10-44-17](https://user-images.githubusercontent.com/22928302/141326824-8bd4e611-3871-426c-ac6c-826c653ea360.png)

```
Aborted due to failure (While trying to checkout 16d161d8a71701b80fa4bca12812a22c19dc0641b3571fe88c517c84da94c5b5 into /home/andirsun/.local/share/flatpak/runtime/org.freedesktop.Platform/x86_64/21.08/.16d161d8a71701b80fa4bca12812a22c19dc0641b3571fe88c517c84da94c5b5-VAFDC1: Opening content object 18dafc4a2f83276e75db2f1c3e7069675ca5e49cd937512a966693e819e00748: Couldn't find file object '18dafc4a2f83276e75db2f1c3e7069675ca5e49cd937512a966693e819e00748')
```

**Steps to reproduce (if you know):**
Try to install any flatpak app.

**Expected behavior:**

**Other Notes:**

**Comment by jabbermacy** [comment]
did you apt update as soon as you installed?  I just checked, no issue with flats here, including telegram

**Comment by andirsun** [comment]
Actually I dont care so much about update regullary my laptop, I just want to fresh install and enter in store and install some software. 
But on response to your question, I didnt run apt update.

**Comment by andirsun** [comment]
I solved the issue with command
```
❯ flatpak repair --user
[19/41] Verifying flathub:app/org.gnome.Boxes/x86_64/stable…
Removing non-deployed ref flathub:runtime/org.freedesktop.Platform/x86_64/21.08…
Checking remotes...
Pruning objects
Erasing .removed

```
