### ISSUE TITLE
Raspberry Pi400 limited to 1080p

### ISSUE THREAD

**Issue by vwbusguy** [pop-os/beta#297]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
x11 - xorg 1:7.7+22ubuntu2

**Issue/Bug Description:**
Pop only detects up and allows up to 1080p on a Pi400 when connected to a 1440p monitor. hdmi_enable_4kp60=1 is set in config.txt by default and the higher resolution works with other distros on this monitor. xrandr shows 1920x1028@60 as the highest. 

**Steps to reproduce (if you know):**
Fresh install of Pop_OS 21.10 beta, connected to 1440p monitor via hdmi

**Expected behavior:**
Full resolution of monitor up to what the Pi400 and monitor support. 

**Other Notes:**

**Comment by vwbusguy** [comment]
It appears to be a kernel parameter limiting it:

```
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:1920x1080M@60 smsc95xx.macaddr=DC:A6:32:DA:EF:22 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
```

**Comment by vwbusguy** [comment]
It looks like this might be somehow getting implied incorrectly from the fkms based on https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/configuration/kernel-command-line-config.adoc#display-entries-in-fkms-and-kms-modes

**Comment by vwbusguy** [comment]
I booted up Ubuntu 21.10 and can confirm that this is a regression for Pop_OS.  I get 1440p from Ubuntu 21.10 on the same Pi400 and monitor but only up to 1080p on Pop_OS 21.10 Beta.

![Screenshot from 2021-11-15 10-37-04](https://user-images.githubusercontent.com/5474941/141836605-dc8a88a2-ae7b-4034-9cb9-c56f1ee62594.png)

**Comment by jacobgkau** [comment]
It looks like that Ubuntu session is running Wayland. Does Ubuntu have the issue if you choose an Xorg session, and/or does Pop have the issue if you enable Wayland in `/etc/gdm3/custom.conf` and log into a Wayland session?

**Comment by vwbusguy** [comment]
I'll try Wayland, but the kernel command line I posted above from dmesg suggests it's an issue before the display server starts.  I'll report back after trying x11 ob Ubuntu and/or Wayland on Pop.

**Comment by vwbusguy** [comment]
x11 on Ubuntu 21.10 also works with 1440p:
![image](https://user-images.githubusercontent.com/5474941/141844478-b483204f-cac8-42f2-842b-50b5d098c74c.png)

**Comment by vwbusguy** [comment]
Wayland didn't make a difference.

In summary, I get 1440p with Wayland and x11 on Ubuntu 21.10.   I only get 1080p on Pop_OS with x11 or Wayland.

**Comment by vwbusguy** [comment]
Good news!  I updated recently and now have 1440p.
