### ISSUE TITLE
Search bar entry in Activites menu are hard to read with mouse over

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#3]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome 3.36.0

**Issue/Bug Description:**

Screenshot: https://ibb.co/DG5z7Nd (Pointer was excluded in shot)

**Steps to reproduce (if you know):**

Enter text into search bar and place mouse over

**Expected behavior:**

**Other Notes:**

**Comment by WatchMkr** [comment]
This should be fixed.
