### ISSUE TITLE
Switching sound output doesn't work with usb attached device

### ISSUE THREAD

**Issue by bflanagin** [pop-os/beta#30]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Upgrade 19.10 to 20.04

**Issue/Bug Description:**

When switching from the standard sound output device to my usb attached device the interface shows that the device has switched but the output is still being sent to the default device.

**Steps to reproduce (if you know):**

Plug in usb device with sound output. Set the device as the output device in the settings panel. Test the audio output. Change it back to the systems default and test it again. Then change it to the usb device again and test. 

**Expected behavior:**

The device listed as the current output device should be handling the output. 

**Other Notes:**

This could be an upstream issue caused by Gnome or Pulse. Will look into it and report back to this issue.

**Comment by OldmanHades** [comment]
Had the same issue.  I removed the device. headphones, and then put them back in.  It showed the mic not the headphones.  I then rebooted and it fixed the issue.
