### ISSUE TITLE
[Raspberry pi 400] After latest kernel updates, audio card doesn't work

### ISSUE THREAD

**Issue by oguzkarayemis** [pop-os/beta#306]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pulseaudio, ALSA

**Issue/Bug Description:**

After upgraded to the latest kernel, there is no audio card shown on pavucontrol, or system settings at Raspberry Pi 400. The only output is the "dummy output".

I tried these instructions step by step, there is no luck: https://itsfoss.com/fix-sound-ubuntu-1304-quick-tip/

**Steps to reproduce (if you know):**

**Expected behavior:**

Listen any music, hear any sound you want.

**Other Notes:**

Upgraded packages:

```
Start-Date: 2021-11-18  15:07:18
Commandline: apt upgrade -y
Requested-By: oguz (1000)
Install: linux-headers-5.13.0-1010-raspi:arm64 (5.13.0-1010.12, automatic), linux-modules-5.13.0-1010-raspi:arm64 (5.13.0-1010.12, automatic), linux-raspi-headers-5.13.0-1010:arm64 (5.13.0-1010.12, automatic), linux-image-5.13.0-1010-raspi:arm64 (5.13.0-1010.12, automatic)
Upgrade: gnome-shell-extension-cosmic-dock:arm64 (70~ubuntu1pop0~1636405927~21.10~92ae103, 70~ubuntu1pop0~1636744323~21.10~55e6d91), pop-shop:arm64 (3.4.2pop0~1634231591~21.10~ee0f962, 3.4.2pop0~1636659358~21.10~60d6e84), netplan.io:arm64 (0.103-0ubuntu7, 0.103-0ubuntu7.1), linux-headers-raspi:arm64 (5.13.0.1009.15, 5.13.0.1010.16), linux-raspi:arm64 (5.13.0.1009.15, 5.13.0.1010.16), libnetplan0:arm64 (0.103-0ubuntu7, 0.103-0ubuntu7.1), linux-image-raspi:arm64 (5.13.0.1009.15, 5.13.0.1010.16), linux-libc-dev:arm64 (5.15.0-76051500.202110312130~1635774356~21.10~6482cb7, 5.15.2-76051502.202111121041~1636734399~21.10~1c02b32)
```

**Comment by sergioad** [comment]
Same here

**Comment by HanYangCoder** [comment]
I have the same issue as well after updating 2 days ago with my RPi4, I had the new kernel upgrade (5.13.0-1010-raspi:arm64) and a couple of packages (including ALSA and Pulseaudio packages) updated and my HDMI audio output doesn't work anymore after the update. Though unlike the first two issues above mine, my 3.5 mm jack output is still detected by the alsa-mixer, is still visible in the settings, and is still functioning well whenever I connect my headphones to it.

**Comment by oguzkarayemis** [comment]
So, I can imagine that this issue maybe not a common issue, so here is some troubleshooting:

`inxi -Axxx
Audio:     Device-1: bcm2835-audio driver: bcm2835_audio bus-ID: N/A 
           chip-ID: brcm:bcm2835_audio class-ID: bcm2835_audio 
           Device-2: bcm2711-hdmi0 driver: N/A bus-ID: N/A chip-ID: brcm:soc 
           class-ID: hdmi 
           Device-3: bcm2711-hdmi1 driver: N/A bus-ID: N/A chip-ID: brcm:soc 
           class-ID: hdmi 
           Sound Server-1: ALSA v: k5.13.0-1011-raspi running: yes 
           Sound Server-2: PulseAudio v: 15.0 running: yes 
           Sound Server-3: PipeWire v: 0.3.32 running: yes`

`lsmod | grep snd     
snd_bcm2835            32768  0
snd_soc_core          274432  1 vc4
snd_compress           32768  1 snd_soc_core
snd_pcm_dmaengine      20480  1 snd_soc_core
snd_pcm               139264  4 snd_bcm2835,snd_compress,snd_soc_core,snd_pcm_dmaengine
snd_seq_midi           20480  0
snd_seq_midi_event     16384  1 snd_seq_midi
snd_rawmidi            49152  1 snd_seq_midi
snd_seq                90112  2 snd_seq_midi,snd_seq_midi_event
snd_seq_device         20480  3 snd_seq,snd_seq_midi,snd_rawmidi
snd_timer              45056  2 snd_seq,snd_pcm
snd                   110592  8 snd_seq,snd_seq_device,snd_bcm2835,snd_timer,snd_compress,snd_soc_core,snd_pcm,snd_rawmidi
ac97_bus               16384  1 snd_soc_core`

`lspci                
00:00.0 PCI bridge: Broadcom Inc. and subsidiaries BCM2711 PCIe Bridge (rev 20)
01:00.0 USB controller: VIA Technologies, Inc. VL805/806 xHCI USB 3.0 Controller (rev 01)`

`sudo dmesg | grep -i audio
[   10.738515] bcm2835_audio bcm2835_audio: there is not valid maps for state default`

`alsamixer
cannot open mixer: No such file or directory`

`aplay -l
aplay: device_list:276: no soundcards found...`

**Comment by sergioad** [comment]
Using FKMS solves this

**Comment by oguzkarayemis** [comment]
@sergioad this is an interesting conflict, but for me using kms solved the issue. Whenever I use fkms, the "dummy output" comes back. Thank you for your comment though, I finally understood what is going on in my system and what causes this.

**Comment by sergioad** [comment]
@oguzkarayemis for me FKMS was the solution... Maybe our TVs are too exotic...

**Comment by oguzkarayemis** [comment]
Ok, I believe we can summarise the solution like this for the possible future problems: 
1- First, open the config.txt file:
`sudo gedit /boot/firmware/config.txt`
2- Check your kms drive line: this can be either `dtoverlay=vc4-kms-v3d`, or `dtoverlay=vc4-fkms-v3d`
3- If that's `dtoverlay=vc4-fkms-v3d`, make it `dtoverlay=vc4-kms-v3d`, or vice versa. 
4- Then save config.txt and reboot. Check if your sound card is now on.

I'm closing this bug report, thank @sergioad for their contribution.

**Comment by sergioad** [comment]
@oguzkarayemis it is a true pleasure to help, I love what you are making here
