### ISSUE TITLE
meer4 boots to blank screen

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/beta#307]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**: Happens when attempting to boot from a live disk, also happens after an upgrade (reported by @mdpetters via https://github.com/pop-os/beta/issues/273#issuecomment-972880828, recreated with live disk in the lab.)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Kernel 5.15? @mdpetters reports 21.10 boots with kernel 5.13.

**Issue/Bug Description:** When attempting to boot, after selecting `Try or Install` from the boot menu, the screen remains powered on but shows nothing. Esc, spacebar, etc don't show any output. The live disk already does not have `quiet` or `splash`, so I can't remove those; removing `noprompt` did not change the behavior (looks like `noprompt` is just for the CD ejection prompt, anyway). A USB keyboard's backlight does turn off as if it detects an OS, but the keyboard backlight controls don't turn it back on.

**Steps to reproduce (if you know):** Attempt to boot Intel iso #12 on meer4 (customer & lab unit both have i7-8559U).

**Expected behavior:** Boots to desktop.

**Other Notes:** https://github.com/pop-os/beta/issues/273#issuecomment-972880828 / https://github.com/pop-os/beta/issues/273#issuecomment-973179087

**Comment by jacobgkau** [comment]
Kernel 5.15.3 from the Mainline app does not have this issue.

**Comment by jacobgkau** [comment]
Should be fixed by https://github.com/pop-os/linux/pull/81, updating kernel to 5.15.4.

**Comment by mdpetters** [comment]
Fixed with 5.15.4 on my machine.

**Comment by leviport** [comment]
Excellent, thanks for confirming!
