### ISSUE TITLE
Suspend broken on Lenovo ThinkPad E565

### ISSUE THREAD

**Issue by pbrilius** [pop-os/beta#315]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install.

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

systemd:
  Įdiegta:    248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa
  Kandidatas: 248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa
  Versijų lentelė:
 *** 248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
     248.3-1ubuntu8 500
        500 http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages

**Issue/Bug Description:**

None of the suspension evoking/triggering actions like` systemctl suspend -i `or _GNOME_ panel navigator to suspend button works, leaving the laptop at stale state, which means the **ThinkPad** red **LED** is still on, though _nothing happens_ except the reboot option with the hard power off button click of for 5 s.

**Steps to reproduce (if you know):**

Power on the laptop, **boot** it up, log in and try to _suspend_ in any known way.

**Expected behavior:**

Laptop **suspends**, closing the lid, e. g., or informs of the _broken_ suspension behavioral package.

**Other Notes:**

**Comment by jacobgkau** [comment]
@pbrilius You stated https://github.com/pop-os/beta/issues/316 was resolved with an update. Was this issue also resolved with that update? (I'm assuming it was the kernel 5.15.5 update, or something Ubuntu is shipping, since we did not update systemd since you opened these.)

**Comment by pbrilius** [comment]
> @pbrilius You stated #316 was resolved with an update. Was this issue also resolved with that update? (I'm assuming it was the kernel 5.15.5 update, or something Ubuntu is shipping, since we did not update systemd since you opened these.)

Sure it _was_, **thank** **you** indeed.
