### ISSUE TITLE
[Dell Precision 5540] Missing text, icons after resuming from suspend

### ISSUE THREAD

**Issue by jyavorska** [pop-os/beta#317]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Upgraded from 21.04.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

No specific program (just the DE itself)

**Issue/Bug Description:**

When resuming from suspend, some letters are missing from the login screen when it shows my name. After logging in, the command search is missing text and icons, dock is missing icons, and menu is missing content.

![Screenshot from 2021-11-30 14-29-50](https://user-images.githubusercontent.com/3529318/144056692-6963d2ff-d778-4db7-89fe-e56ff64dd369.png)

![Screenshot from 2021-11-30 14-29-54](https://user-images.githubusercontent.com/3529318/144056706-5d371a25-14ce-46c3-8362-c2163aaf8902.png)

**Steps to reproduce (if you know):**

Suspend and resume.

**Expected behavior:**

Normal display after resume.

**Other Notes:**

The system is a Dell Precision 5540 with NVIDIA/Intel. The system is running in "Nvidia Graphics" mode.

Restarting Gnome using alt+f2 and running `r` resolves the issue.

Did not have the issue in 21.04.

**Comment by jacobgkau** [comment]
Thank you for trying the beta. Does the issue also happen if you run in Integrated graphics mode, or is it only in NVIDIA mode?

The output of `sudo journalctl --follow` while this is happening (or `sudo journalctl -b 0` after it's happened) may show more information about what's happening.

**Comment by jyavorska** [comment]
Of course, now that I have troubleshooting steps I can't repro it. There was an update that came in last night, perhaps that resolved it or it was a one-time weirdness. I'll keep an eye on it and reopen this if I happen to come across it again.
