### ISSUE TITLE
Menu won't disappear after clicking on "launch with dedicated graphics card"

### ISSUE THREAD

**Issue by oguzkarayemis** [pop-os/beta#319]
https://user-images.githubusercontent.com/80787950/144084757-2e17777a-5105-4314-bdc4-4c102c98aab9.mp4

**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Upgraded from 21.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

App Menu

**Issue/Bug Description:**

The app menu won't disappear after clicking on "launch with dedicated graphics card", while does disappear after just clicking on any item on the menu.

**Steps to reproduce (if you know):**

1) Open the app menu
2) Right click on whatever item you want to launch with dedicated graphics card
3) App launching, but menu staying.

**Expected behavior:**

The menu must disappear after the click.

**Other Notes:**

**Comment by leviport** [comment]
I'm seeing this with more than just the "Launch with Discrete GPU" option. I'm also seeing it with the "New Window" and "Show Details" options that most apps have, as well as some of the custom options like Gedit's "New Document" or Geary's "Compose Message" options.

**Comment by leviport** [comment]
Should be fixed by https://github.com/pop-os/cosmic/pull/251
