### ISSUE TITLE
Custom cursor themes aren't always applied when selected in GNOME Tweaks

### ISSUE THREAD

**Issue by pbrilius** [pop-os/beta#323]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh one.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

apt policy gnome-tweaks
gnome-tweaks:
  Įdiegta:    40.0-3
  Kandidatas: 40.0-3
  Versijų lentelė:
 *** 40.0-3 500
        500 http://us.archive.ubuntu.com/ubuntu impish/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu impish/universe i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

I download as a matter of fact several cursor themes from [Pling Store](https://www.pling.com/p/1175480/) (or clone from [github.com](https://github.com/vinceliuice)) and only **MacOS** _Big Sur_ is applied easily w/o/ any additional tuning, others leave the default **POP! cursor** in place.

**Steps to reproduce (if you know):**

Download and apply several cursor _gtk3_ themes in a **sequence** and you will see the same _malware_ -- not applied most of them cursors, only seldom of them.

**Expected behavior:**

The cursor theme is applied easily w/o/ a fuss on an **Open** **Source** paradigm _distribution_ like **GNOME** _gtk3_ desktop of **POP**! [OS](https://pop.system76.com/).

**Other Notes:**

**Comment by jacobgkau** [comment]
> and you will see the same *malware*

Nothing in your post suggests unwanted code running on your machine. Please do not use alarming words like "malware" without reason.

Do I understand correctly that this issue is about applying any cursor theme via GNOME Tweaks, and is not related to the Pling Store?

**Comment by pbrilius** [comment]
I am signifying the use case **processional** way - the cursor is applied in a _distributional_ manner, likewise not originating from a POP! repositories necessarily - via Pling Store or via source code `./install.sh` CLI issued command.

**Comment by jacobgkau** [comment]
Does this issue occur in Pop!_OS 21.04, or Ubuntu 21.10?

**Comment by pbrilius** [comment]
As far as I'm concerned - as I tried out both of them - **none** is **facing** any similar issues _concerning_ cursor _theme_ application & change @jacobgkau .

**Comment by jacobgkau** [comment]
@pbrilius Why was this issue closed?

**Comment by pbrilius** [comment]
@jacobgkau Because I tried _several_ more themes from **Pling** Store and the majority of them worked...

**Comment by jacobgkau** [comment]
Closed based on your report that cursor themes are working.
