### ISSUE TITLE
Settings menu doesn't show 2nd level options under "Desktop" when in small(single pane?) mode.

### ISSUE THREAD

**Issue by emujoyce** [pop-os/beta#327]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh Install to a virtualbox vm -> ran `sudo apt full-upgrade` before doing anything.
Verified on 2nd VM running in live mode, no updates

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Settings Menu

**Issue/Bug Description:**
![image](https://user-images.githubusercontent.com/10076359/144761470-45bb19d7-558d-4028-ab0f-fa92133e0a79.png)
When the Settings menu is in small mode, the menu items with 2nd levels of options have a ">" on the right.

If I click on "privacy" I get the second level of menu options
![image](https://user-images.githubusercontent.com/10076359/144761550-7ad5ec65-9d02-43e2-8f2f-9d36a99b21b8.png)

Then I can click on something like "Connectivity" to get to the options there.
![image](https://user-images.githubusercontent.com/10076359/144761599-5c65f415-c065-4a9f-b685-3163cb1be0ff.png)

That is all working as expected.

The Menus under "Desktop" do not work. 
![image](https://user-images.githubusercontent.com/10076359/144761686-6e1d2d33-bcf0-4e18-9a13-e162f756f1bc.png)

You can click into the first menu but you can't get to any of the second level items there. 
![image](https://user-images.githubusercontent.com/10076359/144761717-b3d25b10-ab7c-499a-ba75-f90692680156.png)

The only way to access those items is to use the expanded menu.
![image](https://user-images.githubusercontent.com/10076359/144761740-92443c97-da32-4ef0-bdba-6fcd4e3caa57.png)

**Steps to reproduce (if you know):**
Created a 2nd VM running in live mode
![image](https://user-images.githubusercontent.com/10076359/144762171-18990854-13f3-4bde-a419-aabe67e9e033.png)
Same behavior in the unpatched VM

**Expected behavior:**
The menu should show the second level options as in the Privacy menu
![image](https://user-images.githubusercontent.com/10076359/144761550-7ad5ec65-9d02-43e2-8f2f-9d36a99b21b8.png)

**Other Notes:**

**Comment by n3m0-22** [comment]
Closing because I can't replicate the issue. I believe it has since been resolved, but we can reopen if you are still seeing it.
