### ISSUE TITLE
Suspend icon missing from context Super key stage menu

### ISSUE THREAD

**Issue by pbrilius** [pop-os/beta#334]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Fresh installation.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

appstream-data-pop-icons:
  Įdiegta:    0.0.3~1622638394~21.10~41bbf24
  Kandidatas: 0.0.3~1622638394~21.10~41bbf24
  Versijų lentelė:
 *** 0.0.3~1622638394~21.10~41bbf24 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The icon is missing, calling it to the _warning_ replacement.

**Steps to reproduce (if you know):**

Click on the Super key - Lenovo ThinkPad SMB E565 laptop case; enter _suspend_ keyword to the search bar.

**Expected behavior:**

The icon is present like all the around, e.g. **power** **off** action.

**Other Notes:**

**Comment by pbrilius** [comment]
I'll add up **restart** button as we ll to the _problematic_ case.

**Comment by leviport** [comment]
Did you do anything with your 21.10 install after it was freshly installed, perhaps involving changing icon themes? Could you provide a screenshot of the launcher with the missing icon? Fresh installs are showing the icon for me, so more information and screenshots would definitely be helpful.

![Screenshot from 2021-12-09 10-36-01](https://user-images.githubusercontent.com/13512097/145447298-c1c0a2e7-71fd-4ec6-9b4c-33bdaf2f7379.png)

**Comment by ggobbe** [comment]
I got the restart, poweroff and suspend icons with both **PopOS** and **Numix** icon themes.

But with Adwaita (default) that is already installed, there is an odd behaviour:

- if I select PopOS icon theme, then Adwaita (default), all icons are working :heavy_check_mark: 
- if I select Numix icon theme, then Adwaita (default), the suspend and restart icons are missing (and it looks like Adwaita (default) doesn't override some icons from the previously choose theme such as the one for Nautilus :warning: (cf. screenshot)

![image](https://user-images.githubusercontent.com/2607273/145534968-e0e1b885-e643-479e-b5dd-e46c2305d6db.png)

![image](https://user-images.githubusercontent.com/2607273/145535026-a1142b56-87e0-4353-808d-ad7180771142.png)

![image](https://user-images.githubusercontent.com/2607273/145535074-389ca4cf-e895-4d72-a301-3d543e505e91.png)

**Comment by pbrilius** [comment]
Sure @ggobbe you are correct, I just _changed_ it back from POP - branding, which had several of their icons missing back to default POP! and it works.
