### ISSUE TITLE
Not possible to remove 2 apps from Pop Shop

### ISSUE THREAD

**Issue by evil-arri** [pop-os/beta#34]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome Weather App and Videos

**Issue/Bug Description:**
When trying to uninstall them from Pop Shop they refuse to uninstall with a message stating I'm trying to remove an essential package.

**Steps to reproduce (if you know):**
Go to Pop Shop, installed apps, select gnome weather or videos and uninstall. After entering password they are not uninstalled.

**Expected behavior:**
They both apps should be able to uninstall. In 19.10 is possible.

**Other Notes:**

**Comment by evil-arri** [comment]
![Captura de pantalla de 2020-04-17 13-16-03](https://user-images.githubusercontent.com/56842169/79597023-89567c00-80af-11ea-9390-842eac1e6b87.png)

**Comment by devcass** [comment]
Hey!
What’s up?

This app is a part of the system. You cannot remove it

**Comment by evil-arri** [comment]
That's not cool. I wonder why. In Ubuntu they are not even included.
