### ISSUE TITLE
On RPI4 POP-UPGRADE DAEMON is using 100% of 1 core... 

### ISSUE THREAD

**Issue by curyjorge98** [pop-os/beta#345]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 Fresh install.
Using pop-os since oct/21 and every day dist-upgrade. 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
On RPI4 POP-UPGRADE DAEMON is using 100% of 1 core for more than 15 minutes on every boot or reboot.
Is it OK???
Cant remember when it began, but I think last week or two.

**Steps to reproduce (if you know):**

just reboot.

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
You can watch the daemon's logs with `journalctl -fu pop-upgrade` to check if it's logging anything.

**Comment by curyjorge98** [comment]
Hi Mmstick,

I dont know what it mean, but this is the output:

$ journalctl -fu pop-upgrade
-- Journal begins at Wed 2021-11-17 01:59:40 -03. --
jan 06 19:26:04 pop-os pop-upgrade[777]:     Sender: ":1.63",
jan 06 19:26:04 pop-os pop-upgrade[777]:     Destination: "com.system76.PopUpgrade",
jan 06 19:26:04 pop-os pop-upgrade[777]:     Serial: 14,
jan 06 19:26:04 pop-os pop-upgrade[777]:     Args: [
jan 06 19:26:04 pop-os pop-upgrade[777]:         false,
jan 06 19:26:04 pop-os pop-upgrade[777]:     ],
jan 06 19:26:04 pop-os pop-upgrade[777]: }
jan 06 19:26:04 pop-os pop-upgrade[777]: [INFO ] pop_upgrade src/daemon/mod.rs:891: performing a release check
jan 06 19:26:04 pop-os pop-upgrade[777]: [INFO ] pop_upgrade src/daemon/mod.rs:897: Release { current: "21.10", lts: "false",  next: "22.04", available: false }
jan 06 19:26:04 pop-os pop-upgrade[777]: [INFO ] pop_upgrade src/release_api.rs:55: checking for build 21.10 in channel nvidia

**Comment by curyjorge98** [comment]
Issue solved by someone.
