### ISSUE TITLE
[22.04] Upon update, previously non-selected Japanese input support is present.

### ISSUE THREAD

**Issue by XV-02** [pop-os/beta#349]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
 Upgrading via the pop-upgrade utility from 20.04 --> 21.10 --> 22.04 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I believe this is tied to gnome-settings, as that seems to be where the keyboard input settings reside.

**Issue/Bug Description:**
With a fresh 20.04 install, fully updated, the pop-upgrade utility was run to update to 21.10, and then from that [without updating/upgrading] updating to 22.04. At no point were Japanese language input methods [In this case through Japanese (Mozc)] added. However, when transitioning into 22.04, these input methods appeared, and also were default on boot.

**Steps to reproduce (if you know):**
Uncertain, likely updating to 22.04 from 21.10.

**Expected behavior:**
When upgrading from a current release to 22.04, settings should port over without additions or modifications to those defaults where continuity is possible. In this case, Japanese language input support should not be spontaneously present.

**Other Notes:**
None

**Comment by jackpot51** [comment]
Should be fixed with https://github.com/pop-os/mozc/tree/master_jammy
