### ISSUE TITLE
Best way to upgrade to 22.04 when you're using pipewire from the PPA

### ISSUE THREAD

**Issue by mygnu** [pop-os/beta#352]
I have used this guide https://reddit.com/r/pop_os/comments/ofdalv/replaced_pulseaudio_with_pipewire_on_popos_2104_i/
It has been working great so far apart from one incident where and update broke my system for a day but it was fixed. 
Will there be any compatibility issues when system already has pipewire?

**Comment by jotuel** [comment]
No. ppa gets removed by the upgrade. A few packages from it survive the upgrade.

**Comment by mygnu** [comment]
Thanks for the confirmation, I'll re-open the issue if there are any problems.
