### ISSUE TITLE
libglib2.0-0:i386 dependency error prevents installing updates

### ISSUE THREAD

**Issue by Chinchzilla** [pop-os/beta#355]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

chinchzilla@chinchzilla-desktop:~$ apt policy libglib2.0-0:i386
libglib2.0-0:i386:
  Installed: 2.72.0-1
  Candidate: 2.72.0-1
  Version table:
 *** 2.72.0-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Following error appears when trying to update

![betaerror1](https://user-images.githubusercontent.com/92267798/161208821-059736d9-8a10-489f-9db1-c55407c6ea2c.png)

dpkg: error processing package libglib2.0-0:i386 (--configure):
 dependency problems - leaving triggers unprocessed
No apport report written because MaxReports has already been reached
                                                                    dpkg: dependency problems
 prevent processing triggers for libglib2.0-0:i386:
 libglib2.0-0:i386 depends on libpcre3; however:
  Package libpcre3:i386 is not configured yet.
 libglib2.0-0:i386 depends on libselinux1 (>= 3.1~); however:
  Package libselinux1:i386 is not configured yet.

**Steps to reproduce (if you know):**

update in Pop shop or "sudo apt get upgrade"

**Expected behavior:**

Packages get updated

**Other Notes:**

my packages that can't be updated
chinchzilla@chinchzilla-desktop:~$ apt list --upgradable 
Listing... Done
apport/jammy,jammy 2.20.11-0ubuntu80 all [upgradable from: 2.20.11-0ubuntu79]
aspell/jammy 0.60.8-4build1 amd64 [upgradable from: 0.60.8-4]
dctrl-tools/jammy 2.24-3build2 amd64 [upgradable from: 2.24-3build1]
folks-common/jammy,jammy 0.15.5-2 all [upgradable from: 0.15.4-1]
gir1.2-gtk-3.0/jammy 3.24.33-1ubuntu1 amd64 [upgradable from: 3.24.32-0ubuntu1]
gir1.2-json-1.0/jammy 1.6.6-1build1 amd64 [upgradable from: 1.6.6-1]
gir1.2-nm-1.0/jammy 1.36.4-1ubuntu1 amd64 [upgradable from: 1.36.2-1ubuntu1]
gir1.2-vte-2.91/jammy 0.68.0-1 amd64 [upgradable from: 0.67.90-2]
gnome-terminal-data/jammy,jammy 3.44.0-1ubuntu1 all [upgradable from: 3.43.90-1ubuntu1]
gnome-terminal/jammy 3.44.0-1ubuntu1 amd64 [upgradable from: 3.43.90-1ubuntu1]
gtk-update-icon-cache/jammy 3.24.33-1ubuntu1 amd64 [upgradable from: 3.24.32-0ubuntu1]
intel-media-va-driver/jammy 22.2.1+dfsg1-1build1 amd64 [upgradable from: 22.2.1+dfsg1-1]
intel-media-va-driver/jammy 22.2.1+dfsg1-1build1 i386 [upgradable from: 22.2.1+dfsg1-1]
libaspell15/jammy 0.60.8-4build1 amd64 [upgradable from: 0.60.8-4]
libayatana-appindicator3-1/jammy 0.5.90-7ubuntu2 amd64 [upgradable from: 0.5.90-7]
libetonyek-0.1-1/jammy 0.1.10-3build1 amd64 [upgradable from: 0.1.10-3]
libfftw3-double3/jammy 3.3.8-2ubuntu8 amd64 [upgradable from: 3.3.8-2ubuntu7]
libfftw3-single3/jammy 3.3.8-2ubuntu8 amd64 [upgradable from: 3.3.8-2ubuntu7]
libfolks-eds26/jammy 0.15.5-2 amd64 [upgradable from: 0.15.4-1]
libfolks26/jammy 0.15.5-2 amd64 [upgradable from: 0.15.4-1]
libgtk-3-bin/jammy 3.24.33-1ubuntu1 amd64 [upgradable from: 3.24.32-0ubuntu1]
libjson-glib-1.0-0/jammy 1.6.6-1build1 amd64 [upgradable from: 1.6.6-1]
libjson-glib-1.0-common/jammy,jammy 1.6.6-1build1 all [upgradable from: 1.6.6-1]
libmalcontent-0-0/jammy 0.10.4-1 amd64 [upgradable from: 0.10.3-1]
libmythes-1.2-0/jammy 2:1.2.4-4build1 amd64 [upgradable from: 2:1.2.4-4]
libnm0/jammy 1.36.4-1ubuntu1 amd64 [upgradable from: 1.36.2-1ubuntu1]
libodfgen-0.1-1/jammy 0.1.8-2build2 amd64 [upgradable from: 0.1.8-2build1]
libshout3/jammy 2.4.5-1build3 amd64 [upgradable from: 2.4.5-1build2]
libsndfile1/jammy 1.0.31-2build1 amd64 [upgradable from: 1.0.31-2]
libsndfile1/jammy 1.0.31-2build1 i386 [upgradable from: 1.0.31-2]
libvoikko1/jammy 4.3.1-1build1 amd64 [upgradable from: 4.3.1-1]
libvorbis0a/jammy 1.3.7-1build2 amd64 [upgradable from: 1.3.7-1build1]
libvorbis0a/jammy 1.3.7-1build2 i386 [upgradable from: 1.3.7-1build1]
libvorbisenc2/jammy 1.3.7-1build2 amd64 [upgradable from: 1.3.7-1build1]
libvorbisenc2/jammy 1.3.7-1build2 i386 [upgradable from: 1.3.7-1build1]
libvorbisfile3/jammy 1.3.7-1build2 amd64 [upgradable from: 1.3.7-1build1]
libvorbisfile3/jammy 1.3.7-1build2 i386 [upgradable from: 1.3.7-1build1]
libvte-2.91-0/jammy 0.68.0-1 amd64 [upgradable from: 0.67.90-2]
libvte-2.91-common/jammy 0.68.0-1 amd64 [upgradable from: 0.67.90-2]
libwxbase3.0-0v5/jammy 3.0.5.1+dfsg-4 amd64 [upgradable from: 3.0.5.1+dfsg-3]
libwxgtk3.0-gtk3-0v5/jammy 3.0.5.1+dfsg-4 amd64 [upgradable from: 3.0.5.1+dfsg-3]
nautilus-extension-gnome-terminal/jammy 3.44.0-1ubuntu1 amd64 [upgradable from: 3.43.90-1ubuntu1]
network-manager/jammy 1.36.4-1ubuntu1 amd64 [upgradable from: 1.36.2-1ubuntu1]
python3-apport/jammy,jammy 2.20.11-0ubuntu80 all [upgradable from: 2.20.11-0ubuntu79]
python3-problem-report/jammy,jammy 2.20.11-0ubuntu80 all [upgradable from: 2.20.11-0ubuntu79]
python3-software-properties/jammy,jammy 0.99.21 all [upgradable from: 0.99.20]
software-properties-common/jammy,jammy 0.99.21 all [upgradable from: 0.99.20]
xdg-desktop-portal/jammy 1.14.1-2 amd64 [upgradable from: 1.14.1-1]

**Comment by Chinchzilla** [comment]
resovled reinstalling the package

chinchzilla@chinchzilla-desktop:~$ sudo apt reinstall libglib2.0-0:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 to upgrade, 0 to newly install, 2 reinstalled, 0 to remove and 48 not to upgrade.
33 not fully installed or removed.
Need to get 3,021 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libglib2.0-0 amd64 2.72.0-1 [1,458 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu jammy/main i386 libglib2.0-0 i386 2.72.0-1 [1,563 kB]
Fetched 3,021 kB in 2s (1,461 kB/s)          
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libglib2.0-0_2.72.0-1_amd64.deb ...
Unpacking libglib2.0-0:amd64 (2.72.0-1) over (2.72.0-1) ...
Preparing to unpack .../libglib2.0-0_2.72.0-1_i386.deb ...
Unpacking libglib2.0-0:i386 (2.72.0-1) over (2.72.0-1) ...
Setting up libglib2.0-0:amd64 (2.72.0-1) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu1) ...
Setting up libpcrecpp0v5:amd64 (2:8.39-13build5) ...
Setting up cups-browsed (1.28.13-0ubuntu1) ...
Setting up gcc-11-base:i386 (11.2.0-19ubuntu1) ...
Setting up libpcre16-3:amd64 (2:8.39-13build5) ...
Setting up libgutenprint-common (5.3.3-9) ...
Setting up libbrotli1:i386 (1.0.9-2build6) ...
Setting up libedit2:i386 (3.1-20210910-1build1) ...
Setting up avahi-utils (0.8-5ubuntu5) ...
Setting up libssl3:i386 (3.0.2-0ubuntu1) ...
Setting up libidn2-0:i386 (2.3.2-2build1) ...
Setting up libpcre2-16-0:amd64 (10.39-3build1) ...
Setting up libpcre3:i386 (2:8.39-13build5) ...
Setting up libavahi-common-data:i386 (0.8-5ubuntu5) ...
Setting up libpng16-16:i386 (1.6.37-3build5) ...
Setting up libpcre32-3:amd64 (2:8.39-13build5) ...
Setting up libxrandr2:i386 (2:1.5.2-1build1) ...
Setting up libpcre2-8-0:i386 (10.39-3build1) ...
Setting up libpcre2-posix3:amd64 (10.39-3build1) ...
Setting up sane-utils (1.1.1-5) ...
update-inetd: warning: cannot add service, /etc/inetd.conf does not exist
usermod: no changes
saned.socket is a disabled or a static unit not running, not starting it.
Setting up libgutenprint9 (5.3.3-9) ...
Setting up libpcre2-dev:amd64 (10.39-3build1) ...
Setting up libselinux1-dev:amd64 (3.3-1build2) ...
Setting up libpcre3-dev:amd64 (2:8.39-13build5) ...
Setting up libavahi-common3:i386 (0.8-5ubuntu5) ...
Setting up printer-driver-gutenprint (5.3.3-9) ...
Setting up libselinux1:i386 (3.3-1build2) ...
Setting up libfreetype6:i386 (2.11.1+dfsg-1build1) ...
Setting up libfontconfig1:i386 (2.13.1-4.2ubuntu5) ...
Setting up libavahi-client3:i386 (0.8-5ubuntu5) ...
Setting up libglib2.0-0:i386 (2.72.0-1) ...
Setting up libpango-1.0-0:i386 (1.50.6+ds-1) ...
Setting up libpangoft2-1.0-0:i386 (1.50.6+ds-1) ...
Setting up libpangocairo-1.0-0:i386 (1.50.6+ds-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Processing triggers for man-db (2.10.1-1) ...
Processing triggers for dbus (1.12.20-2ubuntu3) ...
Processing triggers for udev (249.11-0ubuntu1pop0~1647560284~22.04~9df3952) ...
Processing triggers for install-info (6.8-4build1) ...
Processing triggers for cups (2.4.1op1-1ubuntu4) ...
Updating PPD files for gutenprint ...
chinchzilla@chinchzilla-desktop:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apport aspell dctrl-tools folks-common gir1.2-gtk-3.0 gir1.2-json-1.0 gir1.2-nm-1.0
  gir1.2-vte-2.91 gnome-terminal gnome-terminal-data gtk-update-icon-cache
  intel-media-va-driver intel-media-va-driver:i386 libaspell15 libayatana-appindicator3-1
  libetonyek-0.1-1 libfftw3-double3 libfftw3-single3 libfolks-eds26 libfolks26 libgtk-3-bin
  libjson-glib-1.0-0 libjson-glib-1.0-common libmalcontent-0-0 libmythes-1.2-0 libnm0
  libodfgen-0.1-1 libshout3 libsndfile1 libsndfile1:i386 libvoikko1 libvorbis0a
  libvorbis0a:i386 libvorbisenc2 libvorbisenc2:i386 libvorbisfile3 libvorbisfile3:i386
  libvte-2.91-0 libvte-2.91-common libwxbase3.0-0v5 libwxgtk3.0-gtk3-0v5
  nautilus-extension-gnome-terminal network-manager python3-apport python3-problem-report
  python3-software-properties software-properties-common xdg-desktop-portal
48 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/18.4 MB of archives.
After this operation, 403 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Extract templates from packages: 100%
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gir1.2-gtk-3.0_3.24.33-1ubuntu1_amd64.deb ...
Unpacking gir1.2-gtk-3.0:amd64 (3.24.33-1ubuntu1) over (3.24.32-0ubuntu1) ...
Setting up gir1.2-gtk-3.0:amd64 (3.24.33-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libjson-glib-1.0-common_1.6.6-1build1_all.deb ...
Unpacking libjson-glib-1.0-common (1.6.6-1build1) over (1.6.6-1) ...
Setting up libjson-glib-1.0-common (1.6.6-1build1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libjson-glib-1.0-0_1.6.6-1build1_amd64.deb ...
Unpacking libjson-glib-1.0-0:amd64 (1.6.6-1build1) over (1.6.6-1) ...
Setting up libjson-glib-1.0-0:amd64 (1.6.6-1build1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gir1.2-json-1.0_1.6.6-1build1_amd64.deb ...
Unpacking gir1.2-json-1.0:amd64 (1.6.6-1build1) over (1.6.6-1) ...
Setting up gir1.2-json-1.0:amd64 (1.6.6-1build1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libnm0_1.36.4-1ubuntu1_amd64.deb ...
Unpacking libnm0:amd64 (1.36.4-1ubuntu1) over (1.36.2-1ubuntu1) ...
Setting up libnm0:amd64 (1.36.4-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../network-manager_1.36.4-1ubuntu1_amd64.deb ...
Unpacking network-manager (1.36.4-1ubuntu1) over (1.36.2-1ubuntu1) ...
Setting up network-manager (1.36.4-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gir1.2-nm-1.0_1.36.4-1ubuntu1_amd64.deb ...
Unpacking gir1.2-nm-1.0:amd64 (1.36.4-1ubuntu1) over (1.36.2-1ubuntu1) ...
Setting up gir1.2-nm-1.0:amd64 (1.36.4-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libvte-2.91-common_0.68.0-1_amd64.deb ...
Unpacking libvte-2.91-common (0.68.0-1) over (0.67.90-2) ...
Setting up libvte-2.91-common (0.68.0-1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libvte-2.91-0_0.68.0-1_amd64.deb ...
Unpacking libvte-2.91-0:amd64 (0.68.0-1) over (0.67.90-2) ...
Setting up libvte-2.91-0:amd64 (0.68.0-1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gir1.2-vte-2.91_0.68.0-1_amd64.deb ...
Unpacking gir1.2-vte-2.91:amd64 (0.68.0-1) over (0.67.90-2) ...
Setting up gir1.2-vte-2.91:amd64 (0.68.0-1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gnome-terminal-data_3.44.0-1ubuntu1_all.deb ...
Unpacking gnome-terminal-data (3.44.0-1ubuntu1) over (3.43.90-1ubuntu1) ...
Setting up gnome-terminal-data (3.44.0-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../nautilus-extension-gnome-terminal_3.44.0-1ubuntu1_amd64.deb ...
Unpacking nautilus-extension-gnome-terminal (3.44.0-1ubuntu1) over (3.43.90-1ubuntu1) ...
Preparing to unpack .../gnome-terminal_3.44.0-1ubuntu1_amd64.deb ...
Unpacking gnome-terminal (3.44.0-1ubuntu1) over (3.43.90-1ubuntu1) ...
Setting up gnome-terminal (3.44.0-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../gtk-update-icon-cache_3.24.33-1ubuntu1_amd64.deb ...
Unpacking gtk-update-icon-cache (3.24.33-1ubuntu1) over (3.24.32-0ubuntu1) ...
Setting up gtk-update-icon-cache (3.24.33-1ubuntu1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libaspell15_0.60.8-4build1_amd64.deb ...
Unpacking libaspell15:amd64 (0.60.8-4build1) over (0.60.8-4) ...
Setting up libaspell15:amd64 (0.60.8-4build1) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../aspell_0.60.8-4build1_amd64.deb ...
Unpacking aspell (0.60.8-4build1) over (0.60.8-4) ...
Preparing to unpack .../libvorbis0a_1.3.7-1build2_amd64.deb ...
De-configuring libvorbis0a:i386 (1.3.7-1build1), to allow configuration of libvorbis0a:amd64 
(1.3.7-1build1) ...
Unpacking libvorbis0a:amd64 (1.3.7-1build2) over (1.3.7-1build1) ...
Preparing to unpack .../libvorbis0a_1.3.7-1build2_i386.deb ...
Unpacking libvorbis0a:i386 (1.3.7-1build2) over (1.3.7-1build1) ...
Preparing to unpack .../libvorbisfile3_1.3.7-1build2_i386.deb ...
De-configuring libvorbisfile3:amd64 (1.3.7-1build1), to allow configuration of libvorbisfile3
:i386 (1.3.7-1build1) ...
Unpacking libvorbisfile3:i386 (1.3.7-1build2) over (1.3.7-1build1) ...
Preparing to unpack .../libvorbisfile3_1.3.7-1build2_amd64.deb ...
Unpacking libvorbisfile3:amd64 (1.3.7-1build2) over (1.3.7-1build1) ...
Setting up libvorbis0a:amd64 (1.3.7-1build2) ...
Setting up libvorbisfile3:amd64 (1.3.7-1build2) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libvorbisenc2_1.3.7-1build2_amd64.deb ...
De-configuring libvorbisenc2:i386 (1.3.7-1build1), to allow configuration of libvorbisenc2:am
d64 (1.3.7-1build1) ...
Unpacking libvorbisenc2:amd64 (1.3.7-1build2) over (1.3.7-1build1) ...
Preparing to unpack .../libvorbisenc2_1.3.7-1build2_i386.deb ...
Unpacking libvorbisenc2:i386 (1.3.7-1build2) over (1.3.7-1build1) ...
Preparing to unpack .../libshout3_2.4.5-1build3_amd64.deb ...
Unpacking libshout3:amd64 (2.4.5-1build3) over (2.4.5-1build2) ...
Setting up libshout3:amd64 (2.4.5-1build3) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../libsndfile1_1.0.31-2build1_amd64.deb ...
De-configuring libsndfile1:i386 (1.0.31-2), to allow configuration of libsndfile1:amd64 (1.0.
31-2) ...
Unpacking libsndfile1:amd64 (1.0.31-2build1) over (1.0.31-2) ...
Preparing to unpack .../libsndfile1_1.0.31-2build1_i386.deb ...
Unpacking libsndfile1:i386 (1.0.31-2build1) over (1.0.31-2) ...
Preparing to unpack .../python3-problem-report_2.20.11-0ubuntu80_all.deb ...
Unpacking python3-problem-report (2.20.11-0ubuntu80) over (2.20.11-0ubuntu79) ...
Setting up python3-problem-report (2.20.11-0ubuntu80) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../python3-apport_2.20.11-0ubuntu80_all.deb ...
Unpacking python3-apport (2.20.11-0ubuntu80) over (2.20.11-0ubuntu79) ...
Setting up python3-apport (2.20.11-0ubuntu80) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../xdg-desktop-portal_1.14.1-2_amd64.deb ...
Unpacking xdg-desktop-portal (1.14.1-2) over (1.14.1-1) ...
Setting up xdg-desktop-portal (1.14.1-2) ...
(Reading database ... 335248 files and directories currently installed.)
Preparing to unpack .../00-apport_2.20.11-0ubuntu80_all.deb ...
Unpacking apport (2.20.11-0ubuntu80) over (2.20.11-0ubuntu79) ...
Preparing to unpack .../01-dctrl-tools_2.24-3build2_amd64.deb ...
Unpacking dctrl-tools (2.24-3build2) over (2.24-3build1) ...
Preparing to unpack .../02-libfolks-eds26_0.15.5-2_amd64.deb ...
Unpacking libfolks-eds26:amd64 (0.15.5-2) over (0.15.4-1) ...
Preparing to unpack .../03-libfolks26_0.15.5-2_amd64.deb ...
Unpacking libfolks26:amd64 (0.15.5-2) over (0.15.4-1) ...
Preparing to unpack .../04-folks-common_0.15.5-2_all.deb ...
Unpacking folks-common (0.15.5-2) over (0.15.4-1) ...
Preparing to unpack .../05-intel-media-va-driver_22.2.1+dfsg1-1build1_i386.deb ...
De-configuring intel-media-va-driver:amd64 (22.2.1+dfsg1-1), to allow configuration of intel-
media-va-driver:i386 (22.2.1+dfsg1-1) ...
Unpacking intel-media-va-driver:i386 (22.2.1+dfsg1-1build1) over (22.2.1+dfsg1-1) ...
Preparing to unpack .../06-intel-media-va-driver_22.2.1+dfsg1-1build1_amd64.deb ...
Unpacking intel-media-va-driver:amd64 (22.2.1+dfsg1-1build1) over (22.2.1+dfsg1-1) ...
Preparing to unpack .../07-libayatana-appindicator3-1_0.5.90-7ubuntu2_amd64.deb ...
Unpacking libayatana-appindicator3-1 (0.5.90-7ubuntu2) over (0.5.90-7) ...
Preparing to unpack .../08-libetonyek-0.1-1_0.1.10-3build1_amd64.deb ...
Unpacking libetonyek-0.1-1:amd64 (0.1.10-3build1) over (0.1.10-3) ...
Preparing to unpack .../09-libfftw3-double3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-double3:amd64 (3.3.8-2ubuntu8) over (3.3.8-2ubuntu7) ...
Preparing to unpack .../10-libfftw3-single3_3.3.8-2ubuntu8_amd64.deb ...
Unpacking libfftw3-single3:amd64 (3.3.8-2ubuntu8) over (3.3.8-2ubuntu7) ...
Preparing to unpack .../11-libgtk-3-bin_3.24.33-1ubuntu1_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu1) over (3.24.32-0ubuntu1) ...
Preparing to unpack .../12-libmalcontent-0-0_0.10.4-1_amd64.deb ...
Unpacking libmalcontent-0-0:amd64 (0.10.4-1) over (0.10.3-1) ...
Preparing to unpack .../13-libmythes-1.2-0_2%3a1.2.4-4build1_amd64.deb ...
Unpacking libmythes-1.2-0:amd64 (2:1.2.4-4build1) over (2:1.2.4-4) ...
Preparing to unpack .../14-libodfgen-0.1-1_0.1.8-2build2_amd64.deb ...
Unpacking libodfgen-0.1-1:amd64 (0.1.8-2build2) over (0.1.8-2build1) ...
Preparing to unpack .../15-libvoikko1_4.3.1-1build1_amd64.deb ...
Unpacking libvoikko1:amd64 (4.3.1-1build1) over (4.3.1-1) ...
Preparing to unpack .../16-libwxbase3.0-0v5_3.0.5.1+dfsg-4_amd64.deb ...
Unpacking libwxbase3.0-0v5:amd64 (3.0.5.1+dfsg-4) over (3.0.5.1+dfsg-3) ...
Preparing to unpack .../17-libwxgtk3.0-gtk3-0v5_3.0.5.1+dfsg-4_amd64.deb ...
Unpacking libwxgtk3.0-gtk3-0v5:amd64 (3.0.5.1+dfsg-4) over (3.0.5.1+dfsg-3) ...
Preparing to unpack .../18-software-properties-common_0.99.21_all.deb ...
Unpacking software-properties-common (0.99.21) over (0.99.20) ...
Preparing to unpack .../19-python3-software-properties_0.99.21_all.deb ...
Unpacking python3-software-properties (0.99.21) over (0.99.20) ...
Setting up libvoikko1:amd64 (4.3.1-1build1) ...
Setting up libfftw3-single3:amd64 (3.3.8-2ubuntu8) ...
Setting up libetonyek-0.1-1:amd64 (0.1.10-3build1) ...
Setting up libgtk-3-bin (3.24.33-1ubuntu1) ...
Setting up apport (2.20.11-0ubuntu80) ...
apport-autoreport.service is a disabled or a static unit, not starting it.
Setting up python3-software-properties (0.99.21) ...
Setting up libayatana-appindicator3-1 (0.5.90-7ubuntu2) ...
Setting up intel-media-va-driver:amd64 (22.2.1+dfsg1-1build1) ...
Setting up intel-media-va-driver:i386 (22.2.1+dfsg1-1build1) ...
Setting up libvorbis0a:i386 (1.3.7-1build2) ...
Setting up aspell (0.60.8-4build1) ...
Setting up libfftw3-double3:amd64 (3.3.8-2ubuntu8) ...
Setting up libmythes-1.2-0:amd64 (2:1.2.4-4build1) ...
Setting up libwxbase3.0-0v5:amd64 (3.0.5.1+dfsg-4) ...
Setting up folks-common (0.15.5-2) ...
Setting up dctrl-tools (2.24-3build2) ...
Setting up libvorbisenc2:amd64 (1.3.7-1build2) ...
Setting up libvorbisenc2:i386 (1.3.7-1build2) ...
Setting up libodfgen-0.1-1:amd64 (0.1.8-2build2) ...
Setting up libmalcontent-0-0:amd64 (0.10.4-1) ...
Setting up software-properties-common (0.99.21) ...
Setting up libwxgtk3.0-gtk3-0v5:amd64 (3.0.5.1+dfsg-4) ...
Setting up libvorbisfile3:i386 (1.3.7-1build2) ...
Setting up libsndfile1:amd64 (1.0.31-2build1) ...
Setting up libsndfile1:i386 (1.0.31-2build1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for libglib2.0-0:i386 (2.72.0-1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.0-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Processing triggers for man-db (2.10.1-1) ...
Processing triggers for dbus (1.12.20-2ubuntu3) ...
Setting up nautilus-extension-gnome-terminal (3.44.0-1ubuntu1) ...
Setting up libfolks26:amd64 (0.15.5-2) ...
Setting up libfolks-eds26:amd64 (0.15.5-2) ...
Processing triggers for dictionaries-common (1.28.14) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...

**Comment by leviport** [comment]
For anyone else seeing this, you can also resolve it with:
```
sudo dpkg --configure -a
```
