### ISSUE TITLE
Workspaces interface does not show properly

### ISSUE THREAD

**Issue by Booligoosh** [pop-os/beta#358]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Upgraded to 22.04 from 21.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**
When opening the Workspaces view, the workspaces on the left side don't display properly, and appear shrunk (in this screenshot, I have 4 workspaces open):
![Screenshot from 2022-04-02 12-53-13](https://user-images.githubusercontent.com/14034891/161361112-67d6fa8f-5a10-4630-8c2a-4c6717ab2036.png)

**Steps to reproduce (if you know):**
1. Open the Workspaces view (by clicking Workspaces in the top bar, in the dock, or by swiping left with 4 fingers)
2. Observe that the workspaces on the left do not show properly

**Expected behavior:**
Workspaces show similar to 21.10, or whatever the intended design is for 22.04

**Other Notes:**

**Comment by leviport** [comment]
This might be fixed by https://github.com/pop-os/cosmic-workspaces/pull/56

**Comment by Booligoosh** [comment]
This has been resolved, thanks!
