### ISSUE TITLE
Workspace thumbnails not visible after boot.

### ISSUE THREAD

**Issue by derpmatt** [pop-os/beta#359]
updated to 22.04 from 21.10 using `pop-upgrade release upgrade -f` before the beta was officially available - maybe 10 days before. I have all the latest updates daily. 
 
`pop-desktop` `1.6.0~1648768891~22.04~a3eee7d`
`gnome-shell` `42~beta-1ubuntu2~1648768011~22~242d2f9`
It has been doing this for several days and through updates though.

**Issue/Bug Description:**
When booting or rebooting Pop!_OS 22.04 the workspace thumbnails are not visible when pressing super. I have the super key selected to do that in Settings. 
I have this machine set up with 4 static workspaces, and they are there and usable with ctrl + super + arrow (down/up). However, the thumbnails aren't visible. (See pics)
There is a strange little orange dot appears on the top left of the desktop. (See pics)
Alt + F2, `r` (restarting shell) fixes the problem. Workspace thumbnails are visible for the rest of the session. Do a reboot though and they are gone again. 

~~I've been looking at and following logs for three days and I cannot see anything that seems relevant, neither is there anything that is changed in `journalctl -f` when restarting shell. Maybe some guidance on what to supply for this?~~

EDIT: It is still happening after today's updates. Here is a log from what happens in `journalctl -f` immediately when I use Alt + F2, `r`. 

https://gist.github.com/derpmatt/087526eadf021d6f6352e2e38a918028

I see `[VERTICAL-OVERVIEW] starting overrides` isn't being called at startup then?

**Steps to reproduce (if you know):**
Boot the OS, press super (or super + d).

**Expected behavior:**
Workspace thumbnails should be visible when pressing super (or super + d) after the display is visible.

**Other Notes:**
Missing thumbnails at boot
![workspace-missing](https://user-images.githubusercontent.com/49352270/161362855-0d548bd5-1a18-4a90-a01a-3baac1c497a5.png)

Appear after restarting shell
![restart-shell](https://user-images.githubusercontent.com/49352270/161362867-20194088-a701-43dd-a5b9-156290be45d9.png)

**Comment by leviport** [comment]
Looks like this may be a duplicate of https://github.com/pop-os/beta/issues/358

I believe https://github.com/pop-os/cosmic-workspaces/pull/56 may be a fix

**Comment by derpmatt** [comment]
Things got much worse before they got better, but this does seem to be fixed now. 
The last three days I completely lost the dock, workspaces, launcher, tiling and had no focused window. I was updating via TTY4 everyday. It came good tonight and seems better than ever.  I think this can be closed.
