### ISSUE TITLE
22.04 doesn't boot properly on QEMU

### ISSUE THREAD

**Issue by manyet1k** [pop-os/beta#364]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Fresh install on a VM
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

The issue is not related to a specific application/package.

**Issue/Bug Description:**
When I tried installing 22.04 Beta with full disk encryption on a QEMU KVM user session on virt-manager, the initial system installation works fine, but after rebooting to continue installing, the system gets stuck on either a black screen or a prompt that does nothing. This happens on all the firmware options available (BIOS, UEFI OVMF_CODE.ms.fd, UEFI OVMF_CODE.secboot.fd, UEFI OVMF_CODE.fd)
When I tried installing without encryption (on UEFI OVMF_CODE.fd), I could get past the first reboot, but after installing the updates over Pop!_Shop and clicking on reboot to apply, I got stuck at a useless prompt after seeing the systemd text: 
![image](https://user-images.githubusercontent.com/65016459/161429190-872a7a7f-e787-4c52-ab8d-cac942cfbb23.png)
I tried doing the same on GNOME Boxes, which uses BIOS, and I realized that rebooting works fine until you install the updates. My host system has a Ryzen 9 5900HX with Pop!_OS 20.04.

**Steps to reproduce (if you know):**
1- Install the Intel graphics ISO on a QEMU KVM virtual machine with arbitrary options. Then, either:
2- Install the system with full disk encryption
3- It's not possible to boot again
Or:
2- Install the system w/o full disk encryption
3- Install the updates using apt or Pop!_Shop
4- It's not possible to boot again

**Expected behavior:**
If encryption is enabled, the installer should ask for the password after the first boot. If it isn't, you should be able to run apt upgrade without breaking your system.

**Other Notes:**
None right now

**Comment by tur1ngb0x** [comment]
Can confirm here as well

**Details:**
* Distro: Fedora 36 Pre-release Cinnamon
* App: GNOME Boxes 42.0 Stable Branch via Flatpak 1.12.7
* VM: PopOS 22.04 Beta Intel ISO + 2 CPUs + 2GB RAM + 20GB + SeaBIOS

**Steps to reproduce:**
1. Install PopOS using entire disk on GNOME Boxes.
2. Boot into the installed PopOS.
3. As a root user: `apt update && apt upgrade`
4. Reboot
5. The display hangs at the boot log for around 4-5 seconds followed by an infinite blank screen with a blinking cursor.
6. TTY is still accessible.

**Screenshots:**
* To fit everything on the guest display, I had to change the TTY font to VGA 8x16.
* ![Screenshot from 2022-04-03 19-06-27](https://user-images.githubusercontent.com/25666761/161431318-08507df6-a360-4eb1-a9fb-49d1502adc96.png)
* ![Screenshot from 2022-04-03 19-06-39](https://user-images.githubusercontent.com/25666761/161431339-af3f5284-4a51-446f-b1c5-25f5159918dc.png)



**Logs:**

* `cat /var/log/apt/history.log`: https://termbin.com/bpqn
* `cat /var/log/apt/term.log`: https://termbin.com/0enj
* `cat /var/log/boot.log`: https://termbin.com/yqyz
* `dmesg`: https://termbin.com/4qxd
* `journalctl -p0..6 -xb --no-pager`: https://termbin.com/rb14

**Comment by manyet1k** [comment]
I've tried running the beta on Oracle VirtualBox and it worked fine, even with disk encryption and after installing updates over Pop!_Shop.

**Comment by snrkl** [comment]
Has the second beta release made any changes that might address this bug? (ie: is it worthwhile downloading and re-testing if using QEMU as at 2022-04-11?)

**Comment by manyet1k** [comment]
Thanks for letting me know that there is a second beta release, but unfortunately things still don't work on my side. Now, the installer won't even boot, let alone the OS itself. The installation media gets stuck at this screen for a while:
![image](https://user-images.githubusercontent.com/65016459/163024567-70107304-0324-4e74-9aea-6a3ab2a42075.png)
After 20-30 seconds, an empty useless shell, just like the one @tur1ngb0x and I shared above, appears.

**Comment by M-Mabrouk1** [comment]
still the same issue uefi or bios won't boot on qemu.

**Comment by snrkl** [comment]
Tried ISO 3 - failed trying to set AU keyboard layout:

```
[INFO distinst:src/installer/steps/configure/chroot_conf.rs:291] configuring keyboard layout
[INFO distinst:crates/chroot/src/command.rs:109] running "chroot" "/tmp/distinst.SNdJ9WfRBKFK" "localectl" "set-x11-keymap" "au" "" ""


[ERROR distinst:src/installer/state.rs:37] configuring chroot error: error setting keyboard layout: command failed with exit status: exit status: 1
[ERROR distinst:src/installer/mod.rs:300] errored while installing system: error setting keyboard layout: command failed with exit status: exit status: 1
[INFO distinst:ffi/src/installer.rs:188] Install error: error setting keyboard layout: command failed with exit status: exit status: 1
```
Full install log attached..
[installer.log](https://github.com/pop-os/beta/files/8546672/installer.log)

**Comment by 13r0ck** [comment]
I have been able to get pop to fun in a QEMU VM (using gnome-boxes), using a new ISO. Can anyone confirm?

**Comment by n3m0-22** [comment]
@13r0ck I was able to install 22.04 in QEMU VM (gnome-boxes), but with some caveats. It will only install with legacy bios. Encryption needs to be disabled, or it breaks after updating the kernel to 5.17.5. Otherwise it works fine. If that is ok this issue can be closed.

**Comment by 13r0ck** [comment]
@n3m0-22 hmm I didnt have to do any of that. Was your template "Unknown OS", or "Ubuntu"? How much ram and storage did you allocate to the system? Did you use ISO 6 or debug ISO 82?

**Comment by n3m0-22** [comment]
Template was "Unknown OS" I couldn't get it to boot with "Ubuntu". I gave it 16GB of RAM and 40GB of storage. I used pop-os_22.04_amd64_intel_5.iso. I'm downloading the 82 debug right now. I double check with that.

**Comment by n3m0-22** [comment]
@13r0ck I was able to get it running with debug 82 as well. I also got it running with the 5 iso, and was able to update to the new kernel. Both with encryption enabled. The one issues I still see is it never boots to Plymouth on its own. I either need to bring up GRUB and select Pop, or I can hit `Del` after waiting a bit and that takes me to a prompt where I can decrypt from. I can also use `Crtl`+`Alt`+`Up` from there to decrypt from the regular Plymouth screen. I would say that it is working, but booting is a little finicky.

**Comment by manyet1k** [comment]
I could run the 9 ISO on virt-manager. I picked the Ubuntu 22.04 OS and UEFI x86_64: /usr/share/OVMF/OVMF_CODE_4M.fd firmware with 8 gigs of RAM, 8 CPU cores and ~25 gigs of storage, and I enabled full disk encryption. Though, the disk encryption key prompt doesn't appear or appears after a long delay. In that case, you can just blindly type in the key to the black screen and hit enter.

I think it's OK to close this issue, I'll open another one in pop-os/pop to report about the encryption key problem.
