### ISSUE TITLE
Only a blank window, no lockscreen after suspend 

### ISSUE THREAD

**Issue by realKarthikNair** [pop-os/beta#367]
### **Upgrade**
- Upgraded from 21.10
 
### **Issue**

- **waking from suspend leaves a blank window with status bar instead  of a proper lockscreen with password input**

- Image attached at bottom

### **Steps to reproduce**

1. suspend
2. Try to Unlock => but there's no Password input screen
3. **Blindly Click on the Center => Put in password => Hit enter => Boom! unlocked**

> Update: I can't reproduce it every single time, but the frequency isn't rare

### **Expected behavior:**

Lockscreen => Password input window => put in password => unlock

### **Other Notes:**

**Blindly Clicking on the Center => Put in password => Hit enter => Unlocks!!!!**

Edit: **After this blind unlocking workaround, every followup suspends just work fine with proper lockscreen and password input**

![WhatsApp Image 2022-04-03 at 9 02 37 PM](https://user-images.githubusercontent.com/78267371/161435595-3fce2135-e952-4bc9-a5d4-72935f3be4c4.jpeg)

**Comment by realKarthikNair** [comment]
**After this blind unlocking workaround, every followup suspends just work fine with proper lockscreen and password input**

**Comment by linuxgnuru** [comment]
Could you provide what hardware your Asus VivoBook runs?

**Comment by Seibz** [comment]
Is this a Ryzen 5000 series system, and what sort of memory is it using?

**Comment by realKarthikNair** [comment]
> Could you provide what hardware your Asus VivoBook runs?

> Is this a Ryzen 5000 series system, and what sort of memory is it using?

@linuxgnuru @Seibz 

```
karthik@cosmic:~$ sudo inxi -MmSC
System:
  Host: cosmic Kernel: 5.16.15-76051615-generic x86_64 bits: 64
    Console: pty pts/1 Distro: Pop!_OS 22.04 LTS
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X421IAY_M413IA
    v: 1.0 
    UEFI: American Megatrends v: X421IAY.311 date: 10/26/2021
Memory:
  RAM: total: 7.25 GiB used: 2.23 GiB (30.8%)
  Array-1: capacity: 32 GiB slots: 2 EC: None
  Device-1: DIMM 0 size: 4 GiB speed: 3200 MT/s
  Device-2: DIMM 0 size: 4 GiB speed: 3200 MT/s
CPU:
  Info: 6-core model: AMD Ryzen 5 4500U with Radeon Graphics bits: 64
    type: MCP cache: L2: 3 MiB
  Speed (MHz): avg: 1562 min/max: 1400/2375 cores: 1: 1400 2: 1400 3: 2375
    4: 1400 5: 1400 6: 1400

```

**Comment by linuxgnuru** [comment]
We have narrowed the issue down to AMD with integrated graphics when suspending for the first time.  The lock screen is there just hidden; if you hit 'Enter' and then type in the password and again hit enter you can log in.  Going to continue testing to see if we can get more information.

**Comment by realKarthikNair** [comment]
@linuxgnuru please read my issue description again, I've already mentioned that it's still unlockable

```Other Notes:
Blindly Clicking on the Center => Put in password => Hit enter => Unlocks!!!!```

**Comment by realKarthikNair** [comment]
Thank you so much

**Comment by linuxgnuru** [comment]
On further research we found that on resume tty1 was getting the focus and not tty2 where the lock screen is.  Tty1 being controlled by gdm3 for switching users.

**Comment by realKarthikNair** [comment]
Sure thing once i get time. Will report back soon.

**Comment by realKarthikNair** [comment]
@linuxgnuru it did work to get back to the lockscreen but there's a catch: after being unlocked, the display goes blank after 3-4 seconds; it gets restored on any user input though; without showing the lockscreen again ofcourse

**Comment by linuxgnuru** [comment]
I'm attaching journalctl logs of an Intel and AMD computer for comparison of the VT not switching back from VT 1 to VT 2.  The two lines that might be of use that only appear in the AMD logs are:

```
Apr 15 06:58:15 pop-os /usr/libexec/gdm-x-session[2862]: (II) AMDGPU(0): AMDGPULeaveVT_KMS
Apr 15 06:58:15 pop-os /usr/libexec/gdm-x-session[2862]: (II) AMDGPU(0): Ok, leaving now...
```

[journal-intel.log](https://github.com/pop-os/beta/files/8496953/journal-intel.log)

[journal-amd.log](https://github.com/pop-os/beta/files/8496954/journal-amd.log)

**Comment by Seibz** [comment]
This may have been fixed. Please run updates and reboot, letting us know if those updates help:
```
sudo apt clean | tee -a ~/updates.txt

sudo apt update -m | tee -a ~/updates.txt

sudo dpkg --configure -a | tee -a ~/updates.txt

sudo apt install -f | tee -a ~/updates.txt

sudo apt full-upgrade | tee -a ~/updates.txt

sudo apt autoremove --purge | tee -a ~/updates.txt

sudo apt install pop-desktop gdm3 | tee -a ~/updates.txt 

flatpak update --appstream

flatpak repair --user

sudo flatpak repair --system

flatpak update

flatpak uninstall --unused
```
After running those, send us your updates.txt log file if you're still having issues.

**Comment by linuxgnuru** [comment]
Yeah, on Kudu after updates it looks like this has been fixed. @realKarthikNair  could you run updates and test?

**Comment by realKarthikNair** [comment]
@Seibz @linuxgnuru I don't have access to that machine temporarily. Will report back as soon as I have.

**Comment by realKarthikNair** [comment]
@Seibz @linuxgnuru Yep it seems fixed! Thank you so much... WIll observe few more hours and close the issue.

Thanks again!
