### ISSUE TITLE
Pop! OS 22.04 beta crashes during install

### ISSUE THREAD

**Issue by theunclemez** [pop-os/beta#368]
I proceed with Fresh install on VM create on KVM 
 
**Issue/Bug Description:**
Here you'll find the installer log file that may help understand what happened
https://paste.opensuse.org/11288379 

**Steps to reproduce (if you know):**
Just try install fresh and it will crash, now 3 times doing the same

**Expected behavior:**
should work without problem

**Comment by manyet1k** [comment]
22.04 on KVM is problematic, even if you manage to install (which I did) the system [won't boot](https://github.com/pop-os/beta/issues/364) after enabling encryption or installing updates.

**Comment by leviport** [comment]
Thanks for helping test the beta! I think this might be the same issue as https://github.com/pop-os/beta/issues/364
