### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring

### ISSUE THREAD

**Issue by matilde-t** [pop-os/beta#376]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Upgraded from 21.10 to 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

I am not sure what to write here, apt is

apt:
  Installed: 2.4.3
  Candidate: 2.4.3
  Version table:
 *** 2.4.3 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

When i run `sudo apt update` I see

W: http://apt.pop-os.org/proprietary/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://apt.pop-os.org/release/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Steps to reproduce (if you know):**

Run `sudo apt update`

**Expected behavior:**

Not to see this warning message

**Other Notes:**

I tried to read apt-key(8) but it seems to me it's more developers' stuff rather than users' stuff

**Comment by borfast** [comment]
Hopefully it's OK to bring this issue back to life. I can't find anything anything else online and this does seem to be the same issue. 

What would be the steps to take to fix this manually? I am on 22.04, installed from scratch some time ago, not an upgrade, and it still seems to be using a key in `/etc/apt/trusted.gpg`.

I tried exporting the key into `/etc/apt/trusted.gpg.d/pop_os.gpg` and modifying `/etc/apt/sources.list.d/pop-os-apps.sources` and `/etc/apt/sources.list.d/pop-os-release.sources` to include a line `Signed-By: /etc/apt/trusted.gpg.d/pop_os.gpg` but as soon as I deleted the key from `/etc/apt/trusted.gpg`, APT started complaining that "the public key is not available: NO_PUBKEY 204DD8AEC33A7AFF"

Any hints as to what I may be missing?


EDIT: problem solved. After I ran `sudo apt update`, `/etc/apt/trusted.gpg.d/pop_os.gpg` was being automatically moved to `/etc/apt/trusted.gpg.d/pop_os.gpg~`. I was exporting the key to that directory assuming it would be the right place for system keys, but apparently APT doesn't like it for some reason. Instead, I used the third-party keys directory `/etc/apt/keyrings/`, modified the .sources files accordingly, and APT doesn't complain anymore. :partying_face:
