### ISSUE TITLE
typelib Adw missing for extensions set for gnome 42

### ISSUE THREAD

**Issue by cryptic3481** [pop-os/beta#377]
Fresh install of 22.04 Beta.  
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Extensions like "User Themes" or "ArcMenu". And possibly more.

**Issue/Bug Description:**
In particular to ArcMenu; 

Error: Requiring Adw, version none: Typelib file for namespace 'Adw' (any version) not found

```
@/home/user/.local/share/gnome-shell/extensions/arcmenu@arcmenu.com/prefs.js:4:56
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:216:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:175:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Steps to reproduce (if you know):**

Hit up gnome extensions, install ArcMenu. It'll install, but will not allow you to change settings. Functions enough to create a menu. Attempting to change the settings will provide that message above. 

**Other Notes:**

Already reached out to creator of the extension. I got a response with;

"Starting with GNOME 42, all extension settings now use Adw (LibAdwaita) to create their preferences window."

"maybe they haven't included the Adw package yet?"

Which makes complete sense after finding other various extensions also having the same Adw issue.

**Comment by jackpot51** [comment]
We do not support libadwaita at this time.

**Comment by jackpot51** [comment]
libadwaita preferences extensions are supported in Pop!_OS 22.04 now.
