### ISSUE TITLE
The system76-power is disabled by default in extensions.

### ISSUE THREAD

**Issue by vancanhuit** [pop-os/beta#38]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh install from ISO.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
NONE.

**Issue/Bug Description:**
The `system76-power` is disabled by default on a clean installed system when opening `extensions` application.

**Steps to reproduce (if you know):**
Download the ISO and install a fresh system.

**Expected behavior:**
The `system76-power` should be enabled by default on a clean install when opening `extensions` application.

**Other Notes:**
NONE.

**Comment by WatchMkr** [comment]
This now appears fixed. Please re-open if necessary.
