### ISSUE TITLE
screen tearing when pressing super

### ISSUE THREAD

**Issue by tuananh** [pop-os/beta#380]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
it looks like this when i press super

i'm using wayland btw.

TODO: reupload image 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

press meta

**Expected behavior:**

launcher is launched and focused

**Other Notes:**

**Comment by cryptic3481** [comment]
just a suggestion, but I'd blur the contact info you dropping in that image.

**Comment by tuananh** [comment]
seems like it's fixed
