### ISSUE TITLE
First resume from suspend after booting takes user to the GDM3 login screen instead of the lock screen

### ISSUE THREAD

**Issue by leviport** [pop-os/beta#382]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Perhaps GDM3? 
`42.0-1ubuntu1pop0~1648760425~22.04~098263d`

**Issue/Bug Description:**
After a reboot or cold boot, the first time I suspend the machine and then resume, I see the lock screen briefly, but then get taken back to the GDM3 login screen. When I log in, my current session and the windows I had open still seem to be preserved, though.

Subsequent suspends and resumes take me to the lock screen, as I would expect.

**Steps to reproduce (if you know):**
1. Boot the machine, or reboot it if it's already running
2. Log in and open any application
3. Suspend
4. Resume
5. You should see the normal lock screen flash briefly, then the gray GDM3 login screen will show up
6. Signing in at the login screen should return you to your session, and the application you had open should still be open.

**Expected behavior:**
First suspend and resume should show the lock screen, not the login screen

**Other Notes:**

**Comment by realKarthikNair** [comment]
Almost same thing being faced by me too: https://github.com/pop-os/beta/issues/367

**Comment by leviport** [comment]
Fixed by https://github.com/pop-os/gdm3/pull/17
