### ISSUE TITLE
workspaces overview doesnt show

### ISSUE THREAD

**Issue by Linuxbeta** [pop-os/beta#383]
updated yesterday to 22.04 from 21.10 using pop-upgrade release upgrade -f . After upgrade when i click on the workspaces button the workspaces don't appear on the desktop, but the workspaces view seems to open. It is not possible to close this view.

![Screenshot from 2022-04-07 14-07-11](https://user-images.githubusercontent.com/103190070/162195011-a1b77838-b93e-41b8-bdfa-216485c78f5d.png)

Alt + F2, r (restarting shell) fixes the problem, this means, it is possible to use the desktop again.

**Comment by leviport** [comment]
Thank you for helping test the beta! We're currently tracking this bug here: https://github.com/pop-os/cosmic-workspaces/issues/59
