### ISSUE TITLE
Custom-set wallpaper changes after upgrading to 22.04

### ISSUE THREAD

**Issue by leviport** [pop-os/beta#389]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Upgrade from 21.10
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-session

**Issue/Bug Description:**
If I set a custom wallpaper in 21.10 and then upgrade to 22.04, my wallpaper will be set to the default dark mode wallpaper after the upgrade.

**Steps to reproduce (if you know):**
- Install 21.10
- Set custom wallpaper
- `pop-upgrade release upgrade -f`

**Expected behavior:**
Custom set wallpaper should remain the same

**Other Notes:**
I think this probably came from https://github.com/pop-os/session/pull/52 and happens because having different wallpapers between light and dark mode is a new feature on 22.04. If I change my theme to light mode, my wallpaper changes back to the custom wallpaper I had set before the upgrade.

**Comment by n3m0-22** [comment]
Confirmed that this is still an issue.

**Comment by n3m0-22** [comment]
Fixed with https://github.com/pop-os/default-settings/pull/136#pullrequestreview-948909734
