### ISSUE TITLE
Unreadable text in Power Statistics, under dark theme.

### ISSUE THREAD

**Issue by briggs1978** [pop-os/beta#39]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-power-manager:
  Installed: 3.32.0-2
  Candidate: 3.32.0-2
  Version table:
 *** 3.32.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
When using the dark theme, the Y Axis label in the power history is too dark to read.

![Screenshot from 2020-04-17 22-26-31](https://user-images.githubusercontent.com/3167458/79626637-90a57600-80ff-11ea-84d3-d1a7ed474e20.png)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by isantop** [comment]
This appears to be a completely custom-drawn widget, so it may not be possible to fix this in the theme. The same problem occurs in Adwaita-dark.

**Comment by briggs1978** [comment]
I guess System76 will just have to make their own power history tool (only mostly kidding).
Thanks for the reply, I'll try reaching out to the package maintainer.
