### ISSUE TITLE
Autologin doesn't work

### ISSUE THREAD

**Issue by Linuxbeta** [pop-os/beta#394]
When automatic login on start-up is selected on pop!_OS 22.04 beta, the pc doesn´t automatically login on start-up. Can you please fix this, so the pc will automatically login on start-up? Thanks! 

![Screenshot from 2022-04-13 10-46-23](https://user-images.githubusercontent.com/103190070/163137513-ee34c06e-9c34-4dd8-a1a2-12bb6ad19b70.png)

**Comment by 13r0ck** [comment]
I am unable to reproduce this. Did you install from the latest iso, and are all updates installed?

**Comment by xploz1on** [comment]
> I am unable to reproduce this. Did you install from the latest iso, and are all updates installed?

Same here. My wife's laptop does Auto login every time.

**Comment by 13r0ck** [comment]
Please provide more information.

**Comment by Linuxbeta** [comment]
I upgraded from 21.10 to 22.04 a week ago and have all updates installed.
Just checked again this morning. It seems that it only asks for a login
when the screen is turned off. Didn´t know for sure if I had this issue
with 21.10 or not, but I don´t think so, because I only noticed it since
the upgrade to 22.04.

Just checked my screen settings, but I have turned all automatic screen
lock etc. off, see attached print screen:

[image: image.png]

Does this help as additional information?


Op do 14 apr. 2022 om 04:02 schreef Brock ***@***.***>:

**Comment by Linuxbeta** [comment]
@leviport I only seem to have this issue when turning my pc on, and turning my screen on (or switch the input from my screen) to my pc. When I let my pc on and turn off my screen, while later turning on my screen, the issue don't occur. 

Regarding the immage: it was a screenshot of the settings menu, under 'privacy' and submenu 'screen', in which you can see that the automatic screen lock is disabled.

**Comment by xploz1on** [comment]
![Screenshot from 2022-04-15 00-03-04](https://user-images.githubusercontent.com/13008386/163516341-285fb88d-077d-4351-b3d3-51c882f953f8.png)
 So your settings looks something like that? And still after switching screen input or for example moving your mouse with the screen off it does ask for password? Does it ask for password too when turning PC on?
Trying to understand if its happening on all situations or just after a black screen (screen off)

**Comment by Linuxbeta** [comment]
It looks like that, only the option 'blank screen delay' is set to 'never´ and 'lock screen on suspend' is also turned off, see:

![image](https://user-images.githubusercontent.com/103190070/163529947-03d9d375-84b8-4e24-88b0-439b2fa4a414.png)


The problem does only occur when I boot my PC and have the screen off, or have another input then my pc on my screen when booting my PC. The problem does not occur when I'm logged in after booting, or when I have the screen on during booting and I turn my screen off after the PC fully booted.

**Comment by Linuxbeta** [comment]
It seems the latest updates have fixed the problem. Thanks!
