### ISSUE TITLE
Pop!_Shop crashes when updating gnome-remote-desktop on Operating System Updates.

### ISSUE THREAD

**Issue by AliCoded** [pop-os/beta#399]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Upgrade (from 21.10)

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Shop (io.elementary.appcenter)

**Issue/Bug Description:**
I tried to update through the Pop!_Shop because there were updates available (under the Installed section) but when I update the gnome-remote-desktop package on the Pop!_Shop, the software crashes.

**Comment by AliCoded** [comment]
When I type `sudo apt upgrade -y,` this is what I get:
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gnome-remote-desktop
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
`

**Comment by xploz1on** [comment]
Is not really an error per say. If the dependencies of an installed package have been changed such that it requires installation of new packages, the installed package won’t be upgraded with the system update and you’ll see package kept back error.
Try 
```sh
 sudo apt update && sudo apt full-upgrade -y
```

That should take care of installing new dependencies. And fix the gnome-remote-desktop package held back. Let us know!
