### ISSUE TITLE
Right ALT not working - darp6

### ISSUE THREAD

**Issue by rchdz** [pop-os/beta#4]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Fresh 19.10, updated, restarted, pop-upgrade command

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
The right ALT key on darp6 no longer functions after updating to 20.04 beta. The left continues to function normally.

**Steps to reproduce (if you know):**
Update to 20.04 beta on darp6 (S76 Darter Pro v6), try to use right ALT key combos

**Expected behavior:**

**Other Notes:**

**Comment by WatchMkr** [comment]
@brs17 @leviport can you guys verify this?

**Comment by rchdz** [comment]
@WatchMkr Actually this seems to have been resolved with a recent package update. Unsure which, exactly, but both ALT keys are working as expected now since updating the beta (apt upgrade).

**Comment by leviport** [comment]
It's working on the darp6 I have, so it must've been fixed. Thanks for the report!
