### ISSUE TITLE
Default mic level for laptop's built-in mic is quite a bit higher than it should be

### ISSUE THREAD

**Issue by leviport** [pop-os/beta#400]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Clean install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Maybe gnome-control-center?

**Issue/Bug Description:**
After install, the mic input level is set way up near 80%, which is way higher than it needs to be for most laptops. I usually set mine between 20% and 30% on my oryp6 and darp5.
![Screenshot from 2022-04-15 18-55-47](https://user-images.githubusercontent.com/13512097/163621576-10996113-d5d3-476f-ac12-8552270725a7.png)

**Steps to reproduce (if you know):**
1. Fresh install
2. Check Settings > Sound > Input volume

**Expected behavior:**
Default input level for built-in mic should be around 20%-30%

**Other Notes:**

**Comment by xploz1on** [comment]
This is correct. If you dont check the level before doing a call you might end up blowing some people ears.
Setting the default level at 10% should be fine.
