### ISSUE TITLE
Unable to install with custom partitioning.

### ISSUE THREAD

**Issue by zaphod80013** [pop-os/beta#403]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Fresh Custom install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Installer

**Issue/Bug Description:**

Attempting to experiment with btrfs root filesystem.  Had previously done a clean default install, rebooted to install media, manually wiped the luks header with dd, created a new disk label (gpt) and recreated partitions using same sizes as the default install,  manually formated nvme0np3 as a luks container. rebooted and reran the installer selecting  Custom partitioning.

Attempted to unlock the luks container in order to create VG & Root LVM got following error.

Decryptyion Error: The decrypted volume does not have a LVM partiton on it.

**Steps to reproduce (if you know):**

Run installer with custom partitioning
Create a layout comparable to the default install
Manually format nvme0n1p3 as luks container. 
reboot
Attempt install with custom partitioning
Attempt to unlock Luks container

**Expected behavior:**

I should be able to perform an encrypted install with custom partitioning.

**Other Notes:**

**Comment by mmstick** [comment]
Btrfs isn't compoatible with LVM unfortunately. There's a btrfs root default PR at https://github.com/pop-os/distinst/pull/286
