### ISSUE TITLE
Icons have black box around them in Top Bar

### ISSUE THREAD

**Issue by Booligoosh** [pop-os/beta#405]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 Upgraded from 21.10

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Some icons in the Top Bar have a black box surrounding them as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/14034891/163751241-6cafd783-dc9e-45a5-87f4-98b2f2edd5c7.png)

**Steps to reproduce (if you know):**
- The issue occurs in both light theme and dark theme. The black boxes are obviously easier to notice when using a light background.

**Expected behavior:**
There shouldn't be black boxes around the icons.

**Other Notes:**

**Comment by linuxgnuru** [comment]
Do you have any gnome extensions to change the top bar's color?

**Comment by linuxgnuru** [comment]
issue is with gnome-shell extension and / or gnome 42 and not with pop
