### ISSUE TITLE
Changing refresh rate in Display Settings crashes the display

### ISSUE THREAD

**Issue by masterteapot** [pop-os/beta#406]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 Upgrade 21.10 to 22.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

NA

**Issue/Bug Description:**
Changing refresh rate from 144 to 60 crashes the display

**Steps to reproduce (if you know):**
- Set power mode to "performance" 
- Go to settings -> display 
- Change refresh rate from 144 to 60

**Expected behavior:**
To change the refresh rate without crashing the display

**Other Notes:**
When this happens I can see my cursor but nothing else
The screen is totally black apart from my cursor
Waiting does not bring back the previous settings and display
I have to force shutdown my system and reboot to get my display back (settings will not have changed, they will still be on 144 hz)

**Comment by linuxgnuru** [comment]
What monitor (make/model) are you using and what GPU / drivers?

**Comment by masterteapot** [comment]
**Monitor**
- Built in monitor on laptop
- Make/model: Razer Blade 15 - Base Model Early 2020
- It is the 144hz 1080p ips panel

**GPU**
- Nvidia geforce rtx 2070 mobile (super)

**Graphics Drivers**
- 510.60.02

**Comment by Seibz** [comment]
If you switch to 470 are you seeing this anomaly?
I wonder if a dmesg output would help @linuxgnuru out here too.

**Comment by mmstick** [comment]
Is that still an issue after the release?

**Comment by masterteapot** [comment]
Hello,  I am no longer experiencing this bug.
