### ISSUE TITLE
Firefox right click issue

### ISSUE THREAD

**Issue by jtsagata** [pop-os/beta#407]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
From previous version
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
firefox:
  Installed: 99.0~1649269630~22.04~d0ebb49
  Candidate: 99.0~1649269630~22.04~d0ebb49
  Version table:
     1:1snap1-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
 *** 99.0~1649269630~22.04~d0ebb49 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Right click and select text to clipboard issue

**Steps to reproduce (if you know):**
Try to right click or select text. Firefox hangs

**Other Notes:**
Try it with and without a clipboard manager and in a private mode. Flathub works.

**Comment by linuxgnuru** [comment]
What sites did you test with?

**Comment by n3m0-22** [comment]
Firefox has since been updated, and I'm unable to recreate this issue. I'm closing it, but we can always reopen if you continue to have problems.
