### ISSUE TITLE
Issues with no audio inputs or outputs

### ISSUE THREAD

**Issue by SanderBlom** [pop-os/beta#409]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 Upgraded from 21.10 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`sander@pop-os:~$ sudo apt policy pipewire
pipewire:
  Installed: 0.3.48-1ubuntu1
  Candidate: 0.3.48-1ubuntu1
  Version table:
 *** 0.3.48-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
sander@pop-os:~$ `

**Issue/Bug Description:**

Since upgrading to 22.10 beta I have experienced a lot of issues with the audio not working as intended on my Thinkpad t14 gen 1 (AMD). Some times the speakers and microphone works great and other times they are detected but no audio is outputted. 

After an update yesterday there are no outputs or inputs in the audio settings. I've tried to reboot multiple times without success.

Maybe this is useful? 

`sander@pop-os:~$ sudo dmesg | grep audio
[    9.942095] snd_hda_intel 0000:07:00.1: Handle vga_switcheroo audio client
[    9.950022] snd_hda_intel 0000:07:00.1: bound 0000:07:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
`

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
Check that the pipewire service isn't masked. Or if it works from another user account

**Comment by SanderBlom** [comment]
This issue seems to have improved drastically after upgrading to the stable 22.04 release
