### ISSUE TITLE
Automatic time zone switch from PDT (accurate) to MDT (inaccurate)

### ISSUE THREAD

**Issue by juanejot** [pop-os/beta#410]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Upgrade from 21.10 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Unknown; perhaps tzdata?

**Issue/Bug Description:**
Upon first reboot into 22.04 beta system, it informed me my time zone had been updated to MDT (that of Boise, it stated; and I assume that of System76 in Colorado). I'm not in MDT; I'm in PDT. Location services are on, but I don't see any particular output of where it thinks I am. Weather websites such as windy.com & darksky.net load my correct city without intervention. If I manually select PDT inside the Date & Time pane of Settings, the time zone works as expected. But any time I tumble the switch to Automatic, it informs me once again that I've switched to MDT.

**Steps to reproduce (if you know):**
As above.

**Expected behavior:**
That my time zone wouldn't change from PDT.

**Other Notes:**
`sudo dpkg-reconfigure tzdata` does fix it. The Time & Date pane of the Settings app shows PDT but Boise before being closed, but Los Angeles & PDT upon being closed/opened.
This fix does not survive a reboot, which only tumbling the "Automatic Time Zone" switch to "off" & keeping it that way, persistently does.

**Comment by n3m0-22** [comment]
I'm seeing a similar issue. I think the timezone is shifting over one.

Steps to reproduce
1. Fresh install of 22.04
2. Tick Location Services on
3. Select your timezone
4. Complete Gnome Initial Setup
5. Timezone shifts (for me from MDT to MST) setting me one hour behind

I have checked against IP Geolocation sites as well as weather sites, and it correctly finds the city I'm in. It is the automatic timezone setting that is off.

**Comment by juanejot** [comment]
This bug is still present in 22.04 final.

**Comment by juanejot** [comment]
~~This bug appears to be fixed as of 4/26 in 22.04 final (though I'm unsure which update did it, as I've been tinkering with other OSes and issues since then). Closing as fixed, anyway.~~

**Comment by juanejot** [comment]
Scratch the above comment & issue closure: While this issue appears to have been fixed on my old IC2D-T9900/NVidia9400M/9600MGT laptop, it is still active and un-fixed--in 22.04 final--on my i7-9700K/RX6600XT desktop; re-opening this issue.

**Comment by mmstick** [comment]
Potentially fixed by https://github.com/pop-os/gnome-settings-daemon/pull/14

**Comment by 13r0ck** [comment]
@juanejot https://github.com/pop-os/gnome-settings-daemon/pull/14 was released. Please update your system. Is the issue fixed for you?

**Comment by juanejot** [comment]
Sorry, had been tracking some other issues on that & other systems; yes, fixed! Closing.

(And thank you!)
