### ISSUE TITLE
Pop Shop not working well with gtk themes other than default

### ISSUE THREAD

**Issue by quinzee33** [pop-os/beta#411]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

Fresh install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
pop-gtk-theme:
  Installed: 5.5.1~1650296971~22.04~f860355
  Candidate: 5.5.1~1650296971~22.04~f860355
  Version table:
 *** 5.5.1~1650296971~22.04~f860355 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
     5.2.0~1586289568~20.04~f35b83b~ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
pop-shop:
  Installed: 3.4.2pop0~1650311375~22.04~b2e7dbb
  Candidate: 3.4.2pop0~1650311375~22.04~b2e7dbb
  Version table:
 *** 3.4.2pop0~1650311375~22.04~b2e7dbb 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

The Pop Shop now has issues with being readable or missing visual elements on themes other than the default one that comes with Pop.

The default:

![pop_shop_default_theme](https://user-images.githubusercontent.com/101351551/164783451-fdfced9e-b223-43d4-bcc3-e147202a160e.png)

Adwaita is unreadable:

![pop_shop_adwaita](https://user-images.githubusercontent.com/101351551/164783449-26f7fbd4-496b-4123-ab6b-1e06fa17f06e.png)

Yaru-dark is missing the button and background:

![pop_shop_yaru_dark](https://user-images.githubusercontent.com/101351551/164783452-a18fd925-02d1-4742-b1fd-59a614ca3ede.png)

It started looking this way after a recent update to the pop shop a couple days ago.

**Steps to reproduce (if you know):**

Change gtk theme and then open pop shop

**Expected behavior:**

That the app page at least be readable and have a legible button.

**Other Notes:**

**Comment by xploz1on** [comment]
Tested with all these themes:


![image](https://user-images.githubusercontent.com/13008386/164803409-a01cf6d5-2f9c-4034-b2c6-a58e2f7164b0.png)

All are readable within Pop!_Shop. No missing elements. Adwaita el fully readable. Are you fully updated?

**Comment by quinzee33** [comment]
I am indeed fully updated as shown with my apt policy output above. I can show you how the themes change the pop shop here:


https://user-images.githubusercontent.com/101351551/165002703-7a37d64f-a338-4c78-9d12-1c51d83b3767.mp4

Yaru light and Adwaita light are unreadable and the dark versions are missing the button and background elements while it looks normal with the default pop theme.

**Comment by lfom** [comment]
Pop!Shop is based on the ElementaryOS app center, it requires that the theme also include special code for it. Please see:

https://github.com/pop-os/shop/issues/124
https://github.com/jnsh/arc-theme/issues/83

Some themes, like Nordic, support it tho.
