### ISSUE TITLE
Cosmic-dock doesn't work with the "this._monitor is undefined" error.

### ISSUE THREAD

**Issue by oguzkarayemis** [pop-os/beta#414]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
Upgrade from 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Cosmic-dock

**Issue/Bug Description:**

Cosmic-dock doesn't work, instead I've ubuntu dock (I think). In extensions app, I get the "this._monitor is undefined" error.

**Steps to reproduce (if you know):**

**Expected behavior:**

Just a working cosmic-dock.

**Other Notes:**
![Ekran Görüntüsü - 2022-04-23 16-35-55](https://user-images.githubusercontent.com/80787950/164897090-0d32e5b8-fef7-4d4d-b4a7-a1b553719405.png)
![Ekran Görüntüsü - 2022-04-23 16-37-33](https://user-images.githubusercontent.com/80787950/164897188-c5268e25-adbb-4107-bd3f-42020541c354.png)

**Comment by oguzkarayemis** [comment]
After some digging, I could figure out the cause (I believe). I found an (arch) user with the same error: https://github.com/micheleg/dash-to-dock/issues/1687
As in that case, it appears that our issue is related with Turkish locale. When I changed locale to English, there is no problem, everything is just expected. I think this discovery can make easier to fix that issue.

![Screenshot from 2022-04-23 21-24-44](https://user-images.githubusercontent.com/80787950/164936408-3e4b1905-1906-407a-8dc6-6080622acdac.png)

**Comment by oguzkarayemis** [comment]
Hello Turkish locale, the upstream dush-to-dock has a workaround for this, you can add the chanced lines to your / if you feel you can (instead, you just wait to merge for cosmic-dock): https://github.com/micheleg/dash-to-dock/commit/a6447f246ad10075dd8f054b4625bff6009acd02

**Comment by oguzkarayemis** [comment]
Now upstream has a workaround for this bug, I can confirm it works for cosmic-dock too: https://github.com/micheleg/dash-to-dock/commit/a6447f246ad10075dd8f054b4625bff6009acd02

**Comment by oguzkarayemis** [comment]
I closed the issue by accident, sorry for that.

**Comment by mmstick** [comment]
This will be fixed in an upstream update of gjs soon

**Comment by oguzkarayemis** [comment]
After the latest update, all issue is gone now.
