### ISSUE TITLE
Active window is deactivated when going to an empty workspace and coming back.

### ISSUE THREAD

**Issue by oguzkarayemis** [pop-os/beta#415]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 
Upgraded from 21.10.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Cosmic-workspaces.

**Issue/Bug Description:**

I don't know if it's a new feature. When I go to an empty workspace and come back, the window I currently use is deactivated. Activating the current used window takes either a mouse click or activating workspaces overview and coming back when the mouse pointer at the window. If pointer is out of the margins of the current window, the second workaround doesn't work.
This issue doesn't appear for occupied workspaces. 

**Steps to reproduce (if you know):**

1) Go down to an empty workspace with the key combination.
2) Come back.
3) The window you used just before don't active now.

**Expected behavior:**

Active window must be active when you come back.

**Other Notes:**

https://user-images.githubusercontent.com/80787950/164943573-d85635db-51d4-440e-97c4-f8a4cb817848.mp4

**Comment by oguzkarayemis** [comment]
Also, I can confirm that this behavior exist in the recovery partition and live iso, too.

**Comment by guischroeder** [comment]
I'm getting this problem also. Since the major update it has being hard to work with a mouseless workflow :cry:

**Comment by guischroeder** [comment]
My workaround was install gnome-tweaks and enable the option "focus on hover". I have being able to work this manner but the behavior still being a bit awkward.

**Comment by oguzkarayemis** [comment]
Thank you very much, it's quiet a good workaround, but I hope this functionality comes back. Because this workaround has its cons.

**Comment by oguzkarayemis** [comment]
After today's updates, the issue is gone now. Thank you very much devs, I'm closing this now.
