### ISSUE TITLE
Unable to remove brltty package

### ISSUE THREAD

**Issue by MurlocCra4ler** [pop-os/beta#421]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**

 Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
brltty:
  Installed: 6.4-4ubuntu2
  Candidate: 6.4-4ubuntu2
  Version table:
 *** 6.4-4ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
On connecting an Arduinio/ESP32 board with a CP210x USB to serial converter, the brltty daemon grabs the tty from the device and replaces the default kernel driver with its own USB Braille terminal driver.

```
[11077.173032] usb 3-3: USB disconnect, device number 16
[11087.388977] usb 3-3: new full-speed USB device number 17 using xhci_hcd
[11087.586993] usb 3-3: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[11087.587004] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[11087.587008] usb 3-3: Product: CP2102 USB to UART Bridge Controller
[11087.587011] usb 3-3: Manufacturer: Silicon Labs
[11087.587014] usb 3-3: SerialNumber: 0001
[11087.605039] cp210x 3-3:1.0: cp210x converter detected
[11087.611189] usb 3-3: cp210x converter now attached to ttyUSB0
[11095.752194] usb 3-3: usbfs: interface 0 claimed by cp210x while 'brltty' sets config #1
[11095.755262] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[11095.755277] cp210x 3-3:1.0: device disconnected

```

As far as I’m aware this is the correct behavior for the brltty daemon. The solution here would be to uninstall the `brltty` package, which is currently not possible because `pop-desktop` depends on it.

**Expected behavior:**
`pop-desktop` should not depend on `brltty`

**Comment by Miguel-Tradacete-Agreda** [comment]
Hi!
I'm currently using Pop!_OS 22.04 LTS and I had the same issue trying to connect an ESP32 board.
I also couldn't remove brltty daemon as some people suggest.
I found this page with the solution: https://arcanesciencelab.wordpress.com/2022/04/30/a-serious-issue-with-pop_os-22-04/

$ sudo systemctl stop brltty-udev.service
$ sudo systemctl mask brltty-udev.service
Created symlink /etc/systemd/system/brltty-udev.service → /dev/null.
$ sudo systemctl stop brltty.service
$ sudo systemctl disable brltty.service
Unit /etc/systemd/system/brltty.service is masked, ignoring.

This worked for me, although last line ("Unit /etc/systemd/system/brltty.service is masked, ignoring.") didn't appear in my terminal.
I suggest reading that article. The error may reappear if an Pop!_OS's update re-enables that daemon.

**Comment by freefall-nm** [comment]
This also seems to be the case when trying to connect a 3D printer via USB while using Docker containers.

Background:
OS: Pop!_OS 22.04 LTS (also a fresh install)
3D printer: Ender 3 V2
Docker: Octoprint 1.8.1

```
[ 1806.328125] ch341 1-1.3:1.0: ch341-uart converter detected
[ 1806.329583] usb 1-1.3: ch341-uart converter now attached to ttyUSB0
[ 1807.093725] input: BRLTTY 6.4 Linux Screen Driver Keyboard as /devices/virtual/input/input10
[ 1807.291280] usb 1-1.3: usbfs: interface 0 claimed by ch341 while 'brltty' sets config #1
[ 1807.292906] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[ 1807.292970] ch341 1-1.3:1.0: device disconnected
```

The solution provided by @Miguel-Tradacete-Agreda  cleared up the issue (Thanks!)
