### ISSUE TITLE
bring back beta

### ISSUE THREAD

**Issue by SpareEnderboy** [pop-os/beta#424]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
You

**Issue/Bug Description:**
Bring back the Pop-OS 24.04 beta

**Steps to reproduce (if you know):**
It's 24.05 and POS 24.04 didn't release

**Expected behavior:**
To have Pop-OS 24.04

**Other Notes:**
I'm impatient

**Comment by jackpot51** [comment]
We will when it is ready
