### ISSUE TITLE
deb - arduino not showing in popshop. Neovim showing up twice.

### ISSUE THREAD

**Issue by ispanos** [pop-os/beta#44]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
pop-os_20.04_amd64_intel_4.iso
Installed on a VM.
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Arduino, Neovim and possibly others as well.

**Issue/Bug Description:**
The package `arduino` is available using `apt`. In Pop Shop I can only see the flatpak version named `Arduino IDE`. The drop-down menu doesn't have an `apt` option, just `flathub`. Even if I install the deb version of `arduino` it still not showing in pop shop.

Neovim has a somewhat similar issue. There are 3 entries in the search for `Neovim`. 
Obviously `Neovim-qt` is it's own thing, but the other two `Neovim` entries should be one. One is the deb version and the other is the flatpak version. 

**Other Notes:**

There could be more packages like that, but its not a very big deal.

**Comment by ispanos** [comment]
Where you able to replicate that issue on your system?

I tried to find `virt-manager` or `virtual machine manager`, but I got too many results and I couldn't find it. I installed it using `apt` and now it shows up in the *Installed* section.

I tried to find `pcmanfm` and it shows up as `Desktop Preferences`. 

I can't think of other packages to search for.


------------
I don't know if that is an issue or even relevant. The only other GUI  "Software center" I've used was `pamac`, before I switched to Arch, more that a 1,5 years ago. I was used to finding every available package in the repositories. Now I think that only programs with a GUI are in  Pop shop.

**Comment by leviport** [comment]
I saw the same thing with Arduino IDE, yes. 

Pop Shop does omit things that aren't standalone GUI applications. People who need/want those tools are usually comfortable enough installing them with apt anyway.

**Comment by ispanos** [comment]
Anyway, I don't know if its an issue with programs other than arduino.
For **virtual machine manager**, even though I can't find it using the search (the search results are actually very bad on a lot of cases), I can see it in the installed section if I install it using `apt`.

----
On a side note, I don't want to turn this issue in to a discussion, but the way `pamac` works on Manjaro is pretty nice. It shows all of the available package in the repos, regardless of the type - gui/ cli/ tui. Pop shop looks better, but its more convenient to have one place to install everything.

**Comment by WatchMkr** [comment]
@ispanos You can install Synaptic Package Manager (synaptic) if you'd like to have a GUI that shows all applications.

The Arduino .deb in the Ubuntu repos does not have app stream data which is why it doesn't show in Pop Shop. We hope to improve search https://github.com/pop-os/shop/issues/171
