### ISSUE TITLE
shortcuts in russian layout

### ISSUE THREAD

**Issue by lo7ev** [pop-os/beta#48]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 19.10 -> 20.04 with apt

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Win button doesn't open activites or launcer (win+/) in russian layout.

**Steps to reproduce (if you know):**

switch layout to ru
press win button

**Expected behavior:**

open activities

**Other Notes:**

**Comment by leviport** [comment]
Can confirm, Super key doesn't open overview except on the first keyboard layout. It is upstream and I've been monitoring the progress of it here: https://gitlab.gnome.org/GNOME/mutter/-/issues/1144

**Comment by leviport** [comment]
This appears to have been fixed long ago. Closing for now.
