### ISSUE TITLE
New application switcher makes no sense

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#5]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Windows are list twice as you can see in the screenshot. It looks quite irritating.

**Steps to reproduce (if you know):**

Super + /

**Expected behavior:**

Nice icons with text but all uniform

**Other Notes:**
![Screenshot from 2020-04-07 23-28-31](https://user-images.githubusercontent.com/40340217/78725657-ffc4e280-7927-11ea-9746-66c6257118b7.png)

**Comment by WatchMkr** [comment]
Thanks, this bug has been fixed.
