### ISSUE TITLE
left panel is white after coming out of suspend

### ISSUE THREAD

**Issue by sk2d** [pop-os/beta#51]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
This is a fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

After coming back from suspend the left dock is white ([see screenshot](https://drive.google.com/file/d/1uy5ZGXmzMjzq035HFuP0UzeP6i3HxcQB/view?usp=sharing)).  If you click on one of the icons and then the super key a couple of times it comes back.  I have a thinkpad p50s and using the nvidia driver.  It did this in ubuntu 20.04 beta as well.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
