### ISSUE TITLE
Default wallpaper is very similar to window management mode's blue rectangle

### ISSUE THREAD

**Issue by leviport** [pop-os/beta#52]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

The default wallpaper is the issue, not any specific application.

**Issue/Bug Description:**
The light blue wallpaper is almost the same as the light blue window management mode cursor when in light mode, making it difficult to see where I'm moving or repositioning the window. It is lighter in dark mode which makes it more discernible.
![Screenshot from 2020-04-20 13-18-57](https://user-images.githubusercontent.com/13512097/79792815-c7041080-830c-11ea-9cdc-266e60d0611f.png)

**Steps to reproduce (if you know):**
With default wallpaper, hit Super + Enter with tiling mode off, and move the cursor over the blue wallpaper.

**Expected behavior:**
We might want to use a wallpaper that doesn't clash with the window management mode cursor so much.

**Other Notes:**

**Comment by brs17** [comment]
Going to close this as 20.04 has been released.
