### ISSUE TITLE
[20.04] Mouse focus always assumes auto-raise

### ISSUE THREAD

**Issue by adamhassel** [pop-os/beta#53]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Fresh install. Bug is also present when live-booting install ISO (Demo mode).

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome 3.36/Pop Shell

```
gnome-shell:
  Installed: 3.36.1-4ubuntu1pop1~1586887581~20.04~9235f57
  Candidate: 3.36.1-4ubuntu1pop1~1586887581~20.04~9235f57
  Version table:
     3.36.1-5ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
 *** 3.36.1-4ubuntu1pop1~1586887581~20.04~9235f57 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

pop-shell:
  Installed: 0.1.0~1587486784~20.04~0e79c1a
  Candidate: 0.1.0~1587486784~20.04~0e79c1a
  Version table:
 *** 0.1.0~1587486784~20.04~0e79c1a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Enabling mouse focus by setting `org.gnome.desktop.wm.preferences focus-mode 'mouse'` (or `'sloppy'`) makes focus follow mouse. Subsequently, the setting `org.gnome.desktop.wm.preferences auto-raise` has no effect. No matter its setting, auto-raise is always turned on. Similarly, setting `auto-raise-delay` has no effect.

**Steps to reproduce (if you know):**

Set `org.gnome.desktop.wm.preferences focus-mode 'mouse'` (or `'sloppy'`)
Set `org.gnome.desktop.wm.preferences auto-raise 'false'`
Set `org.gnome.desktop.wm.preferences click-to-raise 'true'` (but setting this option on or off has no effect on behavior)

Observe how newly focused windows are raised automatically.

Issue is also present when booting install ISO in "Demo mode": Install gnome-tweak-tool, change focus to mouse/sloppy, verify unchecked Auto-raise option, and observe mouse focus behavior.

**Expected behavior:**

Newly focused windows should only be raised on mouse click.

**Other Notes:**

Maybe something connected with the tiling feature? I don't know, but I assume it does some interesting things with the WM, so could be a side effect of that.

**Comment by adamhassel** [comment]
This issue is NOT present when live booting a vanilla Ubuntu 20.04. As mentioned, it IS present when live booting Pop 20.04, so not an upstream bug. Hopefully this will get more attention as the release spreads and people are hit by it.

**Comment by ajsantander** [comment]
Same here. Cannot turn off "auto raise" or set "auto raise delay" in any way. Mine was a fresh install of 19.04 immediately upgraded to 20.04.

**Comment by thomas-covenant** [comment]
Same here on 20.04. set to click on focus in tweaks, but still autorises.

**Comment by adamhassel** [comment]
https://github.com/pop-os/shell/issues/335 seems to fix this.
