### ISSUE TITLE
Time Format in Gnome Shell after fresh install is Wrong

### ISSUE THREAD

**Issue by srueegger** [pop-os/beta#58]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install

**Issue/Bug Description:**

Sorry for my bad english! 

After installation (language: German and Country: Switzerland), the clock in the Gnome Shell is in 12 hour format (with AM and PM).

In Switzerland (actually all over Europe) the 24 hour format is used.

You can change the format under "Date and Time" in the Gnome settings. However, it would be nice if this were already preconfigured after the installation (or user setup).

**Steps to reproduce (if you know):**

1. Download the beta 20.04 popOS ISO (nvidia)
2. Install it with Language German and Country Switzerland as Settings.

**Other Notes:**
It's not a new Problem, i have the same Issue by installing popOS 19.10.

**Comment by WatchMkr** [comment]
We decided to use the 12 hour format by default but it's at least easily customizable.
