### ISSUE TITLE
Firefox CSD Problem

### ISSUE THREAD

**Issue by srueegger** [pop-os/beta#59]
### Sorry

I have see too late. This is a duplicate from: [this issue](https://github.com/pop-os/beta/issues/2)

**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh Install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
srueegger@pop-os:~$ apt policy firefox
firefox:
  Installiert:           75.0+build3-0ubuntu1
  Installationskandidat: 75.0+build3-0ubuntu1
  Versionstabelle:
 *** 75.0+build3-0ubuntu1 500
        500 http://ch.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
in popOS 20.04 i can't enable the CSD Function in Firefox. I'm not sure what is the correct Name in English. But it's not possible to remove the Titlebar. In popOS 19.10 this works without Problems. In Ubuntu 20.04 works too - it is a Problem with popOS.

**Steps to reproduce (if you know):**
Install Firefox
Right Click to the Firefox "Tab-Bar"
Open "Anpassen" - i think in English is "Customize" but i am not sure
Remove Checkbox "Titelleiste" - in English i think is "Titlebar".

After removing the checkbox, the title bar normally disappears. Now there are just two close buttons at the top right ^^

The Option don't work see Screenshot.

![Bildschirmfoto vom 2020-04-21 20-47-43](https://user-images.githubusercontent.com/11472914/79902216-63174000-8411-11ea-8b61-cfe1926669e9.png)
*

**Comment by rengare** [comment]
Duplicated #2
