### ISSUE TITLE
Some applications linger on the dock despite closed

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#6]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Default dock

**Issue/Bug Description:**

I have noticed a range of applications sometime linger on the dock despite being closed. I am 100% percent this has happened with Firefox and CS:GO, and pretty sure a few others

![Screenshot from 2020-04-08 11-08-10](https://user-images.githubusercontent.com/40340217/78772284-6f1eee80-7989-11ea-85a6-07be26af9f1d.png)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by Kartonrealista** [comment]
To add to this, sometimes they completely bork themselves and refuse to launch in that state

**Comment by daleosm** [comment]
For the time being alt + f2 and enter r fixes it

**Comment by ghisvail** [comment]
Is this only happening on Pop or also in Ubuntu 20.04?

**Comment by AutinMitra** [comment]
It seems like it's related to the pop-shell extension, since the issue only stops for me when I disable it.

**Comment by bobzhu418** [comment]
Every time after rebooting the system, the problem comes back. I have to turn off pop-shell extension from browser's Gnome extensions website, then **Alt + F2** and following by **r**, to make it OK for the session.

**Comment by vooharmy** [comment]
Im experiencings this problem as well. I have two systems that were on 19.10 and I upgraded them to 20.04 with no initial issue but this problem is now presenting. I have disabled all extensions and it still happens and the only temp fix is the alt-f2 r. It appears like the issue is with the launcher because I am able to launch the programs from a terminal but can not use the launcher.

**Comment by Kenryoj** [comment]
> .

Got around this by right clicking a borken icon and launching a new window.

**Comment by Kenryoj** [comment]
> Im experiencings this problem as well. I have two systems that were on 19.10 and I upgraded them to 20.04 with no initial issue but this problem is now presenting. I have disabled all extensions and it still happens and the only temp fix is the alt-f2 r. It appears like the issue is with the launcher because I am able to launch the programs from a terminal but can not use the launcher.

Got around this by right clicking a borken icon and launching a new window.

**Comment by vooharmy** [comment]
> > Im experiencings this problem as well. I have two systems that were on 19.10 and I upgraded them to 20.04 with no initial issue but this problem is now presenting. I have disabled all extensions and it still happens and the only temp fix is the alt-f2 r. It appears like the issue is with the launcher because I am able to launch the programs from a terminal but can not use the launcher.
> 
> Got around this by right clicking a borken icon and launching a new window.

Yeah I was using this work around too. It was not present when I first updated to 20.04 it happened later

**Comment by vooharmy** [comment]
Did some updates today and the issue has dissappeared.

**Comment by bobzhu418** [comment]
Yes! The problem is fixed.

**Comment by knapolian** [comment]
Some applications linger on the dock despite closed should remain open. This behavior does not happen in Pop-OS 2004 in virtualbox, but it does happen on a real installation (even after update and upgrade). When the tiling extension is turned on, closed applications linger on the dock. If refreshed with Alt-F2 r, and then tiling extension is turned off, the problem goes away.
