### ISSUE TITLE
Geary windows overlap in tilling mode

### ISSUE THREAD

**Issue by daleosm** [pop-os/beta#60]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgrade from 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Geary

**Issue/Bug Description:**

Please see attached screenshot.

**Steps to reproduce (if you know):**

Enable tilling mode

**Expected behavior:**

Uniform look

![Screenshot from 2020-04-21 20-31-32](https://user-images.githubusercontent.com/40340217/79906333-83de9600-840f-11ea-8904-d140fb4cd7a8.png)

**Other Notes:**

**Comment by WatchMkr** [comment]
Geary has some issues sizing down.We hope to remove the overlap by adjust the rest of the tree to accommodate apps that have large minimum sizes.

Closing as duplicate: https://github.com/pop-os/shell/issues/85
