### ISSUE TITLE
Pop!_OS 20.04 beta iso file checksums

### ISSUE THREAD

**Issue by hakpw** [pop-os/beta#66]
I can't find the checksum for the beta iso anywhere, can you please help?

**Comment by mikemadden42** [comment]
You can download the sha256 sums here.

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/4/SHA256SUMS

```
4a7e1c8970bdd03d073a765fbc18ceca4245e309f444f1e9b5489f06a0a0b422 *pop-os_20.04_amd64_intel_4.iso
```

**Comment by hakpw** [comment]
Thanks :)
