### ISSUE TITLE
Fractional Scaling zooms to a portion of the screen at 125%, broken at rest

### ISSUE THREAD

**Issue by shritesh** [pop-os/beta#67]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Fresh ISO install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Settings Manager? X11?

**Issue/Bug Description:**

Selecting 125% zooms into a portion of the screen at a time which moves around when I mouse around the edges. Selecting 150% and the rest simply displays a black screen and returns back to previous setting after a while.

**Steps to reproduce (if you know):**

Enable fractional scaling and select any of the scaling options.

**Expected behavior:**

The screen should be shown zoomed out at 125% and the display shouldn’t blank out at other display scaling.

**Other Notes:**

I was previously using the `x-11-randr-fractional-scaling` setting for mutter in 19.10 without any issue.

I’m running the NVidia ISO with a 1080TI GPU on an Acer S277HK Monitor at 3840 x 2160 resolution on a freshly installed system and all updates installed.

**Comment by WatchMkr** [comment]
Duplicate. Added your notes here: https://github.com/pop-os/beta/issues/35
