### ISSUE TITLE
Tile Windows: Maximizing window does not work properly for some apps if they are not at the top-left position

### ISSUE THREAD

**Issue by bobzhu418** [pop-os/beta#68]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Fresh install
 
**Issue/Bug Description:**

Tile Windows: Maximizing window does not work properly for some chromium based and electron based apps if they are not at the top-left position.

**Steps to reproduce (if you know):**

* Enable Tile Windows
* Open a few apps, including Chromium, Chrome or VS Code
* Move Chromium, Chrome or VS Code to a position that is not top-left
* Click Maximize button

**Expected behavior:**

The app should take whole screen after clicking Maximize button

**Other Notes:**

The affected app also stops respond after the Maximizing window problem. Clicking other app/window can bring the affected app back to normal.

**Comment by Kartonrealista** [comment]
@WatchMkr 
Maybe this should be moved to Pop shell

**Comment by brs17** [comment]
This issue seems to have been resolved. If the issue persists, please file an issue here: https://github.com/pop-os/shell/issues
