### ISSUE TITLE
Popos not booting

### ISSUE THREAD

**Issue by bukyapavankumar** [pop-os/beta#71]
I did a Fresh install of popos beta .
I made a bootable usb with Rufus on windows 10.
When I boot it .it says vmlinuz.efi Has invalid signature.kernel has to be loaded first etc.

I tried with secure boot off too but it said kernal panic and stuck.

My laptop is dell Inspiron 3543 8gb ram hd 5500
Nvidia GeForce 820m.

**Comment by devinceble** [comment]
Try using balena etcher to flash your usb.

**Comment by bukyapavankumar** [comment]
Ain't Rufus supported?

**Comment by devinceble** [comment]
It should be supported but on my experience rufus works best flashing windows ISO.

**Comment by bukyapavankumar** [comment]
Same with etcher and 19.10 iso too has this issue for me
