### ISSUE TITLE
Python won't update after upgrade from 19.10 to 20.04

### ISSUE THREAD

**Issue by madredhatter22** [pop-os/beta#74]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
Upgraded from 19.10 to 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Right after the upgrade, I was prompted for an available update with 7 packages. Four of the python packages have been held back and will not update.

From Terminal:

libpython2-stdlib/focal 2.7.17-2ubuntu4 amd64 [upgradable from: 2.7.17-1]
python2-minimal/focal 2.7.17-2ubuntu4 amd64 [upgradable from: 2.7.17-1]
python2/focal 2.7.17-2ubuntu4 amd64 [upgradable from: 2.7.17-1]
python/focal,focal 2.7.17-2pop1~1580508288~20.04~6895a24 amd64 [upgradable from: 2.7.17-1]

From PopShop
4 components with updates:
 • libpython2-stdlib interactive high-level object-oriented language (Python2) Version: 2.7.17-2ubuntu4
 • python Transitional metapackage for python2 Version: 2.7.17-2pop1~1580508288~20.04~6895a24
 • python2 interactive high-level object-oriented language (Python2 version) Version: 2.7.17-2ubuntu4
 • python2-minimal minimal subset of the Python2 language Version: 2.7.17-2ubuntu4

**Issue/Bug Description:**

Failure to update python packages following upgrade from 19.10 to 20.04

**Steps to reproduce (if you know):**

system upgrade followed by update

**Expected behavior:**

packages to update

**Other Notes:**

**Comment by cschneider005** [comment]
### Python dependencies are not configured properly, hopefully this ends up being fixed in full release. Attempting to update with the terminal gives a lot more info:

```
user@localhost:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libpython2-stdlib python python2 python2-minimal
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

### If you try to upgrade python individually:

```
user@localhost:~$ sudo apt upgrade python2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python : Depends: python2 (= 2.7.17-1) but 2.7.17-2ubuntu4 is to be installed
 python2 : PreDepends: python2-minimal (= 2.7.17-2ubuntu4) but 2.7.17-1 is to be installed
           Depends: libpython2-stdlib (= 2.7.17-2ubuntu4) but 2.7.17-1 is to be installed
E: Broken packages
```

#### As you can see, python depends on having **_exactly_** version 2.7.17-1, but 2.7.17-2 is already installed; same for python2.

#### If you try and fresh install python2:

```
user@localhost:~$ sudo apt install python2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  appstream-data-pop appstream-data-pop-icons apt-config-icons-hidpi apt-config-icons-large apt-config-icons-large-hidpi gir1.2-ostree-1.0 icu-devtools libflatpak-dev libicu-dev libostree-dev libxml2-dev python-certifi python-cffi-backend python-chardet python-cryptography python-enum34 python-idna python-ipaddress
  python-openssl python-pkg-resources python-six python3-pyflatpak
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpython2-stdlib python2-minimal
Suggested packages:
  python2-doc python-tk
The following packages will be REMOVED:
  libpython-stdlib pop-desktop pop-shop python python-minimal python-requests python-urllib3 repoman
The following packages will be upgraded:
  libpython2-stdlib python2 python2-minimal
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-shop (due to pop-desktop)
3 upgraded, 0 newly installed, 8 to remove and 0 not upgraded.
Need to get 61.1 kB of archives.
After this operation, 3,551 kB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?]
```
 
#### I haven't actually chosen 'Yes, do as I say!', because I honestly doubt it would work anyway. Any combination of upgrade/update/install commands I tried for python result in unmet dependency errors, or broken/held package errors.

#### Personally I would just wait for full release unless an update is pushed out to fix the issue. From one of the upgrade messages above:

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.

### We're definitely using an unstable distro. So best to just wait.

**Comment by bufke** [comment]
This looks fixed. I was able to uninstall python2. I had to be explicit about uninstall all py2 packages. 
`sudo apt remove python-six pyflakes python-cryptography python-openssl python python2 python-minimal python-chardet  python-certifi python-cffi-backend python-enum34 python-pyflakes python-pkg-resources python-ipaddress python-idna python-setuptools`

The command above may very depending on what packages you had installed. After removing python2 I could `apt dist-upgrade` again without error.

**Comment by btegs** [comment]
Btw I have boot-repair from the PPA installed from earlier which explains the boot-repair dependencies, but this is what I get:

```
brian@pop-os:~$ sudo apt remove python2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  efibootmgr gir1.2-appindicator3-0.1 libpython2-stdlib pastebinit python2-minimal syslinux-common
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  boot-repair boot-sav boot-sav-extra glade2script python-cffi-backend python-cryptography python-enum34 python-gi python-ipaddress python-openssl
  python-six python2
0 upgraded, 0 newly installed, 11 to remove and 0 not upgraded.
After this operation, 6,430 kB disk space will be freed.
```

**Comment by v-kelkar** [comment]
If you try to install `atom` you end up with python2 packages 
```
sudo apt install atom            
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpython2-stdlib python python2 python2-minimal
Suggested packages:
  gir1.2-gnomekeyring-1.0 python2-doc python-tk
The following NEW packages will be installed:
  atom libpython2-stdlib python python2 python2-minimal
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 112 MB/112 MB of archives.
After this operation, 623 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

**Comment by btegs** [comment]
> If you try to install `atom` you end up with python2 packages
> 
> ```
> sudo apt install atom            
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   libpython2-stdlib python python2 python2-minimal
> Suggested packages:
>   gir1.2-gnomekeyring-1.0 python2-doc python-tk
> The following NEW packages will be installed:
>   atom libpython2-stdlib python python2 python2-minimal
> 0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
> Need to get 112 MB/112 MB of archives.
> After this operation, 623 MB of additional disk space will be used.
> Do you want to continue? [Y/n] n
> ```

What if you install atom via a Snap package? That way, all the dependencies are self contained and not reliant on the system.

`sudo snap install atom --classic`
