### ISSUE TITLE
URW Gothic font family not working in installer

### ISSUE THREAD

**Issue by subhashissuara** [pop-os/beta#75]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 I booted live session from USB for installation

**Issue/Bug Description:**
I booted a live session for installation and wanted to try things out. I installed gnome tweaks and changed the font to URW Gothic Demi as I use it everyday. The text on left side under the images of the installer are not working and this issue persists in further menus. I noticed this issue throughout the URW Gothic font family.

**Steps to reproduce (if you know):**
![Bug](https://user-images.githubusercontent.com/28859415/80233656-7bd36000-8674-11ea-820e-3688dd54a905.png)

**Comment by jackpot51** [comment]
You should do this configuration after installation, it will not persist from the live session to the installed system
