### ISSUE TITLE
19.10 to 20.04 failed after reboot

### ISSUE THREAD

**Issue by flowerinthenight** [pop-os/beta#78]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Upgrade
19.10 to 20.04 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

NA

**Issue/Bug Description:**
Upgrade using pop-upgrade went alright but after reboot, the upgrade won't proceed and goes into an endless loop of reboots.

**Steps to reproduce (if you know):**
1) Update using pop-upgrade utility. Removed incompatible repos as well.
![1](https://user-images.githubusercontent.com/12397229/80246691-ca4e2200-86a7-11ea-8cd5-47bb43939513.jpeg)

2) After reboot, it only says it failed.
![2](https://user-images.githubusercontent.com/12397229/80246821-05505580-86a8-11ea-9d24-c859ec1bef81.jpeg)

![3](https://user-images.githubusercontent.com/12397229/80246846-0f725400-86a8-11ea-957b-b55b1199abb1.jpeg)

**Expected behavior:**
Successful upgrade.

**Other Notes:**
Any info into how to check logs somewhere when this failure occurs would probably help?

**Comment by StrictTangent** [comment]
I experienced something similar.
I was able to finish my install by going to the TTY (cntrl+alt+f3) and using:
sudo apt -f install
sudo apt full-upgrade

then reboot

**Comment by flowerinthenight** [comment]
@StrictTangent I tried again. Ctrl+Alt+F3 didn't work. No TTY showing up. It will just go on rebooting endlessly.

**Comment by brs17** [comment]
There were a number of upgrade fixes over the past few days: https://github.com/pop-os/upgrade/commits/master. With the official release of 20.04 today, I am going to close this issue but if you have additional upgrade issues, please file additional issues in the upgrade repository.

**Comment by joselufo** [comment]
@brs17 I´m still having this issue, the system doesn´t stop rebooting and trying to upgrade but it always fails. 

Ctrl +Alt + F3 didn´t work, no TTTY showing up. 

Is there any way to cancel the process?

**Comment by rpalaciosg** [comment]
@joselufo Hello, maybe you found something to cancel that restart loop?

**Comment by joselufo** [comment]
@rpalaciosg not really. I needed to format and install the new OS from scratch.
