### ISSUE TITLE
[20.04] Region & Language 

### ISSUE THREAD

**Issue by tchuyev** [pop-os/beta#80]
Defining United States (English) as the default system language and e.g. French as a keyboard layout during install would NOT change the Region & Language / Format to **French** (stuck in United States).

Works perfect on Ubuntu 20.04 LTS though: defining United States (English) as the default system language and French as the keyboard layout would result in automatically changing the Region & Language / Format to **French**, which is the expected result

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
