### ISSUE TITLE
How To Help With Translations?

### ISSUE THREAD

**Issue by djohannes** [pop-os/beta#81]
Hey, I have a simple question with the 20.04 beta: All the strings coming from Pop OS (the new window tilling, additional settings, etc.) are not translated at all and e.g. the default keyboard shortcuts are only made for the US keyboard layout and don't automatically adapt to other layouts.

Is there a way to help with that, especially translations?

**Comment by brs17** [comment]
Translations can be provided to the specific project that has the specific change. All Pop!_OS projects can be found under https://github.com/pop-os/. If you find a project that has no translation support, please file an issue in that specific project. For example Pop!_Shop translations live here: https://github.com/pop-os/shop/tree/master/po
