### ISSUE TITLE
[20.04] Install error: error installing packages

### ISSUE THREAD

**Issue by zaphod80013** [pop-os/beta#82]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 Clean install on GalagoPro3 over 19.10 installed on luks partition.
Encrypt partition option selected with same password as used to decrypt
[installer.log](https://github.com/pop-os/beta/files/4532143/installer.log)

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**
Clean install failed

**Steps to reproduce (if you know):**
Download pop-os_20.04_amd64_intel_4.iso
burn to usb dd if= of= bs=128M conv=fsync
Boot installer from USB
Accept all defaults till install choice page
Unlock existing luks partition accepting cryptdata as name
Select clean install
Install runs but at end reports failed due to hardware error
attempted retry - same result
install log reports exit code 100 from install packages 

**Expected behavior:**
A working OS

**Other Notes:**
If upload worked correctly the installer log should be attached.
Possibly useful info (UNTITLED used after fail to transfer my github password so I could login to report)
pop-os@pop-os:~$ df -hT
Filesystem                  Type      Size  Used Avail Use% Mounted on
udev                        devtmpfs   16G     0   16G   0% /dev
tmpfs                       tmpfs     3.2G   11M  3.1G   1% /run
/dev/sdb1                   iso9660   2.1G  2.1G     0 100% /cdrom
/dev/loop0                  squashfs  2.0G  2.0G     0 100% /rofs
/cow                        overlay    16G  2.2G   14G  15% /
/dev/disk/by-label/writable ext4       13G   41M   12G   1% /var/log
tmpfs                       tmpfs      16G   26M   16G   1% /dev/shm
tmpfs                       tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs                       tmpfs      16G     0   16G   0% /sys/fs/cgroup
tmpfs                       tmpfs      16G  564K   16G   1% /tmp
tmpfs                       tmpfs     3.2G   84K  3.2G   1% /run/user/999
/dev/sdc2                   vfat       29G  2.4G   27G   9% /media/pop-os/UNTITLED
/dev/mapper/data_qVqS8-root ext4      1.8T  5.4G  1.7T   1% /media/pop-os/38f624ba-45b9-422f-846e-9356f5518f1f
pop-os@pop-os:~$ lsblk
NAME                  MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0                   7:0    0     2G  1 loop  /rofs
sda                     8:0    0 931.5G  0 disk  
└─sda1                  8:1    0 931.5G  0 part  
sdb                     8:16   1  14.8G  0 disk  
├─sdb1                  8:17   1   2.1G  0 part  /cdrom
├─sdb2                  8:18   1     4M  0 part  
└─sdb3                  8:19   1  12.7G  0 part  /var/crash
sdc                     8:32   1  28.9G  0 disk  
├─sdc1                  8:33   1   200M  0 part  
└─sdc2                  8:34   1  28.7G  0 part  /media/pop-os/UNTITLED
nvme0n1               259:0    0   1.8T  0 disk  
├─nvme0n1p1           259:5    0   498M  0 part  
├─nvme0n1p2           259:6    0     4G  0 part  
├─nvme0n1p3           259:7    0   1.8T  0 part  
│ └─cryptdata_PDuhz   253:0    0   1.8T  0 crypt 
│   └─data_qVqS8-root 253:1    0   1.8T  0 lvm   /media/pop-os/38f624ba-45b9-422f-846e-9356f5518f1f
└─nvme0n1p4           259:8    0     4G  0 part  
pop-os@pop-os:~$ sudo parted --script /dev/nvme0n1 u mib p
Model: Samsung SSD 970 EVO 2TB (nvme)
Disk /dev/nvme0n1: 1907729MiB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start       End         Size        File system     Name      Flags
 1      2.00MiB     500MiB      498MiB      fat32                     boot, esp
 2      500MiB      4596MiB     4096MiB     fat32           recovery  msftdata
 3      4596MiB     1903631MiB  1899035MiB
 4      1903631MiB  1907727MiB  4096MiB     linux-swap(v1)            swap

**Comment by zaphod80013** [comment]
Additional info, manually zeroed gpt partition table (both copies) and partition boundaries then reattempted install behaved the same.

Redownloaded under OS X and re-imaged USB stick using BalenaEtcher, install ran fine after that, I've left ticket open incase the log is of any use, feel free to close as not a defect.

**Comment by brs17** [comment]
Thank you for filing the issue, there's always seems to be some quirks with different image flashing methods, but I'm glad you got it working!
