### ISSUE TITLE
[20.04] Persistent power settings on laptop

### ISSUE THREAD

**Issue by jdgarcia1381** [pop-os/beta#85]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
 Fresh install.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Power Settings.

**Issue/Bug Description:**
Laptop power setting is not persistent. Will go back to 'Balanced' after boot.
![Screenshot from 2020-04-25 13-29-42](https://user-images.githubusercontent.com/13160502/80287873-9c91c900-86f9-11ea-939e-3da82a900d71.png)

**Steps to reproduce (if you know):**
-On laptop, set power settings to 'High Performance'
-Reboot
-Power setting will now default to 'Balanced'.

**Expected behavior:**
Power settings are persistent after boot. Also, is there any way those settings apply differently if AC adapter is connected? For example, set 'High Performance' on AC, and 'Balanced' on battery.

**Other Notes:**
Everything else is working as expected. Tested on Laptop and Desktop with fresh installs. Thank you!

**Comment by brs17** [comment]
This is something we hope to solve when we address adding a configuration file to system76-power: https://github.com/pop-os/system76-power/issues/2 we will track this request there.
