### ISSUE TITLE
Advice on testing

### ISSUE THREAD

**Issue by sindile** [pop-os/beta#89]
Hello,
I currently use Ubuntu and would like to move to Pop-os
My laptop has the following graphics cards
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)

I see that beta has an Intel iso and Nvidia iso -  should I use Nvidia?

**Comment by tchuyev** [comment]
Just go with the NVIDIA version

**Comment by sindile** [comment]
Noted.
