### ISSUE TITLE
[20.04] Trouble with Pop!_Shop updates after upgrade from 19.10

### ISSUE THREAD

**Issue by nlander** [pop-os/beta#92]
**How did you upgrade to 20.04?**
I  upgraded from 19.10

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop

**Issue/Bug Description:** The first suggested updates after upgrade and reboot don't install. Clicking the Update All button seems to elicit activity in the GUI but it does not resolve the update. There appear to be operating system updates and drivers to install. Clicking the operating system Update button appears to have the same behavior as the Update All button. The Install button for the drivers displays an error message: "There Was An Error Installing (null). The package id's '' are not valid"

**Steps to reproduce:**
- Open Pop!_Shop
- Click Update All
- Click the individual Update button for the operating system updates
- Click the Install button for the drivers

**Expected behavior:**
- This should install the updates and then dismiss the update availability message.
- An installation success message would be nice.

**Comment by nlander** [comment]
![Screenshot from 2020-04-26 15-10-17](https://user-images.githubusercontent.com/5264410/80318489-21e7ad00-87d0-11ea-9909-f794e89b6744.png)
This is the update availability panel that never gets dismissed.

**Comment by nlander** [comment]
![Screenshot from 2020-04-26 15-12-34](https://user-images.githubusercontent.com/5264410/80318534-73903780-87d0-11ea-8393-b7826d77517a.png)
This is the error message after clicking the Install button for the drivers.

**Comment by ankushdas9** [comment]
I can confirm this happening to me as well, even though I did a fresh install.

https://i.imgur.com/ABnZIce.png

After the latest update notification, I can see the null driver on the Pop!_Shop which when clicked displays the same error as described above.

**Comment by brs17** [comment]
The null driver has been resolved with this: https://github.com/pop-os/shop/pull/181
