### ISSUE TITLE
[20.04] Signing into Google service crashed GUI

### ISSUE THREAD

**Issue by msarahan** [pop-os/beta#93]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 fresh install

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Not sure - whatever the initial account setup program is

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

* install 20.04 beta on a clean system, but with an existing home partition from an earlier Ubuntu 18.04 and later Ubuntu 20.04 installation.
* Reboot
* Go through initial setup steps. When shown list of service that gnome can connect to, choose google.
* Sign in, do multifactor. When google asks to grant gnome permission, say OK.
* crash

* I used the 3 finger salute to reboot after a few min of a black screen: ctrl alt del

**Expected behavior:**

sign in successfully and definitely not crash the UI

**Other Notes:**

I haven't spent a ton of time trying to reproduce this. I need my computer to be up during the week, but could try to help isolate the issue next weekend if it would be helpful.

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
