### ISSUE TITLE
[20.04] light/dark appearance didn't "stick" after initial setup

### ISSUE THREAD

**Issue by msarahan** [pop-os/beta#94]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

 
fresh install
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

initial user setup program

**Issue/Bug Description:**

I chose "dark" during setup, but it changed back to "light" by itself somehow.

**Steps to reproduce (if you know):**

* fresh install
* choose dark theme during setup
* finish setup
* look at settings/appearance/appearance - here, light was selected for me.

**Expected behavior:**

theme chosen during initial setup should stay in use.

**Other Notes:**

**Comment by WatchMkr** [comment]
We decided to pull the dark/light mode change in initial setup for the time being.
