### ISSUE TITLE
[20.04] Laptop wakes from suspend on power unplug

### ISSUE THREAD

**Issue by adamhassel** [pop-os/beta#97]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**

Fresh install
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

systemd:
  Installed: 245.4-4ubuntu1~1587437360~20.04~2ea75ac
  Candidate: 245.4-4ubuntu1~1587437360~20.04~2ea75ac
  Version table:
     245.4-4ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
 *** 245.4-4ubuntu1~1587437360~20.04~2ea75ac 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Laptop wakes from suspend if power is unplugged

**Steps to reproduce (if you know):**

* While plugged in, suspend laptop
* Unplug laptop power
* Observe that laptop wakes up from suspend

**Expected behavior:**

Laptop remains suspended if power is unplugged

**Other Notes:**

Dell XPS 13 9360

**Comment by bflanagin** [comment]
With 21.04 fast approaching this issue is being closed to make new issues more visible. If the problem persists we can reference this ticket in the newer one.
