### ISSUE TITLE
[20.04] overview with super key stops working when input source changes

### ISSUE THREAD

**Issue by nabinbogati** [pop-os/beta#98]
![pop](https://user-images.githubusercontent.com/26008383/80360056-7eb19900-889e-11ea-90ed-24e03cd2831e.gif)
**How did you upgrade to 20.04? (Fresh install / Upgrade)** Fresh Install

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Input Sources

**Issue/Bug Description:**
Whenever i use more than one input sources and switch back and forth between them, the overview shortcut with super key doesn't work at all. It happens if i am using the input source other than the default or say first on list.

**Steps to reproduce (if you know):**
1. Go to gnome settings app.
2. Go to Region and Language.
3. Add an input source from Input Sources category using the '+' icon.
4. Now, switch the input sources using shortcut Super+Space or use icon at top right corner of the panel.
5. Then, try using Super key to access gnome-overview
6. If it works then try switching sources to another input source and try again you should get the bug.

**Expected behaviour:**
Overview should work on every input sources.

**Other Notes:**

**Comment by leviport** [comment]
Thank you for the report! As a Dvorak user, I've also been frustrated by this bug lately. It seems to be a Gnome upstream issue which is being tracked here: https://gitlab.gnome.org/GNOME/mutter/-/issues/1144  Please give it a +1 as well to let them know you're also experiencing it.

**Comment by leviport** [comment]
Since this issue is still present, I'm reopening it. The current status is that Mutter was patched by Gnome, but the fix hasn't been released by Ubuntu quite yet. The progress can now be tracked here: https://bugs.launchpad.net/ubuntu/focal/+source/mutter/+bug/1871913

**Comment by antonioqfel** [comment]
I had created an [issue](https://github.com/pop-os/pop/issues/1026) on this as well. Since it's a duplicate, they have closed it.

Good to know they are working on it.

**Comment by allexus39** [comment]
https://bugs.launchpad.net/ubuntu/focal/+source/mutter/+bug/1871913
Finally, the fix has been released. 

It works great now.

**Comment by leviport** [comment]
I installed updates this morning and saw that mutter 3.36.2 was released, and the super key now works on both of my keyboard layouts.
