### ISSUE TITLE
[20.04] Custom shell theme won't stick

### ISSUE THREAD

**Issue by john-ghatas** [pop-os/beta#99]
**How did you upgrade to 20.04? (Fresh install / Upgrade)** Fresh install

 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

GNOME 3.36

**Issue/Bug Description:**
When I apply a custom **shell** theme, it doesn't stick after reboot and I have to re-apply

**Steps to reproduce (if you know):**
- Enable User Theme GNOME extension
- Apply custom shell theme with Gnome Tweaks
- Reboot

**Expected behavior:**
The shell theme defaults back to the pop-os one, the GTK/App theme stays the same

**Other Notes:**
None

**Comment by devcass** [comment]
How did you apply the theme?
With gnome tweaks?

**Comment by john-ghatas** [comment]
Yes, I applied it with Gnome Tweaks

**Comment by john-ghatas** [comment]
The options stays on what I set it to (in my case XO_CATALINA_NIGHT), but it defaults back to PopOS default theme ignoring the shell setting from Gnome Tweaks itself. I have to set it to another theme and set it back to the shell theme I want it on to turn back to my preference.

**Comment by john-ghatas** [comment]
A little update on the situation:
After suspending the laptop and logging in again after logging in after boot, the system sets the shell theme correctly.

**Comment by amithiel** [comment]
can confirm this too. my theme was going fine until I hit alt+f2 and restarted the shell

**Comment by mdhishaamakhtar** [comment]
your theme is not stored in /usr/lib

**Comment by john-ghatas** [comment]
I always stored then in ~/.themes and it worked fine, with the beta it glitches and I have to manually apply it when changing the background or after reboot.

**Comment by amithiel** [comment]
> your theme is not stored in /usr/lib

Thats new for me. Since when in any distro, is mandatory to install themes in other than ~/.themes ?

**Comment by john-ghatas** [comment]
> > your theme is not stored in /usr/lib
> 
> Thats new for me. Since when in any distro, is mandatory to install themes in other than ~/.themes ?

Manjaro with Gome 3.36 retains the ~/.themes structure as well, so the glitch is on the popos side

**Comment by john-ghatas** [comment]
![image](https://user-images.githubusercontent.com/14125058/80624752-6a130380-8a4c-11ea-8e16-012e0c7c41f0.png)
Neofetch screenshot for reference

**Comment by cartoonc4t** [comment]
I have a similar problem but with the 'application theme' in gnome tweaks reverting to 'pop-dark'. The revert happens when you launch any of the 3 options from the context menu on the desktop (change background, display settings, settings). I suspect the backend of the appearance tab containing light and dark theme next to the background tab is causing the revert when the entire settings window is loaded. This happens in the 20.04 beta and the release.

**Comment by paolocalosso** [comment]
> The options stays on what I set it to (in my case XO_CATALINA_NIGHT), but it defaults back to PopOS default theme ignoring the shell setting from Gnome Tweaks itself. I have to set it to another theme and set it back to the shell theme I want it on to turn back to my preference.

confirm. i have the same issue since pop_os 20.04 installed.

**Comment by john-ghatas** [comment]
> I have a similar and probable related problem but with the 'application theme' in gnome tweaks reverting to 'pop-light' or 'pop-dark'. The revert happens when you launch any of the 3 options from the context menu on the desktop (change background, display settings, settings). I suspect the backend of the appearance tab containing light and dark theme next to the background tab is causing the revert when the entire settings window is loaded. This happens in the 20.04 beta and the release.

Encoutered this as well ^

**Comment by SwisSlow** [comment]
I find a solution maybe:
The error occur when you enable the User Theme from the browser. If so, try this:

1) Install User Themes from gnome extensions (browser)

2) disable User Themes

3) Reboot

4) open "extension" app of Pop!_OS

5) Enable User Themes

6) Open Gnome-Tweaks, apply the Theme and Press Alt + F2 and then "r"

For me It Works!!!

**Comment by john-ghatas** [comment]
> I find a solution maybe:
> The error occur when you enable the User Theme from the browser. If so, try this:
> 
>     1. Install User Themes from gnome extensions (browser)
> 
>     2. disable User Themes
> 
>     3. Reboot
> 
>     4. open "extension" app of Pop!_OS
> 
>     5. Enable User Themes
> 
>     6. Open Gnome-Tweaks, apply the Theme and Press Alt + F2 and then "r"
> 
> 
> For me It Works!!!

Not working, the issues still persist

**Comment by SwisSlow** [comment]
> > I find a solution maybe:
> > The error occur when you enable the User Theme from the browser. If so, try this:
> > ```
> > 1. Install User Themes from gnome extensions (browser)
> > 
> > 2. disable User Themes
> > 
> > 3. Reboot
> > 
> > 4. open "extension" app of Pop!_OS
> > 
> > 5. Enable User Themes
> > 
> > 6. Open Gnome-Tweaks, apply the Theme and Press Alt + F2 and then "r"
> > ```
> > 
> > 
> > For me It Works!!!
> 
> Not working, the issues still persist

Try to deactivate Pop_OS Shell in extension too...

**Comment by john-ghatas** [comment]
> > > I find a solution maybe:
> > > The error occur when you enable the User Theme from the browser. If so, try this:
> > > ```
> > > 1. Install User Themes from gnome extensions (browser)
> > > 
> > > 2. disable User Themes
> > > 
> > > 3. Reboot
> > > 
> > > 4. open "extension" app of Pop!_OS
> > > 
> > > 5. Enable User Themes
> > > 
> > > 6. Open Gnome-Tweaks, apply the Theme and Press Alt + F2 and then "r"
> > > ```
> > > 
> > > 
> > > For me It Works!!!
> > 
> > 
> > Not working, the issues still persist
> 
> Try to deactivate Pop_OS Shell in extension too...

Thanks, that worked wonders, only fixes the restart issue the settings defaulting back the default theme is still present.

**Comment by danialkeimasi** [comment]
> I have a similar and probable related problem but with the 'application theme' in gnome tweaks reverting to 'pop-light' or 'pop-dark'. The revert happens when you launch any of the 3 options from the context menu on the desktop (change background, display settings, settings). I suspect the backend of the appearance tab containing light and dark theme next to the background tab is causing the revert when the entire settings window is loaded. This happens in the 20.04 beta and the release.

confirm. same issue with pop_os 20.04 installed.

**Comment by mmstick** [comment]
This is being fixed. You can track the fix here: https://github.com/pop-os/shell/pull/271

**Comment by john-ghatas** [comment]
Just upgraded the packages. If fixes this issue, on reboot it still defaults back to pop-dark on reboot.

> > I have a similar and probable related problem but with the 'application theme' in gnome tweaks reverting to 'pop-light' or 'pop-dark'. The revert happens when you launch any of the 3 options from the context menu on the desktop (change background, display settings, settings). I suspect the backend of the appearance tab containing light and dark theme next to the background tab is causing the revert when the entire settings window is loaded. This happens in the 20.04 beta and the release.
> 
> confirm. same issue with pop_os 20.04 installed.

**Comment by yurikilian** [comment]
Hello,

While the correction is not deployed, this can work:
- Select your desired shell theme
- Create the following script and save on the desired folder:
`
gnome-extensions disable user-theme@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com
`
- Chmod +x script.sh and add to startup

This works for me (again, as workaround only)

**Comment by john-ghatas** [comment]
Issue has been resolved with the latest update, closing the issue now :). Thanks for the cooperation!
